["shortest_path"] # TODO: runtime failed. why?
ignore = true

["strongly_connected_component"] # TODO: runtime failed. why?
ignore = true

["topological_sorting"] # TODO: runtime failed. why?
ignore = true
