export namespace fast_io
{
namespace containers
{
using ::fast_io::containers::array;
using ::fast_io::containers::operator==;
using ::fast_io::containers::operator<=>;
using ::fast_io::containers::swap;
} // namespace containers

namespace tlc
{
using ::fast_io::tlc::array;
using ::fast_io::tlc::to_array;
} // namespace tlc

using ::fast_io::array;
using ::fast_io::containers::to_array;
} // namespace fast_io