export namespace fast_io
{
namespace containers
{
using ::fast_io::containers::null_terminated_t;
using ::fast_io::containers::null_terminated;

using ::fast_io::containers::basic_string_view;
using ::fast_io::containers::basic_cstring_view;
using ::fast_io::containers::operator==;
using ::fast_io::containers::operator<=>;
using ::fast_io::containers::swap;
using ::fast_io::containers::print_alias_define;
} // namespace containers

using ::fast_io::string_view;
using ::fast_io::wstring_view;
using ::fast_io::u8string_view;
using ::fast_io::u16string_view;
using ::fast_io::u32string_view;

using ::fast_io::cstring_view;
using ::fast_io::wcstring_view;
using ::fast_io::u8cstring_view;
using ::fast_io::u16cstring_view;
using ::fast_io::u32cstring_view;

using ::fast_io::basic_string_view;

} // namespace fast_io