#pragma once
#include"floating_traits.h"
#include"fixed_table.h"
#include"dbl_table.h"
#include"operations.h"
#include"fixed.h"
#include"tos.h"
#include"stack_arbitary_int.h"
#include"precise.h"
//#include"sto.h"
#include"sto_reserve.h"