#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Arabic locale for Saudi Arabia"),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Arabic"),.territory=tsc("Saudi Arabia"),.revision=tsc("1.0"),.date=tsc("2000-06-29")},.monetary={.int_curr_symbol=tsc("SAR "),.currency_symbol=tsc("ر.س"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(""),.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc("")},.time={.abday={tsc("ح"),tsc("ن"),tsc("ث"),tsc("ر"),tsc("خ"),tsc("ج"),tsc("س")},.day={tsc("الأحد"),tsc("الإثنين"),tsc("الثلاثاء"),tsc("الأربعاء"),tsc("الخميس"),tsc("الجمعـة"),tsc("السبت")},.abmon={tsc("يناير"),tsc("فبراير"),tsc("مارس"),tsc("أبريل"),tsc("مايو"),tsc("يونيو"),tsc("يوليو"),tsc("أغسطس"),tsc("سبتمبر"),tsc("أكتوبر"),tsc("نوفمبر"),tsc("ديسمبر")},.mon={tsc("يناير"),tsc("فبراير"),tsc("مارس"),tsc("أبريل"),tsc("مايو"),tsc("يونيو"),tsc("يوليو"),tsc("أغسطس"),tsc("سبتمبر"),tsc("أكتوبر"),tsc("نوفمبر"),tsc("ديسمبر")},.d_t_fmt=tsc("%A %e %B %Y %k:%M:%S"),.d_fmt=tsc("%A %e %B %Y"),.t_fmt=tsc("%k:%M:%S"),.t_fmt_ampm=tsc("%k:%M:%S"),.date_fmt=tsc("%A %e %B %Y %Z %k:%M:%S"),.am_pm={tsc(""),tsc("")},.era_d_fmt=tsc(""),.week={7,19971130,1},.first_workday=1},.messages={.yesexpr=tsc("^[+1نyY]"),.noexpr=tsc("^[-0لnN]"),.yesstr=tsc("نعم"),.nostr=tsc("لا")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("966")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("المملكة العربية السعودية"),.country_ab2=tsc("SA"),.country_ab3=tsc("SAU"),.country_num=682,.country_car=tsc("KSA"),.lang_name=tsc("العربية"),.lang_ab=tsc("ar"),.lang_term=tsc("ara"),.lang_lib=tsc("ara")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Arabic locale for Saudi Arabia"),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Arabic"),.territory=tsc(L"Saudi Arabia"),.revision=tsc(L"1.0"),.date=tsc(L"2000-06-29")},.monetary={.int_curr_symbol=tsc(L"SAR "),.currency_symbol=tsc(L"ر.س"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L""),.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L"")},.time={.abday={tsc(L"ح"),tsc(L"ن"),tsc(L"ث"),tsc(L"ر"),tsc(L"خ"),tsc(L"ج"),tsc(L"س")},.day={tsc(L"الأحد"),tsc(L"الإثنين"),tsc(L"الثلاثاء"),tsc(L"الأربعاء"),tsc(L"الخميس"),tsc(L"الجمعـة"),tsc(L"السبت")},.abmon={tsc(L"يناير"),tsc(L"فبراير"),tsc(L"مارس"),tsc(L"أبريل"),tsc(L"مايو"),tsc(L"يونيو"),tsc(L"يوليو"),tsc(L"أغسطس"),tsc(L"سبتمبر"),tsc(L"أكتوبر"),tsc(L"نوفمبر"),tsc(L"ديسمبر")},.mon={tsc(L"يناير"),tsc(L"فبراير"),tsc(L"مارس"),tsc(L"أبريل"),tsc(L"مايو"),tsc(L"يونيو"),tsc(L"يوليو"),tsc(L"أغسطس"),tsc(L"سبتمبر"),tsc(L"أكتوبر"),tsc(L"نوفمبر"),tsc(L"ديسمبر")},.d_t_fmt=tsc(L"%A %e %B %Y %k:%M:%S"),.d_fmt=tsc(L"%A %e %B %Y"),.t_fmt=tsc(L"%k:%M:%S"),.t_fmt_ampm=tsc(L"%k:%M:%S"),.date_fmt=tsc(L"%A %e %B %Y %Z %k:%M:%S"),.am_pm={tsc(L""),tsc(L"")},.era_d_fmt=tsc(L""),.week={7,19971130,1},.first_workday=1},.messages={.yesexpr=tsc(L"^[+1نyY]"),.noexpr=tsc(L"^[-0لnN]"),.yesstr=tsc(L"نعم"),.nostr=tsc(L"لا")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"966")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"المملكة العربية السعودية"),.country_ab2=tsc(L"SA"),.country_ab3=tsc(L"SAU"),.country_num=682,.country_car=tsc(L"KSA"),.lang_name=tsc(L"العربية"),.lang_ab=tsc(L"ar"),.lang_term=tsc(L"ara"),.lang_lib=tsc(L"ara")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Arabic locale for Saudi Arabia"),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Arabic"),.territory=tsc(u8"Saudi Arabia"),.revision=tsc(u8"1.0"),.date=tsc(u8"2000-06-29")},.monetary={.int_curr_symbol=tsc(u8"SAR "),.currency_symbol=tsc(u8"ر.س"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8""),.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8"")},.time={.abday={tsc(u8"ح"),tsc(u8"ن"),tsc(u8"ث"),tsc(u8"ر"),tsc(u8"خ"),tsc(u8"ج"),tsc(u8"س")},.day={tsc(u8"الأحد"),tsc(u8"الإثنين"),tsc(u8"الثلاثاء"),tsc(u8"الأربعاء"),tsc(u8"الخميس"),tsc(u8"الجمعـة"),tsc(u8"السبت")},.abmon={tsc(u8"يناير"),tsc(u8"فبراير"),tsc(u8"مارس"),tsc(u8"أبريل"),tsc(u8"مايو"),tsc(u8"يونيو"),tsc(u8"يوليو"),tsc(u8"أغسطس"),tsc(u8"سبتمبر"),tsc(u8"أكتوبر"),tsc(u8"نوفمبر"),tsc(u8"ديسمبر")},.mon={tsc(u8"يناير"),tsc(u8"فبراير"),tsc(u8"مارس"),tsc(u8"أبريل"),tsc(u8"مايو"),tsc(u8"يونيو"),tsc(u8"يوليو"),tsc(u8"أغسطس"),tsc(u8"سبتمبر"),tsc(u8"أكتوبر"),tsc(u8"نوفمبر"),tsc(u8"ديسمبر")},.d_t_fmt=tsc(u8"%A %e %B %Y %k:%M:%S"),.d_fmt=tsc(u8"%A %e %B %Y"),.t_fmt=tsc(u8"%k:%M:%S"),.t_fmt_ampm=tsc(u8"%k:%M:%S"),.date_fmt=tsc(u8"%A %e %B %Y %Z %k:%M:%S"),.am_pm={tsc(u8""),tsc(u8"")},.era_d_fmt=tsc(u8""),.week={7,19971130,1},.first_workday=1},.messages={.yesexpr=tsc(u8"^[+1نyY]"),.noexpr=tsc(u8"^[-0لnN]"),.yesstr=tsc(u8"نعم"),.nostr=tsc(u8"لا")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"966")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"المملكة العربية السعودية"),.country_ab2=tsc(u8"SA"),.country_ab3=tsc(u8"SAU"),.country_num=682,.country_car=tsc(u8"KSA"),.lang_name=tsc(u8"العربية"),.lang_ab=tsc(u8"ar"),.lang_term=tsc(u8"ara"),.lang_lib=tsc(u8"ara")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Arabic locale for Saudi Arabia"),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Arabic"),.territory=tsc(u"Saudi Arabia"),.revision=tsc(u"1.0"),.date=tsc(u"2000-06-29")},.monetary={.int_curr_symbol=tsc(u"SAR "),.currency_symbol=tsc(u"ر.س"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u""),.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u"")},.time={.abday={tsc(u"ح"),tsc(u"ن"),tsc(u"ث"),tsc(u"ر"),tsc(u"خ"),tsc(u"ج"),tsc(u"س")},.day={tsc(u"الأحد"),tsc(u"الإثنين"),tsc(u"الثلاثاء"),tsc(u"الأربعاء"),tsc(u"الخميس"),tsc(u"الجمعـة"),tsc(u"السبت")},.abmon={tsc(u"يناير"),tsc(u"فبراير"),tsc(u"مارس"),tsc(u"أبريل"),tsc(u"مايو"),tsc(u"يونيو"),tsc(u"يوليو"),tsc(u"أغسطس"),tsc(u"سبتمبر"),tsc(u"أكتوبر"),tsc(u"نوفمبر"),tsc(u"ديسمبر")},.mon={tsc(u"يناير"),tsc(u"فبراير"),tsc(u"مارس"),tsc(u"أبريل"),tsc(u"مايو"),tsc(u"يونيو"),tsc(u"يوليو"),tsc(u"أغسطس"),tsc(u"سبتمبر"),tsc(u"أكتوبر"),tsc(u"نوفمبر"),tsc(u"ديسمبر")},.d_t_fmt=tsc(u"%A %e %B %Y %k:%M:%S"),.d_fmt=tsc(u"%A %e %B %Y"),.t_fmt=tsc(u"%k:%M:%S"),.t_fmt_ampm=tsc(u"%k:%M:%S"),.date_fmt=tsc(u"%A %e %B %Y %Z %k:%M:%S"),.am_pm={tsc(u""),tsc(u"")},.era_d_fmt=tsc(u""),.week={7,19971130,1},.first_workday=1},.messages={.yesexpr=tsc(u"^[+1نyY]"),.noexpr=tsc(u"^[-0لnN]"),.yesstr=tsc(u"نعم"),.nostr=tsc(u"لا")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"966")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"المملكة العربية السعودية"),.country_ab2=tsc(u"SA"),.country_ab3=tsc(u"SAU"),.country_num=682,.country_car=tsc(u"KSA"),.lang_name=tsc(u"العربية"),.lang_ab=tsc(u"ar"),.lang_term=tsc(u"ara"),.lang_lib=tsc(u"ara")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Arabic locale for Saudi Arabia"),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Arabic"),.territory=tsc(U"Saudi Arabia"),.revision=tsc(U"1.0"),.date=tsc(U"2000-06-29")},.monetary={.int_curr_symbol=tsc(U"SAR "),.currency_symbol=tsc(U"ر.س"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U""),.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U"")},.time={.abday={tsc(U"ح"),tsc(U"ن"),tsc(U"ث"),tsc(U"ر"),tsc(U"خ"),tsc(U"ج"),tsc(U"س")},.day={tsc(U"الأحد"),tsc(U"الإثنين"),tsc(U"الثلاثاء"),tsc(U"الأربعاء"),tsc(U"الخميس"),tsc(U"الجمعـة"),tsc(U"السبت")},.abmon={tsc(U"يناير"),tsc(U"فبراير"),tsc(U"مارس"),tsc(U"أبريل"),tsc(U"مايو"),tsc(U"يونيو"),tsc(U"يوليو"),tsc(U"أغسطس"),tsc(U"سبتمبر"),tsc(U"أكتوبر"),tsc(U"نوفمبر"),tsc(U"ديسمبر")},.mon={tsc(U"يناير"),tsc(U"فبراير"),tsc(U"مارس"),tsc(U"أبريل"),tsc(U"مايو"),tsc(U"يونيو"),tsc(U"يوليو"),tsc(U"أغسطس"),tsc(U"سبتمبر"),tsc(U"أكتوبر"),tsc(U"نوفمبر"),tsc(U"ديسمبر")},.d_t_fmt=tsc(U"%A %e %B %Y %k:%M:%S"),.d_fmt=tsc(U"%A %e %B %Y"),.t_fmt=tsc(U"%k:%M:%S"),.t_fmt_ampm=tsc(U"%k:%M:%S"),.date_fmt=tsc(U"%A %e %B %Y %Z %k:%M:%S"),.am_pm={tsc(U""),tsc(U"")},.era_d_fmt=tsc(U""),.week={7,19971130,1},.first_workday=1},.messages={.yesexpr=tsc(U"^[+1نyY]"),.noexpr=tsc(U"^[-0لnN]"),.yesstr=tsc(U"نعم"),.nostr=tsc(U"لا")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"966")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"المملكة العربية السعودية"),.country_ab2=tsc(U"SA"),.country_ab3=tsc(U"SAU"),.country_num=682,.country_car=tsc(U"KSA"),.lang_name=tsc(U"العربية"),.lang_ab=tsc(U"ar"),.lang_term=tsc(U"ara"),.lang_lib=tsc(U"ara")},.measurement={.measurement=1}};


}
}

#include"../main.h"