#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Aymara (ayc) locale for Peru"),.source=tsc("runasimipi.org\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Aymara"),.territory=tsc("Peru"),.revision=tsc("1.1"),.date=tsc("2011-11-13")},.monetary={.int_curr_symbol=tsc("PEN "),.currency_symbol=tsc("S//"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("tum"),tsc("lun"),tsc("mar"),tsc("mir"),tsc("juy"),tsc("wir"),tsc("saw")},.day={tsc("tuminku"),tsc("lunisa"),tsc("martisa"),tsc("mirkulisa"),tsc("juywisa"),tsc("wirnisa"),tsc("sawäru")},.abmon={tsc("ini"),tsc("phi"),tsc("mar"),tsc("awr"),tsc("may"),tsc("jun"),tsc("jul"),tsc("awu"),tsc("sit"),tsc("ukt"),tsc("nuw"),tsc("ris")},.mon={tsc("inïru"),tsc("phiwriru"),tsc("marsu"),tsc("awrila"),tsc("mayu"),tsc("junyu"),tsc("julyu"),tsc("awustu"),tsc("sitimri"),tsc("uktuwri"),tsc("nuwimri"),tsc("risimri")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d//%m//%y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc("%I:%M:%S %p"),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc("VM"),tsc("NM")},.week={7,19971130,1}},.messages={.yesexpr=tsc("^[+1uUsSyY]"),.noexpr=tsc("^[-0jJnN]"),.yesstr=tsc("Ukhamawa"),.nostr=tsc("Janiwa")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("51")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Piruw"),.country_ab2=tsc("PE"),.country_ab3=tsc("PER"),.country_num=604,.country_car=tsc("PE"),.lang_name=tsc("Aymar aru"),.lang_ab=tsc("ay"),.lang_term=tsc("ayc"),.lang_lib=tsc("ayc")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Aymara (ayc) locale for Peru"),.source=tsc(L"runasimipi.org\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Aymara"),.territory=tsc(L"Peru"),.revision=tsc(L"1.1"),.date=tsc(L"2011-11-13")},.monetary={.int_curr_symbol=tsc(L"PEN "),.currency_symbol=tsc(L"S//"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"tum"),tsc(L"lun"),tsc(L"mar"),tsc(L"mir"),tsc(L"juy"),tsc(L"wir"),tsc(L"saw")},.day={tsc(L"tuminku"),tsc(L"lunisa"),tsc(L"martisa"),tsc(L"mirkulisa"),tsc(L"juywisa"),tsc(L"wirnisa"),tsc(L"sawäru")},.abmon={tsc(L"ini"),tsc(L"phi"),tsc(L"mar"),tsc(L"awr"),tsc(L"may"),tsc(L"jun"),tsc(L"jul"),tsc(L"awu"),tsc(L"sit"),tsc(L"ukt"),tsc(L"nuw"),tsc(L"ris")},.mon={tsc(L"inïru"),tsc(L"phiwriru"),tsc(L"marsu"),tsc(L"awrila"),tsc(L"mayu"),tsc(L"junyu"),tsc(L"julyu"),tsc(L"awustu"),tsc(L"sitimri"),tsc(L"uktuwri"),tsc(L"nuwimri"),tsc(L"risimri")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d//%m//%y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L"%I:%M:%S %p"),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L"VM"),tsc(L"NM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(L"^[+1uUsSyY]"),.noexpr=tsc(L"^[-0jJnN]"),.yesstr=tsc(L"Ukhamawa"),.nostr=tsc(L"Janiwa")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"51")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Piruw"),.country_ab2=tsc(L"PE"),.country_ab3=tsc(L"PER"),.country_num=604,.country_car=tsc(L"PE"),.lang_name=tsc(L"Aymar aru"),.lang_ab=tsc(L"ay"),.lang_term=tsc(L"ayc"),.lang_lib=tsc(L"ayc")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Aymara (ayc) locale for Peru"),.source=tsc(u8"runasimipi.org\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Aymara"),.territory=tsc(u8"Peru"),.revision=tsc(u8"1.1"),.date=tsc(u8"2011-11-13")},.monetary={.int_curr_symbol=tsc(u8"PEN "),.currency_symbol=tsc(u8"S//"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"tum"),tsc(u8"lun"),tsc(u8"mar"),tsc(u8"mir"),tsc(u8"juy"),tsc(u8"wir"),tsc(u8"saw")},.day={tsc(u8"tuminku"),tsc(u8"lunisa"),tsc(u8"martisa"),tsc(u8"mirkulisa"),tsc(u8"juywisa"),tsc(u8"wirnisa"),tsc(u8"sawäru")},.abmon={tsc(u8"ini"),tsc(u8"phi"),tsc(u8"mar"),tsc(u8"awr"),tsc(u8"may"),tsc(u8"jun"),tsc(u8"jul"),tsc(u8"awu"),tsc(u8"sit"),tsc(u8"ukt"),tsc(u8"nuw"),tsc(u8"ris")},.mon={tsc(u8"inïru"),tsc(u8"phiwriru"),tsc(u8"marsu"),tsc(u8"awrila"),tsc(u8"mayu"),tsc(u8"junyu"),tsc(u8"julyu"),tsc(u8"awustu"),tsc(u8"sitimri"),tsc(u8"uktuwri"),tsc(u8"nuwimri"),tsc(u8"risimri")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d//%m//%y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p"),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8"VM"),tsc(u8"NM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u8"^[+1uUsSyY]"),.noexpr=tsc(u8"^[-0jJnN]"),.yesstr=tsc(u8"Ukhamawa"),.nostr=tsc(u8"Janiwa")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"51")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Piruw"),.country_ab2=tsc(u8"PE"),.country_ab3=tsc(u8"PER"),.country_num=604,.country_car=tsc(u8"PE"),.lang_name=tsc(u8"Aymar aru"),.lang_ab=tsc(u8"ay"),.lang_term=tsc(u8"ayc"),.lang_lib=tsc(u8"ayc")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Aymara (ayc) locale for Peru"),.source=tsc(u"runasimipi.org\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Aymara"),.territory=tsc(u"Peru"),.revision=tsc(u"1.1"),.date=tsc(u"2011-11-13")},.monetary={.int_curr_symbol=tsc(u"PEN "),.currency_symbol=tsc(u"S//"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"tum"),tsc(u"lun"),tsc(u"mar"),tsc(u"mir"),tsc(u"juy"),tsc(u"wir"),tsc(u"saw")},.day={tsc(u"tuminku"),tsc(u"lunisa"),tsc(u"martisa"),tsc(u"mirkulisa"),tsc(u"juywisa"),tsc(u"wirnisa"),tsc(u"sawäru")},.abmon={tsc(u"ini"),tsc(u"phi"),tsc(u"mar"),tsc(u"awr"),tsc(u"may"),tsc(u"jun"),tsc(u"jul"),tsc(u"awu"),tsc(u"sit"),tsc(u"ukt"),tsc(u"nuw"),tsc(u"ris")},.mon={tsc(u"inïru"),tsc(u"phiwriru"),tsc(u"marsu"),tsc(u"awrila"),tsc(u"mayu"),tsc(u"junyu"),tsc(u"julyu"),tsc(u"awustu"),tsc(u"sitimri"),tsc(u"uktuwri"),tsc(u"nuwimri"),tsc(u"risimri")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d//%m//%y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u"%I:%M:%S %p"),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u"VM"),tsc(u"NM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u"^[+1uUsSyY]"),.noexpr=tsc(u"^[-0jJnN]"),.yesstr=tsc(u"Ukhamawa"),.nostr=tsc(u"Janiwa")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"51")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Piruw"),.country_ab2=tsc(u"PE"),.country_ab3=tsc(u"PER"),.country_num=604,.country_car=tsc(u"PE"),.lang_name=tsc(u"Aymar aru"),.lang_ab=tsc(u"ay"),.lang_term=tsc(u"ayc"),.lang_lib=tsc(u"ayc")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Aymara (ayc) locale for Peru"),.source=tsc(U"runasimipi.org\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Aymara"),.territory=tsc(U"Peru"),.revision=tsc(U"1.1"),.date=tsc(U"2011-11-13")},.monetary={.int_curr_symbol=tsc(U"PEN "),.currency_symbol=tsc(U"S//"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"tum"),tsc(U"lun"),tsc(U"mar"),tsc(U"mir"),tsc(U"juy"),tsc(U"wir"),tsc(U"saw")},.day={tsc(U"tuminku"),tsc(U"lunisa"),tsc(U"martisa"),tsc(U"mirkulisa"),tsc(U"juywisa"),tsc(U"wirnisa"),tsc(U"sawäru")},.abmon={tsc(U"ini"),tsc(U"phi"),tsc(U"mar"),tsc(U"awr"),tsc(U"may"),tsc(U"jun"),tsc(U"jul"),tsc(U"awu"),tsc(U"sit"),tsc(U"ukt"),tsc(U"nuw"),tsc(U"ris")},.mon={tsc(U"inïru"),tsc(U"phiwriru"),tsc(U"marsu"),tsc(U"awrila"),tsc(U"mayu"),tsc(U"junyu"),tsc(U"julyu"),tsc(U"awustu"),tsc(U"sitimri"),tsc(U"uktuwri"),tsc(U"nuwimri"),tsc(U"risimri")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d//%m//%y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U"%I:%M:%S %p"),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U"VM"),tsc(U"NM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(U"^[+1uUsSyY]"),.noexpr=tsc(U"^[-0jJnN]"),.yesstr=tsc(U"Ukhamawa"),.nostr=tsc(U"Janiwa")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"51")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Piruw"),.country_ab2=tsc(U"PE"),.country_ab3=tsc(U"PER"),.country_num=604,.country_car=tsc(U"PE"),.lang_name=tsc(U"Aymar aru"),.lang_ab=tsc(U"ay"),.lang_term=tsc(U"ayc"),.lang_lib=tsc(U"ayc")},.measurement={.measurement=1}};


}
}

#include"../main.h"