#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Azeri language locale for Azerbaijan (latin)"),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc("pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Azerbaijani"),.territory=tsc("Azerbaijan"),.revision=tsc("0.4"),.date=tsc("2001-01-26")},.monetary={.int_curr_symbol=tsc("AZN "),.currency_symbol=tsc("₼"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("baz"),tsc("ber"),tsc("çax"),tsc("çər"),tsc("cax"),tsc("cüm"),tsc("şnb")},.day={tsc("bazar günü"),tsc("bazar ertəsi"),tsc("çərşənbə axşamı"),tsc("çərşənbə"),tsc("cümə axşamı"),tsc("cümə"),tsc("şənbə")},.abmon={tsc("Yan"),tsc("Fev"),tsc("Mar"),tsc("Apr"),tsc("May"),tsc("İyn"),tsc("İyl"),tsc("Avq"),tsc("Sen"),tsc("Okt"),tsc("Noy"),tsc("Dek")},.mon={tsc("yanvar"),tsc("fevral"),tsc("mart"),tsc("aprel"),tsc("may"),tsc("iyun"),tsc("iyul"),tsc("avqust"),tsc("sentyabr"),tsc("oktyabr"),tsc("noyabr"),tsc("dekabr")},.d_t_fmt=tsc("%A, %d %B %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%A, %d %B %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1bBhH]"),.noexpr=tsc("^[-0YyNn]"),.yesstr=tsc("hə"),.nostr=tsc("yox")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("994")},.name={.name_fmt=tsc("???")},.address={.postal_fmt=tsc("???"),.country_name=tsc("Azərbaycan"),.country_ab2=tsc("AZ"),.country_ab3=tsc("AZE"),.country_num=31,.country_car=tsc("AZ"),.lang_name=tsc("azərbaycan"),.lang_ab=tsc("az"),.lang_term=tsc("aze"),.lang_lib=tsc("aze")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Azeri language locale for Azerbaijan (latin)"),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(L"pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Azerbaijani"),.territory=tsc(L"Azerbaijan"),.revision=tsc(L"0.4"),.date=tsc(L"2001-01-26")},.monetary={.int_curr_symbol=tsc(L"AZN "),.currency_symbol=tsc(L"₼"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"baz"),tsc(L"ber"),tsc(L"çax"),tsc(L"çər"),tsc(L"cax"),tsc(L"cüm"),tsc(L"şnb")},.day={tsc(L"bazar günü"),tsc(L"bazar ertəsi"),tsc(L"çərşənbə axşamı"),tsc(L"çərşənbə"),tsc(L"cümə axşamı"),tsc(L"cümə"),tsc(L"şənbə")},.abmon={tsc(L"Yan"),tsc(L"Fev"),tsc(L"Mar"),tsc(L"Apr"),tsc(L"May"),tsc(L"İyn"),tsc(L"İyl"),tsc(L"Avq"),tsc(L"Sen"),tsc(L"Okt"),tsc(L"Noy"),tsc(L"Dek")},.mon={tsc(L"yanvar"),tsc(L"fevral"),tsc(L"mart"),tsc(L"aprel"),tsc(L"may"),tsc(L"iyun"),tsc(L"iyul"),tsc(L"avqust"),tsc(L"sentyabr"),tsc(L"oktyabr"),tsc(L"noyabr"),tsc(L"dekabr")},.d_t_fmt=tsc(L"%A, %d %B %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%A, %d %B %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1bBhH]"),.noexpr=tsc(L"^[-0YyNn]"),.yesstr=tsc(L"hə"),.nostr=tsc(L"yox")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"994")},.name={.name_fmt=tsc(L"???")},.address={.postal_fmt=tsc(L"???"),.country_name=tsc(L"Azərbaycan"),.country_ab2=tsc(L"AZ"),.country_ab3=tsc(L"AZE"),.country_num=31,.country_car=tsc(L"AZ"),.lang_name=tsc(L"azərbaycan"),.lang_ab=tsc(L"az"),.lang_term=tsc(L"aze"),.lang_lib=tsc(L"aze")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Azeri language locale for Azerbaijan (latin)"),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(u8"pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Azerbaijani"),.territory=tsc(u8"Azerbaijan"),.revision=tsc(u8"0.4"),.date=tsc(u8"2001-01-26")},.monetary={.int_curr_symbol=tsc(u8"AZN "),.currency_symbol=tsc(u8"₼"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"baz"),tsc(u8"ber"),tsc(u8"çax"),tsc(u8"çər"),tsc(u8"cax"),tsc(u8"cüm"),tsc(u8"şnb")},.day={tsc(u8"bazar günü"),tsc(u8"bazar ertəsi"),tsc(u8"çərşənbə axşamı"),tsc(u8"çərşənbə"),tsc(u8"cümə axşamı"),tsc(u8"cümə"),tsc(u8"şənbə")},.abmon={tsc(u8"Yan"),tsc(u8"Fev"),tsc(u8"Mar"),tsc(u8"Apr"),tsc(u8"May"),tsc(u8"İyn"),tsc(u8"İyl"),tsc(u8"Avq"),tsc(u8"Sen"),tsc(u8"Okt"),tsc(u8"Noy"),tsc(u8"Dek")},.mon={tsc(u8"yanvar"),tsc(u8"fevral"),tsc(u8"mart"),tsc(u8"aprel"),tsc(u8"may"),tsc(u8"iyun"),tsc(u8"iyul"),tsc(u8"avqust"),tsc(u8"sentyabr"),tsc(u8"oktyabr"),tsc(u8"noyabr"),tsc(u8"dekabr")},.d_t_fmt=tsc(u8"%A, %d %B %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%A, %d %B %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1bBhH]"),.noexpr=tsc(u8"^[-0YyNn]"),.yesstr=tsc(u8"hə"),.nostr=tsc(u8"yox")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"994")},.name={.name_fmt=tsc(u8"???")},.address={.postal_fmt=tsc(u8"???"),.country_name=tsc(u8"Azərbaycan"),.country_ab2=tsc(u8"AZ"),.country_ab3=tsc(u8"AZE"),.country_num=31,.country_car=tsc(u8"AZ"),.lang_name=tsc(u8"azərbaycan"),.lang_ab=tsc(u8"az"),.lang_term=tsc(u8"aze"),.lang_lib=tsc(u8"aze")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Azeri language locale for Azerbaijan (latin)"),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(u"pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Azerbaijani"),.territory=tsc(u"Azerbaijan"),.revision=tsc(u"0.4"),.date=tsc(u"2001-01-26")},.monetary={.int_curr_symbol=tsc(u"AZN "),.currency_symbol=tsc(u"₼"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"baz"),tsc(u"ber"),tsc(u"çax"),tsc(u"çər"),tsc(u"cax"),tsc(u"cüm"),tsc(u"şnb")},.day={tsc(u"bazar günü"),tsc(u"bazar ertəsi"),tsc(u"çərşənbə axşamı"),tsc(u"çərşənbə"),tsc(u"cümə axşamı"),tsc(u"cümə"),tsc(u"şənbə")},.abmon={tsc(u"Yan"),tsc(u"Fev"),tsc(u"Mar"),tsc(u"Apr"),tsc(u"May"),tsc(u"İyn"),tsc(u"İyl"),tsc(u"Avq"),tsc(u"Sen"),tsc(u"Okt"),tsc(u"Noy"),tsc(u"Dek")},.mon={tsc(u"yanvar"),tsc(u"fevral"),tsc(u"mart"),tsc(u"aprel"),tsc(u"may"),tsc(u"iyun"),tsc(u"iyul"),tsc(u"avqust"),tsc(u"sentyabr"),tsc(u"oktyabr"),tsc(u"noyabr"),tsc(u"dekabr")},.d_t_fmt=tsc(u"%A, %d %B %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%A, %d %B %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1bBhH]"),.noexpr=tsc(u"^[-0YyNn]"),.yesstr=tsc(u"hə"),.nostr=tsc(u"yox")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"994")},.name={.name_fmt=tsc(u"???")},.address={.postal_fmt=tsc(u"???"),.country_name=tsc(u"Azərbaycan"),.country_ab2=tsc(u"AZ"),.country_ab3=tsc(u"AZE"),.country_num=31,.country_car=tsc(u"AZ"),.lang_name=tsc(u"azərbaycan"),.lang_ab=tsc(u"az"),.lang_term=tsc(u"aze"),.lang_lib=tsc(u"aze")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Azeri language locale for Azerbaijan (latin)"),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(U"pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Azerbaijani"),.territory=tsc(U"Azerbaijan"),.revision=tsc(U"0.4"),.date=tsc(U"2001-01-26")},.monetary={.int_curr_symbol=tsc(U"AZN "),.currency_symbol=tsc(U"₼"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"baz"),tsc(U"ber"),tsc(U"çax"),tsc(U"çər"),tsc(U"cax"),tsc(U"cüm"),tsc(U"şnb")},.day={tsc(U"bazar günü"),tsc(U"bazar ertəsi"),tsc(U"çərşənbə axşamı"),tsc(U"çərşənbə"),tsc(U"cümə axşamı"),tsc(U"cümə"),tsc(U"şənbə")},.abmon={tsc(U"Yan"),tsc(U"Fev"),tsc(U"Mar"),tsc(U"Apr"),tsc(U"May"),tsc(U"İyn"),tsc(U"İyl"),tsc(U"Avq"),tsc(U"Sen"),tsc(U"Okt"),tsc(U"Noy"),tsc(U"Dek")},.mon={tsc(U"yanvar"),tsc(U"fevral"),tsc(U"mart"),tsc(U"aprel"),tsc(U"may"),tsc(U"iyun"),tsc(U"iyul"),tsc(U"avqust"),tsc(U"sentyabr"),tsc(U"oktyabr"),tsc(U"noyabr"),tsc(U"dekabr")},.d_t_fmt=tsc(U"%A, %d %B %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%A, %d %B %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1bBhH]"),.noexpr=tsc(U"^[-0YyNn]"),.yesstr=tsc(U"hə"),.nostr=tsc(U"yox")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"994")},.name={.name_fmt=tsc(U"???")},.address={.postal_fmt=tsc(U"???"),.country_name=tsc(U"Azərbaycan"),.country_ab2=tsc(U"AZ"),.country_ab3=tsc(U"AZE"),.country_num=31,.country_car=tsc(U"AZ"),.lang_name=tsc(U"azərbaycan"),.lang_ab=tsc(U"az"),.lang_term=tsc(U"aze"),.lang_lib=tsc(U"aze")},.measurement={.measurement=1}};


}
}

#include"../main.h"