#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Belarusian Latin-Script locale for Belarus"),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Belarusian"),.territory=tsc("Belarus"),.revision=tsc("1.0"),.date=tsc("2005-09-15")},.monetary={.int_curr_symbol=tsc("BYR "),.currency_symbol=tsc("Rub"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("Nia"),tsc("Pan"),tsc("Aŭt"),tsc("Sie"),tsc("Čać"),tsc("Pia"),tsc("Sub")},.day={tsc("Niadziela"),tsc("Paniadziełak"),tsc("Aŭtorak"),tsc("Sierada"),tsc("Čaćvier"),tsc("Piatnica"),tsc("Subota")},.abmon={tsc("Stu"),tsc("Lut"),tsc("Sak"),tsc("Kra"),tsc("Maj"),tsc("Čer"),tsc("Lip"),tsc("Žni"),tsc("Vie"),tsc("Kas"),tsc("Lis"),tsc("Śni")},.mon={tsc("studzienia"),tsc("lutaha"),tsc("sakavika"),tsc("krasavika"),tsc("maja"),tsc("červienia"),tsc("lipienia"),tsc("žniŭnia"),tsc("vieraśnia"),tsc("kastryčnika"),tsc("listapada"),tsc("śniežnia")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1TtYy]"),.noexpr=tsc("^[-0Nn]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("8~10"),.int_prefix=tsc("375")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Biełaruś"),.country_ab2=tsc("BY"),.country_ab3=tsc("BLR"),.country_num=112,.country_car=tsc("BY"),.lang_name=tsc("biełaruskaja"),.lang_ab=tsc("be"),.lang_term=tsc("bel"),.lang_lib=tsc("bel")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Belarusian Latin-Script locale for Belarus"),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Belarusian"),.territory=tsc(L"Belarus"),.revision=tsc(L"1.0"),.date=tsc(L"2005-09-15")},.monetary={.int_curr_symbol=tsc(L"BYR "),.currency_symbol=tsc(L"Rub"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"Nia"),tsc(L"Pan"),tsc(L"Aŭt"),tsc(L"Sie"),tsc(L"Čać"),tsc(L"Pia"),tsc(L"Sub")},.day={tsc(L"Niadziela"),tsc(L"Paniadziełak"),tsc(L"Aŭtorak"),tsc(L"Sierada"),tsc(L"Čaćvier"),tsc(L"Piatnica"),tsc(L"Subota")},.abmon={tsc(L"Stu"),tsc(L"Lut"),tsc(L"Sak"),tsc(L"Kra"),tsc(L"Maj"),tsc(L"Čer"),tsc(L"Lip"),tsc(L"Žni"),tsc(L"Vie"),tsc(L"Kas"),tsc(L"Lis"),tsc(L"Śni")},.mon={tsc(L"studzienia"),tsc(L"lutaha"),tsc(L"sakavika"),tsc(L"krasavika"),tsc(L"maja"),tsc(L"červienia"),tsc(L"lipienia"),tsc(L"žniŭnia"),tsc(L"vieraśnia"),tsc(L"kastryčnika"),tsc(L"listapada"),tsc(L"śniežnia")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1TtYy]"),.noexpr=tsc(L"^[-0Nn]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"8~10"),.int_prefix=tsc(L"375")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Biełaruś"),.country_ab2=tsc(L"BY"),.country_ab3=tsc(L"BLR"),.country_num=112,.country_car=tsc(L"BY"),.lang_name=tsc(L"biełaruskaja"),.lang_ab=tsc(L"be"),.lang_term=tsc(L"bel"),.lang_lib=tsc(L"bel")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Belarusian Latin-Script locale for Belarus"),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Belarusian"),.territory=tsc(u8"Belarus"),.revision=tsc(u8"1.0"),.date=tsc(u8"2005-09-15")},.monetary={.int_curr_symbol=tsc(u8"BYR "),.currency_symbol=tsc(u8"Rub"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"Nia"),tsc(u8"Pan"),tsc(u8"Aŭt"),tsc(u8"Sie"),tsc(u8"Čać"),tsc(u8"Pia"),tsc(u8"Sub")},.day={tsc(u8"Niadziela"),tsc(u8"Paniadziełak"),tsc(u8"Aŭtorak"),tsc(u8"Sierada"),tsc(u8"Čaćvier"),tsc(u8"Piatnica"),tsc(u8"Subota")},.abmon={tsc(u8"Stu"),tsc(u8"Lut"),tsc(u8"Sak"),tsc(u8"Kra"),tsc(u8"Maj"),tsc(u8"Čer"),tsc(u8"Lip"),tsc(u8"Žni"),tsc(u8"Vie"),tsc(u8"Kas"),tsc(u8"Lis"),tsc(u8"Śni")},.mon={tsc(u8"studzienia"),tsc(u8"lutaha"),tsc(u8"sakavika"),tsc(u8"krasavika"),tsc(u8"maja"),tsc(u8"červienia"),tsc(u8"lipienia"),tsc(u8"žniŭnia"),tsc(u8"vieraśnia"),tsc(u8"kastryčnika"),tsc(u8"listapada"),tsc(u8"śniežnia")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1TtYy]"),.noexpr=tsc(u8"^[-0Nn]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"8~10"),.int_prefix=tsc(u8"375")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Biełaruś"),.country_ab2=tsc(u8"BY"),.country_ab3=tsc(u8"BLR"),.country_num=112,.country_car=tsc(u8"BY"),.lang_name=tsc(u8"biełaruskaja"),.lang_ab=tsc(u8"be"),.lang_term=tsc(u8"bel"),.lang_lib=tsc(u8"bel")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Belarusian Latin-Script locale for Belarus"),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Belarusian"),.territory=tsc(u"Belarus"),.revision=tsc(u"1.0"),.date=tsc(u"2005-09-15")},.monetary={.int_curr_symbol=tsc(u"BYR "),.currency_symbol=tsc(u"Rub"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"Nia"),tsc(u"Pan"),tsc(u"Aŭt"),tsc(u"Sie"),tsc(u"Čać"),tsc(u"Pia"),tsc(u"Sub")},.day={tsc(u"Niadziela"),tsc(u"Paniadziełak"),tsc(u"Aŭtorak"),tsc(u"Sierada"),tsc(u"Čaćvier"),tsc(u"Piatnica"),tsc(u"Subota")},.abmon={tsc(u"Stu"),tsc(u"Lut"),tsc(u"Sak"),tsc(u"Kra"),tsc(u"Maj"),tsc(u"Čer"),tsc(u"Lip"),tsc(u"Žni"),tsc(u"Vie"),tsc(u"Kas"),tsc(u"Lis"),tsc(u"Śni")},.mon={tsc(u"studzienia"),tsc(u"lutaha"),tsc(u"sakavika"),tsc(u"krasavika"),tsc(u"maja"),tsc(u"červienia"),tsc(u"lipienia"),tsc(u"žniŭnia"),tsc(u"vieraśnia"),tsc(u"kastryčnika"),tsc(u"listapada"),tsc(u"śniežnia")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1TtYy]"),.noexpr=tsc(u"^[-0Nn]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"8~10"),.int_prefix=tsc(u"375")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Biełaruś"),.country_ab2=tsc(u"BY"),.country_ab3=tsc(u"BLR"),.country_num=112,.country_car=tsc(u"BY"),.lang_name=tsc(u"biełaruskaja"),.lang_ab=tsc(u"be"),.lang_term=tsc(u"bel"),.lang_lib=tsc(u"bel")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Belarusian Latin-Script locale for Belarus"),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Belarusian"),.territory=tsc(U"Belarus"),.revision=tsc(U"1.0"),.date=tsc(U"2005-09-15")},.monetary={.int_curr_symbol=tsc(U"BYR "),.currency_symbol=tsc(U"Rub"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"Nia"),tsc(U"Pan"),tsc(U"Aŭt"),tsc(U"Sie"),tsc(U"Čać"),tsc(U"Pia"),tsc(U"Sub")},.day={tsc(U"Niadziela"),tsc(U"Paniadziełak"),tsc(U"Aŭtorak"),tsc(U"Sierada"),tsc(U"Čaćvier"),tsc(U"Piatnica"),tsc(U"Subota")},.abmon={tsc(U"Stu"),tsc(U"Lut"),tsc(U"Sak"),tsc(U"Kra"),tsc(U"Maj"),tsc(U"Čer"),tsc(U"Lip"),tsc(U"Žni"),tsc(U"Vie"),tsc(U"Kas"),tsc(U"Lis"),tsc(U"Śni")},.mon={tsc(U"studzienia"),tsc(U"lutaha"),tsc(U"sakavika"),tsc(U"krasavika"),tsc(U"maja"),tsc(U"červienia"),tsc(U"lipienia"),tsc(U"žniŭnia"),tsc(U"vieraśnia"),tsc(U"kastryčnika"),tsc(U"listapada"),tsc(U"śniežnia")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1TtYy]"),.noexpr=tsc(U"^[-0Nn]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"8~10"),.int_prefix=tsc(U"375")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Biełaruś"),.country_ab2=tsc(U"BY"),.country_ab3=tsc(U"BLR"),.country_num=112,.country_car=tsc(U"BY"),.lang_name=tsc(U"biełaruskaja"),.lang_ab=tsc(U"be"),.lang_term=tsc(U"bel"),.lang_lib=tsc(U"bel")},.measurement={.measurement=1}};


}
}

#include"../main.h"