#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Bislama language locale for Vanuatu"),.source=tsc("Samsung Electronics Co., Ltd.\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("akhilesh.k@samsung.com & maninder1.s@samsung.com;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Bislama"),.territory=tsc("Vanuatu"),.revision=tsc("0.1"),.date=tsc("2017-07-13")},.monetary={.int_curr_symbol=tsc("VUV "),.currency_symbol=tsc("VT"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.int_p_sep_by_space=1,.int_n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("San"),tsc("Man"),tsc("Tus"),tsc("Wen"),tsc("Tas"),tsc("Fra"),tsc("Sar")},.day={tsc("Sande"),tsc("Mande"),tsc("Tusde"),tsc("Wenesde"),tsc("Tosde"),tsc("Fraede"),tsc("Sarere")},.abmon={tsc("Jan"),tsc("Feb"),tsc("Maj"),tsc("Epr"),tsc("Mei"),tsc("Jun"),tsc("Jul"),tsc("Ogs"),tsc("Sep"),tsc("Okt"),tsc("Nov"),tsc("Dis")},.mon={tsc("Jenuware"),tsc("Febwari"),tsc("Maj"),tsc("Epril"),tsc("Mei"),tsc("Jun"),tsc("Julae"),tsc("Ogis"),tsc("Septemba"),tsc("Oktoba"),tsc("Novemba"),tsc("Disemba")},.d_t_fmt=tsc("%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc("%A %d %b %Y"),.t_fmt=tsc("%I:%M:%S %p %Z"),.t_fmt_ampm=tsc("%I:%M:%S %p %Z"),.date_fmt=tsc("%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc("AM"),tsc("PM")}},.messages={.yesexpr=tsc("^[+1yY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("Yes"),.nostr=tsc("No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %l"),.int_select=tsc("00"),.int_prefix=tsc("678")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f"),.name_miss=tsc("Miss."),.name_mr=tsc("Mr."),.name_mrs=tsc("Mrs."),.name_ms=tsc("Ms.")},.address={.postal_fmt=tsc("%a%b%s%c"),.country_name=tsc("Vanuatu"),.country_ab2=tsc("VU"),.country_ab3=tsc("VUT"),.country_num=548,.country_car=tsc("VU"),.lang_name=tsc("Bislama"),.lang_ab=tsc("bi"),.lang_term=tsc("bis"),.lang_lib=tsc("bis")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Bislama language locale for Vanuatu"),.source=tsc(L"Samsung Electronics Co., Ltd.\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"akhilesh.k@samsung.com & maninder1.s@samsung.com;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Bislama"),.territory=tsc(L"Vanuatu"),.revision=tsc(L"0.1"),.date=tsc(L"2017-07-13")},.monetary={.int_curr_symbol=tsc(L"VUV "),.currency_symbol=tsc(L"VT"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.int_p_sep_by_space=1,.int_n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"San"),tsc(L"Man"),tsc(L"Tus"),tsc(L"Wen"),tsc(L"Tas"),tsc(L"Fra"),tsc(L"Sar")},.day={tsc(L"Sande"),tsc(L"Mande"),tsc(L"Tusde"),tsc(L"Wenesde"),tsc(L"Tosde"),tsc(L"Fraede"),tsc(L"Sarere")},.abmon={tsc(L"Jan"),tsc(L"Feb"),tsc(L"Maj"),tsc(L"Epr"),tsc(L"Mei"),tsc(L"Jun"),tsc(L"Jul"),tsc(L"Ogs"),tsc(L"Sep"),tsc(L"Okt"),tsc(L"Nov"),tsc(L"Dis")},.mon={tsc(L"Jenuware"),tsc(L"Febwari"),tsc(L"Maj"),tsc(L"Epril"),tsc(L"Mei"),tsc(L"Jun"),tsc(L"Julae"),tsc(L"Ogis"),tsc(L"Septemba"),tsc(L"Oktoba"),tsc(L"Novemba"),tsc(L"Disemba")},.d_t_fmt=tsc(L"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(L"%A %d %b %Y"),.t_fmt=tsc(L"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(L"%I:%M:%S %p %Z"),.date_fmt=tsc(L"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(L"AM"),tsc(L"PM")}},.messages={.yesexpr=tsc(L"^[+1yY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"Yes"),.nostr=tsc(L"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"678")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f"),.name_miss=tsc(L"Miss."),.name_mr=tsc(L"Mr."),.name_mrs=tsc(L"Mrs."),.name_ms=tsc(L"Ms.")},.address={.postal_fmt=tsc(L"%a%b%s%c"),.country_name=tsc(L"Vanuatu"),.country_ab2=tsc(L"VU"),.country_ab3=tsc(L"VUT"),.country_num=548,.country_car=tsc(L"VU"),.lang_name=tsc(L"Bislama"),.lang_ab=tsc(L"bi"),.lang_term=tsc(L"bis"),.lang_lib=tsc(L"bis")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Bislama language locale for Vanuatu"),.source=tsc(u8"Samsung Electronics Co., Ltd.\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"akhilesh.k@samsung.com & maninder1.s@samsung.com;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Bislama"),.territory=tsc(u8"Vanuatu"),.revision=tsc(u8"0.1"),.date=tsc(u8"2017-07-13")},.monetary={.int_curr_symbol=tsc(u8"VUV "),.currency_symbol=tsc(u8"VT"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.int_p_sep_by_space=1,.int_n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"San"),tsc(u8"Man"),tsc(u8"Tus"),tsc(u8"Wen"),tsc(u8"Tas"),tsc(u8"Fra"),tsc(u8"Sar")},.day={tsc(u8"Sande"),tsc(u8"Mande"),tsc(u8"Tusde"),tsc(u8"Wenesde"),tsc(u8"Tosde"),tsc(u8"Fraede"),tsc(u8"Sarere")},.abmon={tsc(u8"Jan"),tsc(u8"Feb"),tsc(u8"Maj"),tsc(u8"Epr"),tsc(u8"Mei"),tsc(u8"Jun"),tsc(u8"Jul"),tsc(u8"Ogs"),tsc(u8"Sep"),tsc(u8"Okt"),tsc(u8"Nov"),tsc(u8"Dis")},.mon={tsc(u8"Jenuware"),tsc(u8"Febwari"),tsc(u8"Maj"),tsc(u8"Epril"),tsc(u8"Mei"),tsc(u8"Jun"),tsc(u8"Julae"),tsc(u8"Ogis"),tsc(u8"Septemba"),tsc(u8"Oktoba"),tsc(u8"Novemba"),tsc(u8"Disemba")},.d_t_fmt=tsc(u8"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(u8"%A %d %b %Y"),.t_fmt=tsc(u8"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p %Z"),.date_fmt=tsc(u8"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(u8"AM"),tsc(u8"PM")}},.messages={.yesexpr=tsc(u8"^[+1yY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"Yes"),.nostr=tsc(u8"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"678")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f"),.name_miss=tsc(u8"Miss."),.name_mr=tsc(u8"Mr."),.name_mrs=tsc(u8"Mrs."),.name_ms=tsc(u8"Ms.")},.address={.postal_fmt=tsc(u8"%a%b%s%c"),.country_name=tsc(u8"Vanuatu"),.country_ab2=tsc(u8"VU"),.country_ab3=tsc(u8"VUT"),.country_num=548,.country_car=tsc(u8"VU"),.lang_name=tsc(u8"Bislama"),.lang_ab=tsc(u8"bi"),.lang_term=tsc(u8"bis"),.lang_lib=tsc(u8"bis")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Bislama language locale for Vanuatu"),.source=tsc(u"Samsung Electronics Co., Ltd.\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"akhilesh.k@samsung.com & maninder1.s@samsung.com;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Bislama"),.territory=tsc(u"Vanuatu"),.revision=tsc(u"0.1"),.date=tsc(u"2017-07-13")},.monetary={.int_curr_symbol=tsc(u"VUV "),.currency_symbol=tsc(u"VT"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.int_p_sep_by_space=1,.int_n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"San"),tsc(u"Man"),tsc(u"Tus"),tsc(u"Wen"),tsc(u"Tas"),tsc(u"Fra"),tsc(u"Sar")},.day={tsc(u"Sande"),tsc(u"Mande"),tsc(u"Tusde"),tsc(u"Wenesde"),tsc(u"Tosde"),tsc(u"Fraede"),tsc(u"Sarere")},.abmon={tsc(u"Jan"),tsc(u"Feb"),tsc(u"Maj"),tsc(u"Epr"),tsc(u"Mei"),tsc(u"Jun"),tsc(u"Jul"),tsc(u"Ogs"),tsc(u"Sep"),tsc(u"Okt"),tsc(u"Nov"),tsc(u"Dis")},.mon={tsc(u"Jenuware"),tsc(u"Febwari"),tsc(u"Maj"),tsc(u"Epril"),tsc(u"Mei"),tsc(u"Jun"),tsc(u"Julae"),tsc(u"Ogis"),tsc(u"Septemba"),tsc(u"Oktoba"),tsc(u"Novemba"),tsc(u"Disemba")},.d_t_fmt=tsc(u"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(u"%A %d %b %Y"),.t_fmt=tsc(u"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(u"%I:%M:%S %p %Z"),.date_fmt=tsc(u"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(u"AM"),tsc(u"PM")}},.messages={.yesexpr=tsc(u"^[+1yY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"Yes"),.nostr=tsc(u"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"678")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f"),.name_miss=tsc(u"Miss."),.name_mr=tsc(u"Mr."),.name_mrs=tsc(u"Mrs."),.name_ms=tsc(u"Ms.")},.address={.postal_fmt=tsc(u"%a%b%s%c"),.country_name=tsc(u"Vanuatu"),.country_ab2=tsc(u"VU"),.country_ab3=tsc(u"VUT"),.country_num=548,.country_car=tsc(u"VU"),.lang_name=tsc(u"Bislama"),.lang_ab=tsc(u"bi"),.lang_term=tsc(u"bis"),.lang_lib=tsc(u"bis")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Bislama language locale for Vanuatu"),.source=tsc(U"Samsung Electronics Co., Ltd.\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"akhilesh.k@samsung.com & maninder1.s@samsung.com;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Bislama"),.territory=tsc(U"Vanuatu"),.revision=tsc(U"0.1"),.date=tsc(U"2017-07-13")},.monetary={.int_curr_symbol=tsc(U"VUV "),.currency_symbol=tsc(U"VT"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.int_p_sep_by_space=1,.int_n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"San"),tsc(U"Man"),tsc(U"Tus"),tsc(U"Wen"),tsc(U"Tas"),tsc(U"Fra"),tsc(U"Sar")},.day={tsc(U"Sande"),tsc(U"Mande"),tsc(U"Tusde"),tsc(U"Wenesde"),tsc(U"Tosde"),tsc(U"Fraede"),tsc(U"Sarere")},.abmon={tsc(U"Jan"),tsc(U"Feb"),tsc(U"Maj"),tsc(U"Epr"),tsc(U"Mei"),tsc(U"Jun"),tsc(U"Jul"),tsc(U"Ogs"),tsc(U"Sep"),tsc(U"Okt"),tsc(U"Nov"),tsc(U"Dis")},.mon={tsc(U"Jenuware"),tsc(U"Febwari"),tsc(U"Maj"),tsc(U"Epril"),tsc(U"Mei"),tsc(U"Jun"),tsc(U"Julae"),tsc(U"Ogis"),tsc(U"Septemba"),tsc(U"Oktoba"),tsc(U"Novemba"),tsc(U"Disemba")},.d_t_fmt=tsc(U"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(U"%A %d %b %Y"),.t_fmt=tsc(U"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(U"%I:%M:%S %p %Z"),.date_fmt=tsc(U"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(U"AM"),tsc(U"PM")}},.messages={.yesexpr=tsc(U"^[+1yY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"Yes"),.nostr=tsc(U"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"678")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f"),.name_miss=tsc(U"Miss."),.name_mr=tsc(U"Mr."),.name_mrs=tsc(U"Mrs."),.name_ms=tsc(U"Ms.")},.address={.postal_fmt=tsc(U"%a%b%s%c"),.country_name=tsc(U"Vanuatu"),.country_ab2=tsc(U"VU"),.country_ab3=tsc(U"VUT"),.country_num=548,.country_car=tsc(U"VU"),.lang_name=tsc(U"Bislama"),.lang_ab=tsc(U"bi"),.lang_term=tsc(U"bis"),.lang_lib=tsc(U"bis")},.measurement={.measurement=1}};


}
}

#include"../main.h"