#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t monetary_mon_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Bosnian language locale for Bosnia and Herzegowina"),.source=tsc("adapted from Croatian locale\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Tomislav Vujec\t\t;\t\tfast_io"),.email=tsc("tvujec@carnet.hr;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Bosnian"),.territory=tsc("Bosnia & Herzegovina"),.revision=tsc("0.4"),.date=tsc("2004-01-09")},.monetary={.int_curr_symbol=tsc("BAM "),.currency_symbol=tsc("KM"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("")},.time={.abday={tsc("Ned"),tsc("Pon"),tsc("Uto"),tsc("Sri"),tsc("Čet"),tsc("Pet"),tsc("Sub")},.day={tsc("Nedjelja"),tsc("Ponedjeljak"),tsc("Utorak"),tsc("Srijeda"),tsc("Četvrtak"),tsc("Petak"),tsc("Subota")},.abmon={tsc("Jan"),tsc("Feb"),tsc("Mar"),tsc("Apr"),tsc("Maj"),tsc("Jun"),tsc("Jul"),tsc("Aug"),tsc("Sep"),tsc("Okt"),tsc("Nov"),tsc("Dec")},.mon={tsc("Januar"),tsc("Februar"),tsc("Mart"),tsc("April"),tsc("Maj"),tsc("Juni"),tsc("Juli"),tsc("August"),tsc("Septembar"),tsc("Oktobar"),tsc("Novembar"),tsc("Decembar")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1dDyY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("da"),.nostr=tsc("ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("387")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%a%N%f%N%d%N%b%N%h %s %e %r%N%T %z%N%c%N"),.country_name=tsc("Bosna i Hercegovina"),.country_ab2=tsc("BA"),.country_ab3=tsc("BIH"),.country_num=70,.country_car=tsc("BIH"),.lang_name=tsc("bosanski"),.lang_ab=tsc("bs"),.lang_term=tsc("bos"),.lang_lib=tsc("bos")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Bosnian language locale for Bosnia and Herzegowina"),.source=tsc(L"adapted from Croatian locale\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Tomislav Vujec\t\t;\t\tfast_io"),.email=tsc(L"tvujec@carnet.hr;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Bosnian"),.territory=tsc(L"Bosnia & Herzegovina"),.revision=tsc(L"0.4"),.date=tsc(L"2004-01-09")},.monetary={.int_curr_symbol=tsc(L"BAM "),.currency_symbol=tsc(L"KM"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"")},.time={.abday={tsc(L"Ned"),tsc(L"Pon"),tsc(L"Uto"),tsc(L"Sri"),tsc(L"Čet"),tsc(L"Pet"),tsc(L"Sub")},.day={tsc(L"Nedjelja"),tsc(L"Ponedjeljak"),tsc(L"Utorak"),tsc(L"Srijeda"),tsc(L"Četvrtak"),tsc(L"Petak"),tsc(L"Subota")},.abmon={tsc(L"Jan"),tsc(L"Feb"),tsc(L"Mar"),tsc(L"Apr"),tsc(L"Maj"),tsc(L"Jun"),tsc(L"Jul"),tsc(L"Aug"),tsc(L"Sep"),tsc(L"Okt"),tsc(L"Nov"),tsc(L"Dec")},.mon={tsc(L"Januar"),tsc(L"Februar"),tsc(L"Mart"),tsc(L"April"),tsc(L"Maj"),tsc(L"Juni"),tsc(L"Juli"),tsc(L"August"),tsc(L"Septembar"),tsc(L"Oktobar"),tsc(L"Novembar"),tsc(L"Decembar")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1dDyY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"da"),.nostr=tsc(L"ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"387")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%a%N%f%N%d%N%b%N%h %s %e %r%N%T %z%N%c%N"),.country_name=tsc(L"Bosna i Hercegovina"),.country_ab2=tsc(L"BA"),.country_ab3=tsc(L"BIH"),.country_num=70,.country_car=tsc(L"BIH"),.lang_name=tsc(L"bosanski"),.lang_ab=tsc(L"bs"),.lang_term=tsc(L"bos"),.lang_lib=tsc(L"bos")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Bosnian language locale for Bosnia and Herzegowina"),.source=tsc(u8"adapted from Croatian locale\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Tomislav Vujec\t\t;\t\tfast_io"),.email=tsc(u8"tvujec@carnet.hr;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Bosnian"),.territory=tsc(u8"Bosnia & Herzegovina"),.revision=tsc(u8"0.4"),.date=tsc(u8"2004-01-09")},.monetary={.int_curr_symbol=tsc(u8"BAM "),.currency_symbol=tsc(u8"KM"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"")},.time={.abday={tsc(u8"Ned"),tsc(u8"Pon"),tsc(u8"Uto"),tsc(u8"Sri"),tsc(u8"Čet"),tsc(u8"Pet"),tsc(u8"Sub")},.day={tsc(u8"Nedjelja"),tsc(u8"Ponedjeljak"),tsc(u8"Utorak"),tsc(u8"Srijeda"),tsc(u8"Četvrtak"),tsc(u8"Petak"),tsc(u8"Subota")},.abmon={tsc(u8"Jan"),tsc(u8"Feb"),tsc(u8"Mar"),tsc(u8"Apr"),tsc(u8"Maj"),tsc(u8"Jun"),tsc(u8"Jul"),tsc(u8"Aug"),tsc(u8"Sep"),tsc(u8"Okt"),tsc(u8"Nov"),tsc(u8"Dec")},.mon={tsc(u8"Januar"),tsc(u8"Februar"),tsc(u8"Mart"),tsc(u8"April"),tsc(u8"Maj"),tsc(u8"Juni"),tsc(u8"Juli"),tsc(u8"August"),tsc(u8"Septembar"),tsc(u8"Oktobar"),tsc(u8"Novembar"),tsc(u8"Decembar")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1dDyY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"da"),.nostr=tsc(u8"ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"387")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%a%N%f%N%d%N%b%N%h %s %e %r%N%T %z%N%c%N"),.country_name=tsc(u8"Bosna i Hercegovina"),.country_ab2=tsc(u8"BA"),.country_ab3=tsc(u8"BIH"),.country_num=70,.country_car=tsc(u8"BIH"),.lang_name=tsc(u8"bosanski"),.lang_ab=tsc(u8"bs"),.lang_term=tsc(u8"bos"),.lang_lib=tsc(u8"bos")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Bosnian language locale for Bosnia and Herzegowina"),.source=tsc(u"adapted from Croatian locale\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Tomislav Vujec\t\t;\t\tfast_io"),.email=tsc(u"tvujec@carnet.hr;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Bosnian"),.territory=tsc(u"Bosnia & Herzegovina"),.revision=tsc(u"0.4"),.date=tsc(u"2004-01-09")},.monetary={.int_curr_symbol=tsc(u"BAM "),.currency_symbol=tsc(u"KM"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"")},.time={.abday={tsc(u"Ned"),tsc(u"Pon"),tsc(u"Uto"),tsc(u"Sri"),tsc(u"Čet"),tsc(u"Pet"),tsc(u"Sub")},.day={tsc(u"Nedjelja"),tsc(u"Ponedjeljak"),tsc(u"Utorak"),tsc(u"Srijeda"),tsc(u"Četvrtak"),tsc(u"Petak"),tsc(u"Subota")},.abmon={tsc(u"Jan"),tsc(u"Feb"),tsc(u"Mar"),tsc(u"Apr"),tsc(u"Maj"),tsc(u"Jun"),tsc(u"Jul"),tsc(u"Aug"),tsc(u"Sep"),tsc(u"Okt"),tsc(u"Nov"),tsc(u"Dec")},.mon={tsc(u"Januar"),tsc(u"Februar"),tsc(u"Mart"),tsc(u"April"),tsc(u"Maj"),tsc(u"Juni"),tsc(u"Juli"),tsc(u"August"),tsc(u"Septembar"),tsc(u"Oktobar"),tsc(u"Novembar"),tsc(u"Decembar")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1dDyY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"da"),.nostr=tsc(u"ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"387")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%a%N%f%N%d%N%b%N%h %s %e %r%N%T %z%N%c%N"),.country_name=tsc(u"Bosna i Hercegovina"),.country_ab2=tsc(u"BA"),.country_ab3=tsc(u"BIH"),.country_num=70,.country_car=tsc(u"BIH"),.lang_name=tsc(u"bosanski"),.lang_ab=tsc(u"bs"),.lang_term=tsc(u"bos"),.lang_lib=tsc(u"bos")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Bosnian language locale for Bosnia and Herzegowina"),.source=tsc(U"adapted from Croatian locale\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Tomislav Vujec\t\t;\t\tfast_io"),.email=tsc(U"tvujec@carnet.hr;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Bosnian"),.territory=tsc(U"Bosnia & Herzegovina"),.revision=tsc(U"0.4"),.date=tsc(U"2004-01-09")},.monetary={.int_curr_symbol=tsc(U"BAM "),.currency_symbol=tsc(U"KM"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"")},.time={.abday={tsc(U"Ned"),tsc(U"Pon"),tsc(U"Uto"),tsc(U"Sri"),tsc(U"Čet"),tsc(U"Pet"),tsc(U"Sub")},.day={tsc(U"Nedjelja"),tsc(U"Ponedjeljak"),tsc(U"Utorak"),tsc(U"Srijeda"),tsc(U"Četvrtak"),tsc(U"Petak"),tsc(U"Subota")},.abmon={tsc(U"Jan"),tsc(U"Feb"),tsc(U"Mar"),tsc(U"Apr"),tsc(U"Maj"),tsc(U"Jun"),tsc(U"Jul"),tsc(U"Aug"),tsc(U"Sep"),tsc(U"Okt"),tsc(U"Nov"),tsc(U"Dec")},.mon={tsc(U"Januar"),tsc(U"Februar"),tsc(U"Mart"),tsc(U"April"),tsc(U"Maj"),tsc(U"Juni"),tsc(U"Juli"),tsc(U"August"),tsc(U"Septembar"),tsc(U"Oktobar"),tsc(U"Novembar"),tsc(U"Decembar")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1dDyY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"da"),.nostr=tsc(U"ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"387")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%a%N%f%N%d%N%b%N%h %s %e %r%N%T %z%N%c%N"),.country_name=tsc(U"Bosna i Hercegovina"),.country_ab2=tsc(U"BA"),.country_ab3=tsc(U"BIH"),.country_num=70,.country_car=tsc(U"BIH"),.lang_name=tsc(U"bosanski"),.lang_ab=tsc(U"bs"),.lang_term=tsc(U"bos"),.lang_lib=tsc(U"bos")},.measurement={.measurement=1}};


}
}

#include"../main.h"