#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr lc_all lc_all_global{.identification={.title=tsc("C locale"),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc(""),.territory=tsc(""),.revision=tsc("2.0"),.date=tsc("2020-06-28")},.monetary={.int_curr_symbol=tsc(""),.currency_symbol=tsc(""),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(""),.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.int_p_sep_by_space=SIZE_MAX,.int_n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc("")},.time={.abday={tsc("Sun"),tsc("Mon"),tsc("Tue"),tsc("Wed"),tsc("Thu"),tsc("Fri"),tsc("Sat")},.day={tsc("Sunday"),tsc("Monday"),tsc("Tuesday"),tsc("Wednesday"),tsc("Thursday"),tsc("Friday"),tsc("Saturday")},.abmon={tsc("Jan"),tsc("Feb"),tsc("Mar"),tsc("Apr"),tsc("May"),tsc("Jun"),tsc("Jul"),tsc("Aug"),tsc("Sep"),tsc("Oct"),tsc("Nov"),tsc("Dec")},.mon={tsc("January"),tsc("February"),tsc("March"),tsc("April"),tsc("May"),tsc("June"),tsc("July"),tsc("August"),tsc("September"),tsc("October"),tsc("November"),tsc("December")},.d_t_fmt=tsc("%a %b %e %H:%M:%S %Y"),.d_fmt=tsc("%m/%d/%y"),.t_fmt=tsc("%H:%M:%S"),.t_fmt_ampm=tsc("%I:%M:%S %p"),.date_fmt=tsc("%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc("AM"),tsc("PM")},.week={7,19971201,4},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc("^[yY]"),.noexpr=tsc("^[nN]"),.yesstr=tsc("Yes"),.nostr=tsc("No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l")},.name={.name_fmt=tsc("%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"C locale"),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L""),.territory=tsc(L""),.revision=tsc(L"2.0"),.date=tsc(L"2020-06-28")},.monetary={.int_curr_symbol=tsc(L""),.currency_symbol=tsc(L""),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L""),.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.int_p_sep_by_space=SIZE_MAX,.int_n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L"")},.time={.abday={tsc(L"Sun"),tsc(L"Mon"),tsc(L"Tue"),tsc(L"Wed"),tsc(L"Thu"),tsc(L"Fri"),tsc(L"Sat")},.day={tsc(L"Sunday"),tsc(L"Monday"),tsc(L"Tuesday"),tsc(L"Wednesday"),tsc(L"Thursday"),tsc(L"Friday"),tsc(L"Saturday")},.abmon={tsc(L"Jan"),tsc(L"Feb"),tsc(L"Mar"),tsc(L"Apr"),tsc(L"May"),tsc(L"Jun"),tsc(L"Jul"),tsc(L"Aug"),tsc(L"Sep"),tsc(L"Oct"),tsc(L"Nov"),tsc(L"Dec")},.mon={tsc(L"January"),tsc(L"February"),tsc(L"March"),tsc(L"April"),tsc(L"May"),tsc(L"June"),tsc(L"July"),tsc(L"August"),tsc(L"September"),tsc(L"October"),tsc(L"November"),tsc(L"December")},.d_t_fmt=tsc(L"%a %b %e %H:%M:%S %Y"),.d_fmt=tsc(L"%m/%d/%y"),.t_fmt=tsc(L"%H:%M:%S"),.t_fmt_ampm=tsc(L"%I:%M:%S %p"),.date_fmt=tsc(L"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(L"AM"),tsc(L"PM")},.week={7,19971201,4},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc(L"^[yY]"),.noexpr=tsc(L"^[nN]"),.yesstr=tsc(L"Yes"),.nostr=tsc(L"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l")},.name={.name_fmt=tsc(L"%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"C locale"),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8""),.territory=tsc(u8""),.revision=tsc(u8"2.0"),.date=tsc(u8"2020-06-28")},.monetary={.int_curr_symbol=tsc(u8""),.currency_symbol=tsc(u8""),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8""),.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.int_p_sep_by_space=SIZE_MAX,.int_n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8"")},.time={.abday={tsc(u8"Sun"),tsc(u8"Mon"),tsc(u8"Tue"),tsc(u8"Wed"),tsc(u8"Thu"),tsc(u8"Fri"),tsc(u8"Sat")},.day={tsc(u8"Sunday"),tsc(u8"Monday"),tsc(u8"Tuesday"),tsc(u8"Wednesday"),tsc(u8"Thursday"),tsc(u8"Friday"),tsc(u8"Saturday")},.abmon={tsc(u8"Jan"),tsc(u8"Feb"),tsc(u8"Mar"),tsc(u8"Apr"),tsc(u8"May"),tsc(u8"Jun"),tsc(u8"Jul"),tsc(u8"Aug"),tsc(u8"Sep"),tsc(u8"Oct"),tsc(u8"Nov"),tsc(u8"Dec")},.mon={tsc(u8"January"),tsc(u8"February"),tsc(u8"March"),tsc(u8"April"),tsc(u8"May"),tsc(u8"June"),tsc(u8"July"),tsc(u8"August"),tsc(u8"September"),tsc(u8"October"),tsc(u8"November"),tsc(u8"December")},.d_t_fmt=tsc(u8"%a %b %e %H:%M:%S %Y"),.d_fmt=tsc(u8"%m/%d/%y"),.t_fmt=tsc(u8"%H:%M:%S"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p"),.date_fmt=tsc(u8"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(u8"AM"),tsc(u8"PM")},.week={7,19971201,4},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc(u8"^[yY]"),.noexpr=tsc(u8"^[nN]"),.yesstr=tsc(u8"Yes"),.nostr=tsc(u8"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l")},.name={.name_fmt=tsc(u8"%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"C locale"),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u""),.territory=tsc(u""),.revision=tsc(u"2.0"),.date=tsc(u"2020-06-28")},.monetary={.int_curr_symbol=tsc(u""),.currency_symbol=tsc(u""),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u""),.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.int_p_sep_by_space=SIZE_MAX,.int_n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u"")},.time={.abday={tsc(u"Sun"),tsc(u"Mon"),tsc(u"Tue"),tsc(u"Wed"),tsc(u"Thu"),tsc(u"Fri"),tsc(u"Sat")},.day={tsc(u"Sunday"),tsc(u"Monday"),tsc(u"Tuesday"),tsc(u"Wednesday"),tsc(u"Thursday"),tsc(u"Friday"),tsc(u"Saturday")},.abmon={tsc(u"Jan"),tsc(u"Feb"),tsc(u"Mar"),tsc(u"Apr"),tsc(u"May"),tsc(u"Jun"),tsc(u"Jul"),tsc(u"Aug"),tsc(u"Sep"),tsc(u"Oct"),tsc(u"Nov"),tsc(u"Dec")},.mon={tsc(u"January"),tsc(u"February"),tsc(u"March"),tsc(u"April"),tsc(u"May"),tsc(u"June"),tsc(u"July"),tsc(u"August"),tsc(u"September"),tsc(u"October"),tsc(u"November"),tsc(u"December")},.d_t_fmt=tsc(u"%a %b %e %H:%M:%S %Y"),.d_fmt=tsc(u"%m/%d/%y"),.t_fmt=tsc(u"%H:%M:%S"),.t_fmt_ampm=tsc(u"%I:%M:%S %p"),.date_fmt=tsc(u"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(u"AM"),tsc(u"PM")},.week={7,19971201,4},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc(u"^[yY]"),.noexpr=tsc(u"^[nN]"),.yesstr=tsc(u"Yes"),.nostr=tsc(u"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l")},.name={.name_fmt=tsc(u"%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"C locale"),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U""),.territory=tsc(U""),.revision=tsc(U"2.0"),.date=tsc(U"2020-06-28")},.monetary={.int_curr_symbol=tsc(U""),.currency_symbol=tsc(U""),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U""),.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.int_p_sep_by_space=SIZE_MAX,.int_n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U"")},.time={.abday={tsc(U"Sun"),tsc(U"Mon"),tsc(U"Tue"),tsc(U"Wed"),tsc(U"Thu"),tsc(U"Fri"),tsc(U"Sat")},.day={tsc(U"Sunday"),tsc(U"Monday"),tsc(U"Tuesday"),tsc(U"Wednesday"),tsc(U"Thursday"),tsc(U"Friday"),tsc(U"Saturday")},.abmon={tsc(U"Jan"),tsc(U"Feb"),tsc(U"Mar"),tsc(U"Apr"),tsc(U"May"),tsc(U"Jun"),tsc(U"Jul"),tsc(U"Aug"),tsc(U"Sep"),tsc(U"Oct"),tsc(U"Nov"),tsc(U"Dec")},.mon={tsc(U"January"),tsc(U"February"),tsc(U"March"),tsc(U"April"),tsc(U"May"),tsc(U"June"),tsc(U"July"),tsc(U"August"),tsc(U"September"),tsc(U"October"),tsc(U"November"),tsc(U"December")},.d_t_fmt=tsc(U"%a %b %e %H:%M:%S %Y"),.d_fmt=tsc(U"%m/%d/%y"),.t_fmt=tsc(U"%H:%M:%S"),.t_fmt_ampm=tsc(U"%I:%M:%S %p"),.date_fmt=tsc(U"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(U"AM"),tsc(U"PM")},.week={7,19971201,4},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc(U"^[yY]"),.noexpr=tsc(U"^[nN]"),.yesstr=tsc(U"Yes"),.nostr=tsc(U"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l")},.name={.name_fmt=tsc(U"%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};


}
}

#include"../main.h"