#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Dhivehi Language Locale for Maldives"),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("sofwath@hotmail.com;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Divehi"),.territory=tsc("Maldives"),.revision=tsc("0.1"),.date=tsc("2006-05-13")},.monetary={.int_curr_symbol=tsc("MVR "),.currency_symbol=tsc("ރ."),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=2,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("އާދީއްތަ"),tsc("ހޯމަ"),tsc("އަންގާރަ"),tsc("ބުދަ"),tsc("ބުރާސްފަތި"),tsc("ހުކުރު"),tsc("ހޮނިހިރު")},.day={tsc("އާދީއްތަ"),tsc("ހޯމަ"),tsc("އަންގާރަ"),tsc("ބުދަ"),tsc("ބުރާސްފަތި"),tsc("ހުކުރު"),tsc("ހޮނިހިރު")},.abmon={tsc("ޖެނުއަރީ"),tsc("ފެބްރުއަރީ"),tsc("މާރޗް"),tsc("އެޕްރީލް"),tsc("މެއި"),tsc("ޖޫން"),tsc("ޖުލައި"),tsc("އޮގަސްޓް"),tsc("ސެޕްޓެންބަރ"),tsc("އޮކްޓޫބަރ"),tsc("ނޮވެންބަރ"),tsc("ޑިސެންބަރ")},.mon={tsc("ޖެނުއަރީ"),tsc("ފެބްރުއަރީ"),tsc("މާރޗް"),tsc("އެޕްރީލް"),tsc("މެއި"),tsc("ޖޫން"),tsc("ޖުލައި"),tsc("އޮގަސްޓް"),tsc("ސެޕްޓެންބަރ"),tsc("އޮކްޓޫބަރ"),tsc("ނޮވެންބަރ"),tsc("ޑިސެންބަރ")},.d_t_fmt=tsc("%H:%M:%S %Y %b %d %a"),.d_fmt=tsc("%d//%m//%Y"),.t_fmt=tsc("%H:%M:%S"),.t_fmt_ampm=tsc("%P %I:%M:%S"),.date_fmt=tsc("%Z %H:%M:%S %Y %b %d %a"),.am_pm={tsc("މކ"),tsc("މފ")},.week={7,19971130,1},.first_weekday=6,.cal_direction=3},.messages={.yesexpr=tsc("^[+1yY]"),.noexpr=tsc("^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.tel_dom_fmt=tsc("%a %l"),.int_select=tsc("00"),.int_prefix=tsc("960")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.country_name=tsc("ދިވެހިރާއްޖެ"),.country_ab2=tsc("MV"),.country_ab3=tsc("MDV"),.country_num=462,.country_car=tsc("MV"),.lang_name=tsc("ދިވެހި"),.lang_ab=tsc("dv"),.lang_term=tsc("div"),.lang_lib=tsc("div")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Dhivehi Language Locale for Maldives"),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"sofwath@hotmail.com;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Divehi"),.territory=tsc(L"Maldives"),.revision=tsc(L"0.1"),.date=tsc(L"2006-05-13")},.monetary={.int_curr_symbol=tsc(L"MVR "),.currency_symbol=tsc(L"ރ."),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=2,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"އާދީއްތަ"),tsc(L"ހޯމަ"),tsc(L"އަންގާރަ"),tsc(L"ބުދަ"),tsc(L"ބުރާސްފަތި"),tsc(L"ހުކުރު"),tsc(L"ހޮނިހިރު")},.day={tsc(L"އާދީއްތަ"),tsc(L"ހޯމަ"),tsc(L"އަންގާރަ"),tsc(L"ބުދަ"),tsc(L"ބުރާސްފަތި"),tsc(L"ހުކުރު"),tsc(L"ހޮނިހިރު")},.abmon={tsc(L"ޖެނުއަރީ"),tsc(L"ފެބްރުއަރީ"),tsc(L"މާރޗް"),tsc(L"އެޕްރީލް"),tsc(L"މެއި"),tsc(L"ޖޫން"),tsc(L"ޖުލައި"),tsc(L"އޮގަސްޓް"),tsc(L"ސެޕްޓެންބަރ"),tsc(L"އޮކްޓޫބަރ"),tsc(L"ނޮވެންބަރ"),tsc(L"ޑިސެންބަރ")},.mon={tsc(L"ޖެނުއަރީ"),tsc(L"ފެބްރުއަރީ"),tsc(L"މާރޗް"),tsc(L"އެޕްރީލް"),tsc(L"މެއި"),tsc(L"ޖޫން"),tsc(L"ޖުލައި"),tsc(L"އޮގަސްޓް"),tsc(L"ސެޕްޓެންބަރ"),tsc(L"އޮކްޓޫބަރ"),tsc(L"ނޮވެންބަރ"),tsc(L"ޑިސެންބަރ")},.d_t_fmt=tsc(L"%H:%M:%S %Y %b %d %a"),.d_fmt=tsc(L"%d//%m//%Y"),.t_fmt=tsc(L"%H:%M:%S"),.t_fmt_ampm=tsc(L"%P %I:%M:%S"),.date_fmt=tsc(L"%Z %H:%M:%S %Y %b %d %a"),.am_pm={tsc(L"މކ"),tsc(L"މފ")},.week={7,19971130,1},.first_weekday=6,.cal_direction=3},.messages={.yesexpr=tsc(L"^[+1yY]"),.noexpr=tsc(L"^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.tel_dom_fmt=tsc(L"%a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"960")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.country_name=tsc(L"ދިވެހިރާއްޖެ"),.country_ab2=tsc(L"MV"),.country_ab3=tsc(L"MDV"),.country_num=462,.country_car=tsc(L"MV"),.lang_name=tsc(L"ދިވެހި"),.lang_ab=tsc(L"dv"),.lang_term=tsc(L"div"),.lang_lib=tsc(L"div")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Dhivehi Language Locale for Maldives"),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"sofwath@hotmail.com;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Divehi"),.territory=tsc(u8"Maldives"),.revision=tsc(u8"0.1"),.date=tsc(u8"2006-05-13")},.monetary={.int_curr_symbol=tsc(u8"MVR "),.currency_symbol=tsc(u8"ރ."),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=2,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"އާދީއްތަ"),tsc(u8"ހޯމަ"),tsc(u8"އަންގާރަ"),tsc(u8"ބުދަ"),tsc(u8"ބުރާސްފަތި"),tsc(u8"ހުކުރު"),tsc(u8"ހޮނިހިރު")},.day={tsc(u8"އާދީއްތަ"),tsc(u8"ހޯމަ"),tsc(u8"އަންގާރަ"),tsc(u8"ބުދަ"),tsc(u8"ބުރާސްފަތި"),tsc(u8"ހުކުރު"),tsc(u8"ހޮނިހިރު")},.abmon={tsc(u8"ޖެނުއަރީ"),tsc(u8"ފެބްރުއަރީ"),tsc(u8"މާރޗް"),tsc(u8"އެޕްރީލް"),tsc(u8"މެއި"),tsc(u8"ޖޫން"),tsc(u8"ޖުލައި"),tsc(u8"އޮގަސްޓް"),tsc(u8"ސެޕްޓެންބަރ"),tsc(u8"އޮކްޓޫބަރ"),tsc(u8"ނޮވެންބަރ"),tsc(u8"ޑިސެންބަރ")},.mon={tsc(u8"ޖެނުއަރީ"),tsc(u8"ފެބްރުއަރީ"),tsc(u8"މާރޗް"),tsc(u8"އެޕްރީލް"),tsc(u8"މެއި"),tsc(u8"ޖޫން"),tsc(u8"ޖުލައި"),tsc(u8"އޮގަސްޓް"),tsc(u8"ސެޕްޓެންބަރ"),tsc(u8"އޮކްޓޫބަރ"),tsc(u8"ނޮވެންބަރ"),tsc(u8"ޑިސެންބަރ")},.d_t_fmt=tsc(u8"%H:%M:%S %Y %b %d %a"),.d_fmt=tsc(u8"%d//%m//%Y"),.t_fmt=tsc(u8"%H:%M:%S"),.t_fmt_ampm=tsc(u8"%P %I:%M:%S"),.date_fmt=tsc(u8"%Z %H:%M:%S %Y %b %d %a"),.am_pm={tsc(u8"މކ"),tsc(u8"މފ")},.week={7,19971130,1},.first_weekday=6,.cal_direction=3},.messages={.yesexpr=tsc(u8"^[+1yY]"),.noexpr=tsc(u8"^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.tel_dom_fmt=tsc(u8"%a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"960")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.country_name=tsc(u8"ދިވެހިރާއްޖެ"),.country_ab2=tsc(u8"MV"),.country_ab3=tsc(u8"MDV"),.country_num=462,.country_car=tsc(u8"MV"),.lang_name=tsc(u8"ދިވެހި"),.lang_ab=tsc(u8"dv"),.lang_term=tsc(u8"div"),.lang_lib=tsc(u8"div")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Dhivehi Language Locale for Maldives"),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"sofwath@hotmail.com;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Divehi"),.territory=tsc(u"Maldives"),.revision=tsc(u"0.1"),.date=tsc(u"2006-05-13")},.monetary={.int_curr_symbol=tsc(u"MVR "),.currency_symbol=tsc(u"ރ."),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=2,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"އާދީއްތަ"),tsc(u"ހޯމަ"),tsc(u"އަންގާރަ"),tsc(u"ބުދަ"),tsc(u"ބުރާސްފަތި"),tsc(u"ހުކުރު"),tsc(u"ހޮނިހިރު")},.day={tsc(u"އާދީއްތަ"),tsc(u"ހޯމަ"),tsc(u"އަންގާރަ"),tsc(u"ބުދަ"),tsc(u"ބުރާސްފަތި"),tsc(u"ހުކުރު"),tsc(u"ހޮނިހިރު")},.abmon={tsc(u"ޖެނުއަރީ"),tsc(u"ފެބްރުއަރީ"),tsc(u"މާރޗް"),tsc(u"އެޕްރީލް"),tsc(u"މެއި"),tsc(u"ޖޫން"),tsc(u"ޖުލައި"),tsc(u"އޮގަސްޓް"),tsc(u"ސެޕްޓެންބަރ"),tsc(u"އޮކްޓޫބަރ"),tsc(u"ނޮވެންބަރ"),tsc(u"ޑިސެންބަރ")},.mon={tsc(u"ޖެނުއަރީ"),tsc(u"ފެބްރުއަރީ"),tsc(u"މާރޗް"),tsc(u"އެޕްރީލް"),tsc(u"މެއި"),tsc(u"ޖޫން"),tsc(u"ޖުލައި"),tsc(u"އޮގަސްޓް"),tsc(u"ސެޕްޓެންބަރ"),tsc(u"އޮކްޓޫބަރ"),tsc(u"ނޮވެންބަރ"),tsc(u"ޑިސެންބަރ")},.d_t_fmt=tsc(u"%H:%M:%S %Y %b %d %a"),.d_fmt=tsc(u"%d//%m//%Y"),.t_fmt=tsc(u"%H:%M:%S"),.t_fmt_ampm=tsc(u"%P %I:%M:%S"),.date_fmt=tsc(u"%Z %H:%M:%S %Y %b %d %a"),.am_pm={tsc(u"މކ"),tsc(u"މފ")},.week={7,19971130,1},.first_weekday=6,.cal_direction=3},.messages={.yesexpr=tsc(u"^[+1yY]"),.noexpr=tsc(u"^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.tel_dom_fmt=tsc(u"%a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"960")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.country_name=tsc(u"ދިވެހިރާއްޖެ"),.country_ab2=tsc(u"MV"),.country_ab3=tsc(u"MDV"),.country_num=462,.country_car=tsc(u"MV"),.lang_name=tsc(u"ދިވެހި"),.lang_ab=tsc(u"dv"),.lang_term=tsc(u"div"),.lang_lib=tsc(u"div")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Dhivehi Language Locale for Maldives"),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"sofwath@hotmail.com;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Divehi"),.territory=tsc(U"Maldives"),.revision=tsc(U"0.1"),.date=tsc(U"2006-05-13")},.monetary={.int_curr_symbol=tsc(U"MVR "),.currency_symbol=tsc(U"ރ."),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=2,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"އާދީއްތަ"),tsc(U"ހޯމަ"),tsc(U"އަންގާރަ"),tsc(U"ބުދަ"),tsc(U"ބުރާސްފަތި"),tsc(U"ހުކުރު"),tsc(U"ހޮނިހިރު")},.day={tsc(U"އާދީއްތަ"),tsc(U"ހޯމަ"),tsc(U"އަންގާރަ"),tsc(U"ބުދަ"),tsc(U"ބުރާސްފަތި"),tsc(U"ހުކުރު"),tsc(U"ހޮނިހިރު")},.abmon={tsc(U"ޖެނުއަރީ"),tsc(U"ފެބްރުއަރީ"),tsc(U"މާރޗް"),tsc(U"އެޕްރީލް"),tsc(U"މެއި"),tsc(U"ޖޫން"),tsc(U"ޖުލައި"),tsc(U"އޮގަސްޓް"),tsc(U"ސެޕްޓެންބަރ"),tsc(U"އޮކްޓޫބަރ"),tsc(U"ނޮވެންބަރ"),tsc(U"ޑިސެންބަރ")},.mon={tsc(U"ޖެނުއަރީ"),tsc(U"ފެބްރުއަރީ"),tsc(U"މާރޗް"),tsc(U"އެޕްރީލް"),tsc(U"މެއި"),tsc(U"ޖޫން"),tsc(U"ޖުލައި"),tsc(U"އޮގަސްޓް"),tsc(U"ސެޕްޓެންބަރ"),tsc(U"އޮކްޓޫބަރ"),tsc(U"ނޮވެންބަރ"),tsc(U"ޑިސެންބަރ")},.d_t_fmt=tsc(U"%H:%M:%S %Y %b %d %a"),.d_fmt=tsc(U"%d//%m//%Y"),.t_fmt=tsc(U"%H:%M:%S"),.t_fmt_ampm=tsc(U"%P %I:%M:%S"),.date_fmt=tsc(U"%Z %H:%M:%S %Y %b %d %a"),.am_pm={tsc(U"މކ"),tsc(U"މފ")},.week={7,19971130,1},.first_weekday=6,.cal_direction=3},.messages={.yesexpr=tsc(U"^[+1yY]"),.noexpr=tsc(U"^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.tel_dom_fmt=tsc(U"%a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"960")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.country_name=tsc(U"ދިވެހިރާއްޖެ"),.country_ab2=tsc(U"MV"),.country_ab3=tsc(U"MDV"),.country_num=462,.country_car=tsc(U"MV"),.lang_name=tsc(U"ދިވެހި"),.lang_ab=tsc(U"dv"),.lang_term=tsc(U"div"),.lang_lib=tsc(U"div")},.measurement={.measurement=1}};


}
}

#include"../main.h"