#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t monetary_mon_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Esperanto language locale"),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("debian-esperanto@lists.debian.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Esperanto"),.territory=tsc(""),.revision=tsc("draft"),.date=tsc("2016-06-10")},.monetary={.int_curr_symbol=tsc("XDR "),.currency_symbol=tsc("¤"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("")},.time={.abday={tsc("dim"),tsc("lun"),tsc("mar"),tsc("mer"),tsc("ĵaŭ"),tsc("ven"),tsc("sab")},.day={tsc("dimanĉo"),tsc("lundo"),tsc("mardo"),tsc("merkredo"),tsc("ĵaŭdo"),tsc("vendredo"),tsc("sabato")},.abmon={tsc("Jan"),tsc("Feb"),tsc("Mar"),tsc("Apr"),tsc("Maj"),tsc("Jun"),tsc("Jul"),tsc("Aŭg"),tsc("Sep"),tsc("Okt"),tsc("Nov"),tsc("Dec")},.mon={tsc("Januaro"),tsc("Februaro"),tsc("Marto"),tsc("Aprilo"),tsc("Majo"),tsc("Junio"),tsc("Julio"),tsc("Aŭgusto"),tsc("Septembro"),tsc("Oktobro"),tsc("Novembro"),tsc("Decembro")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%Y-%m-%d"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1}},.messages={.yesexpr=tsc("^[+1JjYy]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("Jes"),.nostr=tsc("Ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a%t%l"),.int_select=tsc("00")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f"),.name_mr=tsc("s-ro"),.name_mrs=tsc("s-ino"),.name_ms=tsc("s-ino")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.lang_name=tsc("esperanto"),.lang_ab=tsc("eo"),.lang_term=tsc("epo")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Esperanto language locale"),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"debian-esperanto@lists.debian.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Esperanto"),.territory=tsc(L""),.revision=tsc(L"draft"),.date=tsc(L"2016-06-10")},.monetary={.int_curr_symbol=tsc(L"XDR "),.currency_symbol=tsc(L"¤"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"")},.time={.abday={tsc(L"dim"),tsc(L"lun"),tsc(L"mar"),tsc(L"mer"),tsc(L"ĵaŭ"),tsc(L"ven"),tsc(L"sab")},.day={tsc(L"dimanĉo"),tsc(L"lundo"),tsc(L"mardo"),tsc(L"merkredo"),tsc(L"ĵaŭdo"),tsc(L"vendredo"),tsc(L"sabato")},.abmon={tsc(L"Jan"),tsc(L"Feb"),tsc(L"Mar"),tsc(L"Apr"),tsc(L"Maj"),tsc(L"Jun"),tsc(L"Jul"),tsc(L"Aŭg"),tsc(L"Sep"),tsc(L"Okt"),tsc(L"Nov"),tsc(L"Dec")},.mon={tsc(L"Januaro"),tsc(L"Februaro"),tsc(L"Marto"),tsc(L"Aprilo"),tsc(L"Majo"),tsc(L"Junio"),tsc(L"Julio"),tsc(L"Aŭgusto"),tsc(L"Septembro"),tsc(L"Oktobro"),tsc(L"Novembro"),tsc(L"Decembro")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%Y-%m-%d"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(L"^[+1JjYy]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"Jes"),.nostr=tsc(L"Ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a%t%l"),.int_select=tsc(L"00")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f"),.name_mr=tsc(L"s-ro"),.name_mrs=tsc(L"s-ino"),.name_ms=tsc(L"s-ino")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.lang_name=tsc(L"esperanto"),.lang_ab=tsc(L"eo"),.lang_term=tsc(L"epo")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Esperanto language locale"),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"debian-esperanto@lists.debian.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Esperanto"),.territory=tsc(u8""),.revision=tsc(u8"draft"),.date=tsc(u8"2016-06-10")},.monetary={.int_curr_symbol=tsc(u8"XDR "),.currency_symbol=tsc(u8"¤"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"")},.time={.abday={tsc(u8"dim"),tsc(u8"lun"),tsc(u8"mar"),tsc(u8"mer"),tsc(u8"ĵaŭ"),tsc(u8"ven"),tsc(u8"sab")},.day={tsc(u8"dimanĉo"),tsc(u8"lundo"),tsc(u8"mardo"),tsc(u8"merkredo"),tsc(u8"ĵaŭdo"),tsc(u8"vendredo"),tsc(u8"sabato")},.abmon={tsc(u8"Jan"),tsc(u8"Feb"),tsc(u8"Mar"),tsc(u8"Apr"),tsc(u8"Maj"),tsc(u8"Jun"),tsc(u8"Jul"),tsc(u8"Aŭg"),tsc(u8"Sep"),tsc(u8"Okt"),tsc(u8"Nov"),tsc(u8"Dec")},.mon={tsc(u8"Januaro"),tsc(u8"Februaro"),tsc(u8"Marto"),tsc(u8"Aprilo"),tsc(u8"Majo"),tsc(u8"Junio"),tsc(u8"Julio"),tsc(u8"Aŭgusto"),tsc(u8"Septembro"),tsc(u8"Oktobro"),tsc(u8"Novembro"),tsc(u8"Decembro")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%Y-%m-%d"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u8"^[+1JjYy]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"Jes"),.nostr=tsc(u8"Ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a%t%l"),.int_select=tsc(u8"00")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f"),.name_mr=tsc(u8"s-ro"),.name_mrs=tsc(u8"s-ino"),.name_ms=tsc(u8"s-ino")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.lang_name=tsc(u8"esperanto"),.lang_ab=tsc(u8"eo"),.lang_term=tsc(u8"epo")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Esperanto language locale"),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"debian-esperanto@lists.debian.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Esperanto"),.territory=tsc(u""),.revision=tsc(u"draft"),.date=tsc(u"2016-06-10")},.monetary={.int_curr_symbol=tsc(u"XDR "),.currency_symbol=tsc(u"¤"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"")},.time={.abday={tsc(u"dim"),tsc(u"lun"),tsc(u"mar"),tsc(u"mer"),tsc(u"ĵaŭ"),tsc(u"ven"),tsc(u"sab")},.day={tsc(u"dimanĉo"),tsc(u"lundo"),tsc(u"mardo"),tsc(u"merkredo"),tsc(u"ĵaŭdo"),tsc(u"vendredo"),tsc(u"sabato")},.abmon={tsc(u"Jan"),tsc(u"Feb"),tsc(u"Mar"),tsc(u"Apr"),tsc(u"Maj"),tsc(u"Jun"),tsc(u"Jul"),tsc(u"Aŭg"),tsc(u"Sep"),tsc(u"Okt"),tsc(u"Nov"),tsc(u"Dec")},.mon={tsc(u"Januaro"),tsc(u"Februaro"),tsc(u"Marto"),tsc(u"Aprilo"),tsc(u"Majo"),tsc(u"Junio"),tsc(u"Julio"),tsc(u"Aŭgusto"),tsc(u"Septembro"),tsc(u"Oktobro"),tsc(u"Novembro"),tsc(u"Decembro")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%Y-%m-%d"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u"^[+1JjYy]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"Jes"),.nostr=tsc(u"Ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a%t%l"),.int_select=tsc(u"00")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f"),.name_mr=tsc(u"s-ro"),.name_mrs=tsc(u"s-ino"),.name_ms=tsc(u"s-ino")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.lang_name=tsc(u"esperanto"),.lang_ab=tsc(u"eo"),.lang_term=tsc(u"epo")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Esperanto language locale"),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"debian-esperanto@lists.debian.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Esperanto"),.territory=tsc(U""),.revision=tsc(U"draft"),.date=tsc(U"2016-06-10")},.monetary={.int_curr_symbol=tsc(U"XDR "),.currency_symbol=tsc(U"¤"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"")},.time={.abday={tsc(U"dim"),tsc(U"lun"),tsc(U"mar"),tsc(U"mer"),tsc(U"ĵaŭ"),tsc(U"ven"),tsc(U"sab")},.day={tsc(U"dimanĉo"),tsc(U"lundo"),tsc(U"mardo"),tsc(U"merkredo"),tsc(U"ĵaŭdo"),tsc(U"vendredo"),tsc(U"sabato")},.abmon={tsc(U"Jan"),tsc(U"Feb"),tsc(U"Mar"),tsc(U"Apr"),tsc(U"Maj"),tsc(U"Jun"),tsc(U"Jul"),tsc(U"Aŭg"),tsc(U"Sep"),tsc(U"Okt"),tsc(U"Nov"),tsc(U"Dec")},.mon={tsc(U"Januaro"),tsc(U"Februaro"),tsc(U"Marto"),tsc(U"Aprilo"),tsc(U"Majo"),tsc(U"Junio"),tsc(U"Julio"),tsc(U"Aŭgusto"),tsc(U"Septembro"),tsc(U"Oktobro"),tsc(U"Novembro"),tsc(U"Decembro")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%Y-%m-%d"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(U"^[+1JjYy]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"Jes"),.nostr=tsc(U"Ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a%t%l"),.int_select=tsc(U"00")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f"),.name_mr=tsc(U"s-ro"),.name_mrs=tsc(U"s-ino"),.name_ms=tsc(U"s-ino")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%%z %T%N%c%N"),.lang_name=tsc(U"esperanto"),.lang_ab=tsc(U"eo"),.lang_term=tsc(U"epo")},.measurement={.measurement=1}};


}
}

#include"../main.h"