#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Estonian locale for Estonia"),.source=tsc("Estonian Informatics Fund\t\t;\t\tfast_io"),.address=tsc("To-nisma:gi 8, Tallinn, EE0100 Estonia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Estonian"),.territory=tsc("Estonia"),.revision=tsc("1.0"),.date=tsc("2000-06-29")},.monetary={.int_curr_symbol=tsc("EUR "),.currency_symbol=tsc("€"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("P"),tsc("E"),tsc("T"),tsc("K"),tsc("N"),tsc("R"),tsc("L")},.day={tsc("pühapäev"),tsc("esmaspäev"),tsc("teisipäev"),tsc("kolmapäev"),tsc("neljapäev"),tsc("reede"),tsc("laupäev")},.abmon={tsc("jaan "),tsc("veebr"),tsc("märts"),tsc("apr  "),tsc("mai  "),tsc("juuni"),tsc("juuli"),tsc("aug  "),tsc("sept "),tsc("okt  "),tsc("nov  "),tsc("dets ")},.mon={tsc("jaanuar"),tsc("veebruar"),tsc("märts"),tsc("aprill"),tsc("mai"),tsc("juuni"),tsc("juuli"),tsc("august"),tsc("september"),tsc("oktoober"),tsc("november"),tsc("detsember")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc("^[+1JjYy]"),.noexpr=tsc("^[-0EeNn]"),.yesstr=tsc("jah"),.nostr=tsc("ei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("372")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%a%N%f%N%d%N%b%N%s%t%h%t%e%t%r%N%C-%z %T%N%c%N"),.country_name=tsc("Eesti"),.country_post=tsc("EE"),.country_ab2=tsc("EE"),.country_ab3=tsc("EST"),.country_num=233,.country_car=tsc("EST"),.country_isbn=tsc("978-9949,978-9985"),.lang_name=tsc("eesti"),.lang_ab=tsc("et"),.lang_term=tsc("est"),.lang_lib=tsc("est")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Estonian locale for Estonia"),.source=tsc(L"Estonian Informatics Fund\t\t;\t\tfast_io"),.address=tsc(L"To-nisma:gi 8, Tallinn, EE0100 Estonia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Estonian"),.territory=tsc(L"Estonia"),.revision=tsc(L"1.0"),.date=tsc(L"2000-06-29")},.monetary={.int_curr_symbol=tsc(L"EUR "),.currency_symbol=tsc(L"€"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"P"),tsc(L"E"),tsc(L"T"),tsc(L"K"),tsc(L"N"),tsc(L"R"),tsc(L"L")},.day={tsc(L"pühapäev"),tsc(L"esmaspäev"),tsc(L"teisipäev"),tsc(L"kolmapäev"),tsc(L"neljapäev"),tsc(L"reede"),tsc(L"laupäev")},.abmon={tsc(L"jaan "),tsc(L"veebr"),tsc(L"märts"),tsc(L"apr  "),tsc(L"mai  "),tsc(L"juuni"),tsc(L"juuli"),tsc(L"aug  "),tsc(L"sept "),tsc(L"okt  "),tsc(L"nov  "),tsc(L"dets ")},.mon={tsc(L"jaanuar"),tsc(L"veebruar"),tsc(L"märts"),tsc(L"aprill"),tsc(L"mai"),tsc(L"juuni"),tsc(L"juuli"),tsc(L"august"),tsc(L"september"),tsc(L"oktoober"),tsc(L"november"),tsc(L"detsember")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1JjYy]"),.noexpr=tsc(L"^[-0EeNn]"),.yesstr=tsc(L"jah"),.nostr=tsc(L"ei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"372")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%a%N%f%N%d%N%b%N%s%t%h%t%e%t%r%N%C-%z %T%N%c%N"),.country_name=tsc(L"Eesti"),.country_post=tsc(L"EE"),.country_ab2=tsc(L"EE"),.country_ab3=tsc(L"EST"),.country_num=233,.country_car=tsc(L"EST"),.country_isbn=tsc(L"978-9949,978-9985"),.lang_name=tsc(L"eesti"),.lang_ab=tsc(L"et"),.lang_term=tsc(L"est"),.lang_lib=tsc(L"est")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Estonian locale for Estonia"),.source=tsc(u8"Estonian Informatics Fund\t\t;\t\tfast_io"),.address=tsc(u8"To-nisma:gi 8, Tallinn, EE0100 Estonia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Estonian"),.territory=tsc(u8"Estonia"),.revision=tsc(u8"1.0"),.date=tsc(u8"2000-06-29")},.monetary={.int_curr_symbol=tsc(u8"EUR "),.currency_symbol=tsc(u8"€"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"P"),tsc(u8"E"),tsc(u8"T"),tsc(u8"K"),tsc(u8"N"),tsc(u8"R"),tsc(u8"L")},.day={tsc(u8"pühapäev"),tsc(u8"esmaspäev"),tsc(u8"teisipäev"),tsc(u8"kolmapäev"),tsc(u8"neljapäev"),tsc(u8"reede"),tsc(u8"laupäev")},.abmon={tsc(u8"jaan "),tsc(u8"veebr"),tsc(u8"märts"),tsc(u8"apr  "),tsc(u8"mai  "),tsc(u8"juuni"),tsc(u8"juuli"),tsc(u8"aug  "),tsc(u8"sept "),tsc(u8"okt  "),tsc(u8"nov  "),tsc(u8"dets ")},.mon={tsc(u8"jaanuar"),tsc(u8"veebruar"),tsc(u8"märts"),tsc(u8"aprill"),tsc(u8"mai"),tsc(u8"juuni"),tsc(u8"juuli"),tsc(u8"august"),tsc(u8"september"),tsc(u8"oktoober"),tsc(u8"november"),tsc(u8"detsember")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1JjYy]"),.noexpr=tsc(u8"^[-0EeNn]"),.yesstr=tsc(u8"jah"),.nostr=tsc(u8"ei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"372")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%a%N%f%N%d%N%b%N%s%t%h%t%e%t%r%N%C-%z %T%N%c%N"),.country_name=tsc(u8"Eesti"),.country_post=tsc(u8"EE"),.country_ab2=tsc(u8"EE"),.country_ab3=tsc(u8"EST"),.country_num=233,.country_car=tsc(u8"EST"),.country_isbn=tsc(u8"978-9949,978-9985"),.lang_name=tsc(u8"eesti"),.lang_ab=tsc(u8"et"),.lang_term=tsc(u8"est"),.lang_lib=tsc(u8"est")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Estonian locale for Estonia"),.source=tsc(u"Estonian Informatics Fund\t\t;\t\tfast_io"),.address=tsc(u"To-nisma:gi 8, Tallinn, EE0100 Estonia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Estonian"),.territory=tsc(u"Estonia"),.revision=tsc(u"1.0"),.date=tsc(u"2000-06-29")},.monetary={.int_curr_symbol=tsc(u"EUR "),.currency_symbol=tsc(u"€"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"P"),tsc(u"E"),tsc(u"T"),tsc(u"K"),tsc(u"N"),tsc(u"R"),tsc(u"L")},.day={tsc(u"pühapäev"),tsc(u"esmaspäev"),tsc(u"teisipäev"),tsc(u"kolmapäev"),tsc(u"neljapäev"),tsc(u"reede"),tsc(u"laupäev")},.abmon={tsc(u"jaan "),tsc(u"veebr"),tsc(u"märts"),tsc(u"apr  "),tsc(u"mai  "),tsc(u"juuni"),tsc(u"juuli"),tsc(u"aug  "),tsc(u"sept "),tsc(u"okt  "),tsc(u"nov  "),tsc(u"dets ")},.mon={tsc(u"jaanuar"),tsc(u"veebruar"),tsc(u"märts"),tsc(u"aprill"),tsc(u"mai"),tsc(u"juuni"),tsc(u"juuli"),tsc(u"august"),tsc(u"september"),tsc(u"oktoober"),tsc(u"november"),tsc(u"detsember")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1JjYy]"),.noexpr=tsc(u"^[-0EeNn]"),.yesstr=tsc(u"jah"),.nostr=tsc(u"ei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"372")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%a%N%f%N%d%N%b%N%s%t%h%t%e%t%r%N%C-%z %T%N%c%N"),.country_name=tsc(u"Eesti"),.country_post=tsc(u"EE"),.country_ab2=tsc(u"EE"),.country_ab3=tsc(u"EST"),.country_num=233,.country_car=tsc(u"EST"),.country_isbn=tsc(u"978-9949,978-9985"),.lang_name=tsc(u"eesti"),.lang_ab=tsc(u"et"),.lang_term=tsc(u"est"),.lang_lib=tsc(u"est")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Estonian locale for Estonia"),.source=tsc(U"Estonian Informatics Fund\t\t;\t\tfast_io"),.address=tsc(U"To-nisma:gi 8, Tallinn, EE0100 Estonia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Estonian"),.territory=tsc(U"Estonia"),.revision=tsc(U"1.0"),.date=tsc(U"2000-06-29")},.monetary={.int_curr_symbol=tsc(U"EUR "),.currency_symbol=tsc(U"€"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"P"),tsc(U"E"),tsc(U"T"),tsc(U"K"),tsc(U"N"),tsc(U"R"),tsc(U"L")},.day={tsc(U"pühapäev"),tsc(U"esmaspäev"),tsc(U"teisipäev"),tsc(U"kolmapäev"),tsc(U"neljapäev"),tsc(U"reede"),tsc(U"laupäev")},.abmon={tsc(U"jaan "),tsc(U"veebr"),tsc(U"märts"),tsc(U"apr  "),tsc(U"mai  "),tsc(U"juuni"),tsc(U"juuli"),tsc(U"aug  "),tsc(U"sept "),tsc(U"okt  "),tsc(U"nov  "),tsc(U"dets ")},.mon={tsc(U"jaanuar"),tsc(U"veebruar"),tsc(U"märts"),tsc(U"aprill"),tsc(U"mai"),tsc(U"juuni"),tsc(U"juuli"),tsc(U"august"),tsc(U"september"),tsc(U"oktoober"),tsc(U"november"),tsc(U"detsember")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1JjYy]"),.noexpr=tsc(U"^[-0EeNn]"),.yesstr=tsc(U"jah"),.nostr=tsc(U"ei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"372")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%a%N%f%N%d%N%b%N%s%t%h%t%e%t%r%N%C-%z %T%N%c%N"),.country_name=tsc(U"Eesti"),.country_post=tsc(U"EE"),.country_ab2=tsc(U"EE"),.country_ab3=tsc(U"EST"),.country_num=233,.country_car=tsc(U"EST"),.country_isbn=tsc(U"978-9949,978-9985"),.lang_name=tsc(U"eesti"),.lang_ab=tsc(U"et"),.lang_term=tsc(U"est"),.lang_lib=tsc(U"est")},.measurement={.measurement=1}};


}
}

#include"../main.h"