#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Faroese locale for Faroe Islands"),.source=tsc("Danish Standards Association\t\t;\t\tfast_io"),.address=tsc("Kollegievej 6, DK-2920 Charlottenlund, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Faroese"),.territory=tsc("Faroe Islands"),.revision=tsc("1.0"),.date=tsc("2000-06-29")},.monetary={.int_curr_symbol=tsc("DKK "),.currency_symbol=tsc("kr."),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc("."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=2,.n_cs_precedes=1,.n_sep_by_space=2,.p_sign_posn=4,.n_sign_posn=4},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("sun"),tsc("mán"),tsc("týs"),tsc("mik"),tsc("hós"),tsc("frí"),tsc("ley")},.day={tsc("sunnudagur"),tsc("mánadagur"),tsc("týsdagur"),tsc("mikudagur"),tsc("hósdagur"),tsc("fríggjadagur"),tsc("leygardagur")},.abmon={tsc("jan"),tsc("feb"),tsc("mar"),tsc("apr"),tsc("mai"),tsc("jun"),tsc("jul"),tsc("aug"),tsc("sep"),tsc("okt"),tsc("nov"),tsc("des")},.mon={tsc("januar"),tsc("februar"),tsc("mars"),tsc("apríl"),tsc("mai"),tsc("juni"),tsc("juli"),tsc("august"),tsc("september"),tsc("oktober"),tsc("november"),tsc("desember")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d//%m-%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc("^[+1JjYy]"),.noexpr=tsc("^[-0Nn]"),.yesstr=tsc("já"),.nostr=tsc("nei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("298")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Føroyar"),.country_ab2=tsc("FO"),.country_ab3=tsc("FRO"),.country_num=234,.country_car=tsc("FO"),.lang_name=tsc("føroyskt"),.lang_ab=tsc("fo"),.lang_term=tsc("fao")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Faroese locale for Faroe Islands"),.source=tsc(L"Danish Standards Association\t\t;\t\tfast_io"),.address=tsc(L"Kollegievej 6, DK-2920 Charlottenlund, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Faroese"),.territory=tsc(L"Faroe Islands"),.revision=tsc(L"1.0"),.date=tsc(L"2000-06-29")},.monetary={.int_curr_symbol=tsc(L"DKK "),.currency_symbol=tsc(L"kr."),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=2,.n_cs_precedes=1,.n_sep_by_space=2,.p_sign_posn=4,.n_sign_posn=4},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"sun"),tsc(L"mán"),tsc(L"týs"),tsc(L"mik"),tsc(L"hós"),tsc(L"frí"),tsc(L"ley")},.day={tsc(L"sunnudagur"),tsc(L"mánadagur"),tsc(L"týsdagur"),tsc(L"mikudagur"),tsc(L"hósdagur"),tsc(L"fríggjadagur"),tsc(L"leygardagur")},.abmon={tsc(L"jan"),tsc(L"feb"),tsc(L"mar"),tsc(L"apr"),tsc(L"mai"),tsc(L"jun"),tsc(L"jul"),tsc(L"aug"),tsc(L"sep"),tsc(L"okt"),tsc(L"nov"),tsc(L"des")},.mon={tsc(L"januar"),tsc(L"februar"),tsc(L"mars"),tsc(L"apríl"),tsc(L"mai"),tsc(L"juni"),tsc(L"juli"),tsc(L"august"),tsc(L"september"),tsc(L"oktober"),tsc(L"november"),tsc(L"desember")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d//%m-%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1JjYy]"),.noexpr=tsc(L"^[-0Nn]"),.yesstr=tsc(L"já"),.nostr=tsc(L"nei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"298")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Føroyar"),.country_ab2=tsc(L"FO"),.country_ab3=tsc(L"FRO"),.country_num=234,.country_car=tsc(L"FO"),.lang_name=tsc(L"føroyskt"),.lang_ab=tsc(L"fo"),.lang_term=tsc(L"fao")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Faroese locale for Faroe Islands"),.source=tsc(u8"Danish Standards Association\t\t;\t\tfast_io"),.address=tsc(u8"Kollegievej 6, DK-2920 Charlottenlund, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Faroese"),.territory=tsc(u8"Faroe Islands"),.revision=tsc(u8"1.0"),.date=tsc(u8"2000-06-29")},.monetary={.int_curr_symbol=tsc(u8"DKK "),.currency_symbol=tsc(u8"kr."),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=2,.n_cs_precedes=1,.n_sep_by_space=2,.p_sign_posn=4,.n_sign_posn=4},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"sun"),tsc(u8"mán"),tsc(u8"týs"),tsc(u8"mik"),tsc(u8"hós"),tsc(u8"frí"),tsc(u8"ley")},.day={tsc(u8"sunnudagur"),tsc(u8"mánadagur"),tsc(u8"týsdagur"),tsc(u8"mikudagur"),tsc(u8"hósdagur"),tsc(u8"fríggjadagur"),tsc(u8"leygardagur")},.abmon={tsc(u8"jan"),tsc(u8"feb"),tsc(u8"mar"),tsc(u8"apr"),tsc(u8"mai"),tsc(u8"jun"),tsc(u8"jul"),tsc(u8"aug"),tsc(u8"sep"),tsc(u8"okt"),tsc(u8"nov"),tsc(u8"des")},.mon={tsc(u8"januar"),tsc(u8"februar"),tsc(u8"mars"),tsc(u8"apríl"),tsc(u8"mai"),tsc(u8"juni"),tsc(u8"juli"),tsc(u8"august"),tsc(u8"september"),tsc(u8"oktober"),tsc(u8"november"),tsc(u8"desember")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d//%m-%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1JjYy]"),.noexpr=tsc(u8"^[-0Nn]"),.yesstr=tsc(u8"já"),.nostr=tsc(u8"nei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"298")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Føroyar"),.country_ab2=tsc(u8"FO"),.country_ab3=tsc(u8"FRO"),.country_num=234,.country_car=tsc(u8"FO"),.lang_name=tsc(u8"føroyskt"),.lang_ab=tsc(u8"fo"),.lang_term=tsc(u8"fao")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Faroese locale for Faroe Islands"),.source=tsc(u"Danish Standards Association\t\t;\t\tfast_io"),.address=tsc(u"Kollegievej 6, DK-2920 Charlottenlund, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Faroese"),.territory=tsc(u"Faroe Islands"),.revision=tsc(u"1.0"),.date=tsc(u"2000-06-29")},.monetary={.int_curr_symbol=tsc(u"DKK "),.currency_symbol=tsc(u"kr."),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=2,.n_cs_precedes=1,.n_sep_by_space=2,.p_sign_posn=4,.n_sign_posn=4},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"sun"),tsc(u"mán"),tsc(u"týs"),tsc(u"mik"),tsc(u"hós"),tsc(u"frí"),tsc(u"ley")},.day={tsc(u"sunnudagur"),tsc(u"mánadagur"),tsc(u"týsdagur"),tsc(u"mikudagur"),tsc(u"hósdagur"),tsc(u"fríggjadagur"),tsc(u"leygardagur")},.abmon={tsc(u"jan"),tsc(u"feb"),tsc(u"mar"),tsc(u"apr"),tsc(u"mai"),tsc(u"jun"),tsc(u"jul"),tsc(u"aug"),tsc(u"sep"),tsc(u"okt"),tsc(u"nov"),tsc(u"des")},.mon={tsc(u"januar"),tsc(u"februar"),tsc(u"mars"),tsc(u"apríl"),tsc(u"mai"),tsc(u"juni"),tsc(u"juli"),tsc(u"august"),tsc(u"september"),tsc(u"oktober"),tsc(u"november"),tsc(u"desember")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d//%m-%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1JjYy]"),.noexpr=tsc(u"^[-0Nn]"),.yesstr=tsc(u"já"),.nostr=tsc(u"nei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"298")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Føroyar"),.country_ab2=tsc(u"FO"),.country_ab3=tsc(u"FRO"),.country_num=234,.country_car=tsc(u"FO"),.lang_name=tsc(u"føroyskt"),.lang_ab=tsc(u"fo"),.lang_term=tsc(u"fao")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Faroese locale for Faroe Islands"),.source=tsc(U"Danish Standards Association\t\t;\t\tfast_io"),.address=tsc(U"Kollegievej 6, DK-2920 Charlottenlund, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Faroese"),.territory=tsc(U"Faroe Islands"),.revision=tsc(U"1.0"),.date=tsc(U"2000-06-29")},.monetary={.int_curr_symbol=tsc(U"DKK "),.currency_symbol=tsc(U"kr."),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=2,.n_cs_precedes=1,.n_sep_by_space=2,.p_sign_posn=4,.n_sign_posn=4},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"sun"),tsc(U"mán"),tsc(U"týs"),tsc(U"mik"),tsc(U"hós"),tsc(U"frí"),tsc(U"ley")},.day={tsc(U"sunnudagur"),tsc(U"mánadagur"),tsc(U"týsdagur"),tsc(U"mikudagur"),tsc(U"hósdagur"),tsc(U"fríggjadagur"),tsc(U"leygardagur")},.abmon={tsc(U"jan"),tsc(U"feb"),tsc(U"mar"),tsc(U"apr"),tsc(U"mai"),tsc(U"jun"),tsc(U"jul"),tsc(U"aug"),tsc(U"sep"),tsc(U"okt"),tsc(U"nov"),tsc(U"des")},.mon={tsc(U"januar"),tsc(U"februar"),tsc(U"mars"),tsc(U"apríl"),tsc(U"mai"),tsc(U"juni"),tsc(U"juli"),tsc(U"august"),tsc(U"september"),tsc(U"oktober"),tsc(U"november"),tsc(U"desember")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d//%m-%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1JjYy]"),.noexpr=tsc(U"^[-0Nn]"),.yesstr=tsc(U"já"),.nostr=tsc(U"nei")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"298")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Føroyar"),.country_ab2=tsc(U"FO"),.country_ab3=tsc(U"FRO"),.country_num=234,.country_car=tsc(U"FO"),.lang_name=tsc(U"føroyskt"),.lang_ab=tsc(U"fo"),.lang_term=tsc(U"fao")},.measurement={.measurement=1}};


}
}

#include"../main.h"