#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr lc_all lc_all_global{.identification={.title=tsc(""),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc(""),.territory=tsc(""),.revision=tsc(""),.date=tsc("2017-06-20")},.monetary={.int_curr_symbol=tsc("XDR "),.currency_symbol=tsc("¤"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(""),.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("")},.time={.abday={tsc("1"),tsc("2"),tsc("3"),tsc("4"),tsc("5"),tsc("6"),tsc("7")},.day={tsc("1"),tsc("2"),tsc("3"),tsc("4"),tsc("5"),tsc("6"),tsc("7")},.abmon={tsc("01"),tsc("02"),tsc("03"),tsc("04"),tsc("05"),tsc("06"),tsc("07"),tsc("08"),tsc("09"),tsc("10"),tsc("11"),tsc("12")},.mon={tsc("01"),tsc("02"),tsc("03"),tsc("04"),tsc("05"),tsc("06"),tsc("07"),tsc("08"),tsc("09"),tsc("10"),tsc("11"),tsc("12")},.d_t_fmt=tsc("%F %T"),.d_fmt=tsc("%F"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(""),tsc("")},.week={7,19971201,4},.first_weekday=1,.first_workday=1},.messages={.yesexpr=tsc("^[+1]"),.noexpr=tsc("^[-0]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a%t%l")},.name={.name_fmt=tsc("%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L""),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L""),.territory=tsc(L""),.revision=tsc(L""),.date=tsc(L"2017-06-20")},.monetary={.int_curr_symbol=tsc(L"XDR "),.currency_symbol=tsc(L"¤"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L""),.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"")},.time={.abday={tsc(L"1"),tsc(L"2"),tsc(L"3"),tsc(L"4"),tsc(L"5"),tsc(L"6"),tsc(L"7")},.day={tsc(L"1"),tsc(L"2"),tsc(L"3"),tsc(L"4"),tsc(L"5"),tsc(L"6"),tsc(L"7")},.abmon={tsc(L"01"),tsc(L"02"),tsc(L"03"),tsc(L"04"),tsc(L"05"),tsc(L"06"),tsc(L"07"),tsc(L"08"),tsc(L"09"),tsc(L"10"),tsc(L"11"),tsc(L"12")},.mon={tsc(L"01"),tsc(L"02"),tsc(L"03"),tsc(L"04"),tsc(L"05"),tsc(L"06"),tsc(L"07"),tsc(L"08"),tsc(L"09"),tsc(L"10"),tsc(L"11"),tsc(L"12")},.d_t_fmt=tsc(L"%F %T"),.d_fmt=tsc(L"%F"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971201,4},.first_weekday=1,.first_workday=1},.messages={.yesexpr=tsc(L"^[+1]"),.noexpr=tsc(L"^[-0]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a%t%l")},.name={.name_fmt=tsc(L"%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8""),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8""),.territory=tsc(u8""),.revision=tsc(u8""),.date=tsc(u8"2017-06-20")},.monetary={.int_curr_symbol=tsc(u8"XDR "),.currency_symbol=tsc(u8"¤"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8""),.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"")},.time={.abday={tsc(u8"1"),tsc(u8"2"),tsc(u8"3"),tsc(u8"4"),tsc(u8"5"),tsc(u8"6"),tsc(u8"7")},.day={tsc(u8"1"),tsc(u8"2"),tsc(u8"3"),tsc(u8"4"),tsc(u8"5"),tsc(u8"6"),tsc(u8"7")},.abmon={tsc(u8"01"),tsc(u8"02"),tsc(u8"03"),tsc(u8"04"),tsc(u8"05"),tsc(u8"06"),tsc(u8"07"),tsc(u8"08"),tsc(u8"09"),tsc(u8"10"),tsc(u8"11"),tsc(u8"12")},.mon={tsc(u8"01"),tsc(u8"02"),tsc(u8"03"),tsc(u8"04"),tsc(u8"05"),tsc(u8"06"),tsc(u8"07"),tsc(u8"08"),tsc(u8"09"),tsc(u8"10"),tsc(u8"11"),tsc(u8"12")},.d_t_fmt=tsc(u8"%F %T"),.d_fmt=tsc(u8"%F"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971201,4},.first_weekday=1,.first_workday=1},.messages={.yesexpr=tsc(u8"^[+1]"),.noexpr=tsc(u8"^[-0]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a%t%l")},.name={.name_fmt=tsc(u8"%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u""),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u""),.territory=tsc(u""),.revision=tsc(u""),.date=tsc(u"2017-06-20")},.monetary={.int_curr_symbol=tsc(u"XDR "),.currency_symbol=tsc(u"¤"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u""),.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"")},.time={.abday={tsc(u"1"),tsc(u"2"),tsc(u"3"),tsc(u"4"),tsc(u"5"),tsc(u"6"),tsc(u"7")},.day={tsc(u"1"),tsc(u"2"),tsc(u"3"),tsc(u"4"),tsc(u"5"),tsc(u"6"),tsc(u"7")},.abmon={tsc(u"01"),tsc(u"02"),tsc(u"03"),tsc(u"04"),tsc(u"05"),tsc(u"06"),tsc(u"07"),tsc(u"08"),tsc(u"09"),tsc(u"10"),tsc(u"11"),tsc(u"12")},.mon={tsc(u"01"),tsc(u"02"),tsc(u"03"),tsc(u"04"),tsc(u"05"),tsc(u"06"),tsc(u"07"),tsc(u"08"),tsc(u"09"),tsc(u"10"),tsc(u"11"),tsc(u"12")},.d_t_fmt=tsc(u"%F %T"),.d_fmt=tsc(u"%F"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971201,4},.first_weekday=1,.first_workday=1},.messages={.yesexpr=tsc(u"^[+1]"),.noexpr=tsc(u"^[-0]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a%t%l")},.name={.name_fmt=tsc(u"%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U""),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U""),.territory=tsc(U""),.revision=tsc(U""),.date=tsc(U"2017-06-20")},.monetary={.int_curr_symbol=tsc(U"XDR "),.currency_symbol=tsc(U"¤"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U""),.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=SIZE_MAX,.frac_digits=SIZE_MAX,.p_cs_precedes=SIZE_MAX,.p_sep_by_space=SIZE_MAX,.n_cs_precedes=SIZE_MAX,.n_sep_by_space=SIZE_MAX,.p_sign_posn=SIZE_MAX,.n_sign_posn=SIZE_MAX},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"")},.time={.abday={tsc(U"1"),tsc(U"2"),tsc(U"3"),tsc(U"4"),tsc(U"5"),tsc(U"6"),tsc(U"7")},.day={tsc(U"1"),tsc(U"2"),tsc(U"3"),tsc(U"4"),tsc(U"5"),tsc(U"6"),tsc(U"7")},.abmon={tsc(U"01"),tsc(U"02"),tsc(U"03"),tsc(U"04"),tsc(U"05"),tsc(U"06"),tsc(U"07"),tsc(U"08"),tsc(U"09"),tsc(U"10"),tsc(U"11"),tsc(U"12")},.mon={tsc(U"01"),tsc(U"02"),tsc(U"03"),tsc(U"04"),tsc(U"05"),tsc(U"06"),tsc(U"07"),tsc(U"08"),tsc(U"09"),tsc(U"10"),tsc(U"11"),tsc(U"12")},.d_t_fmt=tsc(U"%F %T"),.d_fmt=tsc(U"%F"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971201,4},.first_weekday=1,.first_workday=1},.messages={.yesexpr=tsc(U"^[+1]"),.noexpr=tsc(U"^[-0]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a%t%l")},.name={.name_fmt=tsc(U"%p%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%a%N%f%N%d%N%b%N%s %h %e %r%N%C-%z %T%N%c%N")},.measurement={.measurement=1}};


}
}

#include"../main.h"