#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Interlingua locale for France"),.source=tsc("Fedora Project\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Nik Kalach\t\t;\t\tfast_io"),.email=tsc("nikka@fedoraproject.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Interlingua"),.territory=tsc("France"),.revision=tsc("1.0"),.date=tsc("2013-03-01")},.monetary={.int_curr_symbol=tsc("EUR "),.currency_symbol=tsc("€"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("dom"),tsc("lun"),tsc("mar"),tsc("mer"),tsc("jov"),tsc("ven"),tsc("sab")},.day={tsc("dominica"),tsc("lunedi"),tsc("martedi"),tsc("mercuridi"),tsc("jovedi"),tsc("venerdi"),tsc("sabbato")},.abmon={tsc("jan"),tsc("feb"),tsc("mar"),tsc("apr"),tsc("mai"),tsc("jun"),tsc("jul"),tsc("aug"),tsc("sep"),tsc("oct"),tsc("nov"),tsc("dec")},.mon={tsc("januario"),tsc("februario"),tsc("martio"),tsc("april"),tsc("maio"),tsc("junio"),tsc("julio"),tsc("augusto"),tsc("septembre"),tsc("octobre"),tsc("novembre"),tsc("decembre")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc("AM"),tsc("PM")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc("^[+1sSyY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("Si"),.nostr=tsc("No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.tel_dom_fmt=tsc("%a %l"),.int_select=tsc("00"),.int_prefix=tsc("33")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s%t%h%t%e%t%r%N%z%t%T%N%c%N"),.country_name=tsc("Francia"),.country_post=tsc("F"),.country_ab2=tsc("FR"),.country_ab3=tsc("FRA"),.country_num=250,.country_car=tsc("F"),.country_isbn=tsc("979-10"),.lang_name=tsc("interlingua"),.lang_ab=tsc("ia"),.lang_term=tsc("ina"),.lang_lib=tsc("ina")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Interlingua locale for France"),.source=tsc(L"Fedora Project\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Nik Kalach\t\t;\t\tfast_io"),.email=tsc(L"nikka@fedoraproject.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Interlingua"),.territory=tsc(L"France"),.revision=tsc(L"1.0"),.date=tsc(L"2013-03-01")},.monetary={.int_curr_symbol=tsc(L"EUR "),.currency_symbol=tsc(L"€"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"dom"),tsc(L"lun"),tsc(L"mar"),tsc(L"mer"),tsc(L"jov"),tsc(L"ven"),tsc(L"sab")},.day={tsc(L"dominica"),tsc(L"lunedi"),tsc(L"martedi"),tsc(L"mercuridi"),tsc(L"jovedi"),tsc(L"venerdi"),tsc(L"sabbato")},.abmon={tsc(L"jan"),tsc(L"feb"),tsc(L"mar"),tsc(L"apr"),tsc(L"mai"),tsc(L"jun"),tsc(L"jul"),tsc(L"aug"),tsc(L"sep"),tsc(L"oct"),tsc(L"nov"),tsc(L"dec")},.mon={tsc(L"januario"),tsc(L"februario"),tsc(L"martio"),tsc(L"april"),tsc(L"maio"),tsc(L"junio"),tsc(L"julio"),tsc(L"augusto"),tsc(L"septembre"),tsc(L"octobre"),tsc(L"novembre"),tsc(L"decembre")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L"AM"),tsc(L"PM")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1sSyY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"Si"),.nostr=tsc(L"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.tel_dom_fmt=tsc(L"%a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"33")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s%t%h%t%e%t%r%N%z%t%T%N%c%N"),.country_name=tsc(L"Francia"),.country_post=tsc(L"F"),.country_ab2=tsc(L"FR"),.country_ab3=tsc(L"FRA"),.country_num=250,.country_car=tsc(L"F"),.country_isbn=tsc(L"979-10"),.lang_name=tsc(L"interlingua"),.lang_ab=tsc(L"ia"),.lang_term=tsc(L"ina"),.lang_lib=tsc(L"ina")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Interlingua locale for France"),.source=tsc(u8"Fedora Project\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Nik Kalach\t\t;\t\tfast_io"),.email=tsc(u8"nikka@fedoraproject.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Interlingua"),.territory=tsc(u8"France"),.revision=tsc(u8"1.0"),.date=tsc(u8"2013-03-01")},.monetary={.int_curr_symbol=tsc(u8"EUR "),.currency_symbol=tsc(u8"€"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"dom"),tsc(u8"lun"),tsc(u8"mar"),tsc(u8"mer"),tsc(u8"jov"),tsc(u8"ven"),tsc(u8"sab")},.day={tsc(u8"dominica"),tsc(u8"lunedi"),tsc(u8"martedi"),tsc(u8"mercuridi"),tsc(u8"jovedi"),tsc(u8"venerdi"),tsc(u8"sabbato")},.abmon={tsc(u8"jan"),tsc(u8"feb"),tsc(u8"mar"),tsc(u8"apr"),tsc(u8"mai"),tsc(u8"jun"),tsc(u8"jul"),tsc(u8"aug"),tsc(u8"sep"),tsc(u8"oct"),tsc(u8"nov"),tsc(u8"dec")},.mon={tsc(u8"januario"),tsc(u8"februario"),tsc(u8"martio"),tsc(u8"april"),tsc(u8"maio"),tsc(u8"junio"),tsc(u8"julio"),tsc(u8"augusto"),tsc(u8"septembre"),tsc(u8"octobre"),tsc(u8"novembre"),tsc(u8"decembre")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8"AM"),tsc(u8"PM")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1sSyY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"Si"),.nostr=tsc(u8"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.tel_dom_fmt=tsc(u8"%a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"33")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s%t%h%t%e%t%r%N%z%t%T%N%c%N"),.country_name=tsc(u8"Francia"),.country_post=tsc(u8"F"),.country_ab2=tsc(u8"FR"),.country_ab3=tsc(u8"FRA"),.country_num=250,.country_car=tsc(u8"F"),.country_isbn=tsc(u8"979-10"),.lang_name=tsc(u8"interlingua"),.lang_ab=tsc(u8"ia"),.lang_term=tsc(u8"ina"),.lang_lib=tsc(u8"ina")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Interlingua locale for France"),.source=tsc(u"Fedora Project\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Nik Kalach\t\t;\t\tfast_io"),.email=tsc(u"nikka@fedoraproject.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Interlingua"),.territory=tsc(u"France"),.revision=tsc(u"1.0"),.date=tsc(u"2013-03-01")},.monetary={.int_curr_symbol=tsc(u"EUR "),.currency_symbol=tsc(u"€"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"dom"),tsc(u"lun"),tsc(u"mar"),tsc(u"mer"),tsc(u"jov"),tsc(u"ven"),tsc(u"sab")},.day={tsc(u"dominica"),tsc(u"lunedi"),tsc(u"martedi"),tsc(u"mercuridi"),tsc(u"jovedi"),tsc(u"venerdi"),tsc(u"sabbato")},.abmon={tsc(u"jan"),tsc(u"feb"),tsc(u"mar"),tsc(u"apr"),tsc(u"mai"),tsc(u"jun"),tsc(u"jul"),tsc(u"aug"),tsc(u"sep"),tsc(u"oct"),tsc(u"nov"),tsc(u"dec")},.mon={tsc(u"januario"),tsc(u"februario"),tsc(u"martio"),tsc(u"april"),tsc(u"maio"),tsc(u"junio"),tsc(u"julio"),tsc(u"augusto"),tsc(u"septembre"),tsc(u"octobre"),tsc(u"novembre"),tsc(u"decembre")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u"AM"),tsc(u"PM")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1sSyY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"Si"),.nostr=tsc(u"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.tel_dom_fmt=tsc(u"%a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"33")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s%t%h%t%e%t%r%N%z%t%T%N%c%N"),.country_name=tsc(u"Francia"),.country_post=tsc(u"F"),.country_ab2=tsc(u"FR"),.country_ab3=tsc(u"FRA"),.country_num=250,.country_car=tsc(u"F"),.country_isbn=tsc(u"979-10"),.lang_name=tsc(u"interlingua"),.lang_ab=tsc(u"ia"),.lang_term=tsc(u"ina"),.lang_lib=tsc(u"ina")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Interlingua locale for France"),.source=tsc(U"Fedora Project\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Nik Kalach\t\t;\t\tfast_io"),.email=tsc(U"nikka@fedoraproject.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Interlingua"),.territory=tsc(U"France"),.revision=tsc(U"1.0"),.date=tsc(U"2013-03-01")},.monetary={.int_curr_symbol=tsc(U"EUR "),.currency_symbol=tsc(U"€"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"dom"),tsc(U"lun"),tsc(U"mar"),tsc(U"mer"),tsc(U"jov"),tsc(U"ven"),tsc(U"sab")},.day={tsc(U"dominica"),tsc(U"lunedi"),tsc(U"martedi"),tsc(U"mercuridi"),tsc(U"jovedi"),tsc(U"venerdi"),tsc(U"sabbato")},.abmon={tsc(U"jan"),tsc(U"feb"),tsc(U"mar"),tsc(U"apr"),tsc(U"mai"),tsc(U"jun"),tsc(U"jul"),tsc(U"aug"),tsc(U"sep"),tsc(U"oct"),tsc(U"nov"),tsc(U"dec")},.mon={tsc(U"januario"),tsc(U"februario"),tsc(U"martio"),tsc(U"april"),tsc(U"maio"),tsc(U"junio"),tsc(U"julio"),tsc(U"augusto"),tsc(U"septembre"),tsc(U"octobre"),tsc(U"novembre"),tsc(U"decembre")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U"AM"),tsc(U"PM")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1sSyY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"Si"),.nostr=tsc(U"No")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.tel_dom_fmt=tsc(U"%a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"33")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s%t%h%t%e%t%r%N%z%t%T%N%c%N"),.country_name=tsc(U"Francia"),.country_post=tsc(U"F"),.country_ab2=tsc(U"FR"),.country_ab3=tsc(U"FRA"),.country_num=250,.country_car=tsc(U"F"),.country_isbn=tsc(U"979-10"),.lang_name=tsc(U"interlingua"),.lang_ab=tsc(U"ia"),.lang_term=tsc(U"ina"),.lang_lib=tsc(U"ina")},.measurement={.measurement=1}};


}
}

#include"../main.h"