#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Indonesian locale for Indonesia"),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Indonesian"),.territory=tsc("Indonesia"),.revision=tsc("1.0"),.date=tsc("2000-06-29")},.monetary={.int_curr_symbol=tsc("IDR "),.currency_symbol=tsc("Rp"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc("."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("Min"),tsc("Sen"),tsc("Sel"),tsc("Rab"),tsc("Kam"),tsc("Jum"),tsc("Sab")},.day={tsc("Minggu"),tsc("Senin"),tsc("Selasa"),tsc("Rabu"),tsc("Kamis"),tsc("Jumat"),tsc("Sabtu")},.abmon={tsc("Jan"),tsc("Feb"),tsc("Mar"),tsc("Apr"),tsc("Mei"),tsc("Jun"),tsc("Jul"),tsc("Agu"),tsc("Sep"),tsc("Okt"),tsc("Nov"),tsc("Des")},.mon={tsc("Januari"),tsc("Februari"),tsc("Maret"),tsc("April"),tsc("Mei"),tsc("Juni"),tsc("Juli"),tsc("Agustus"),tsc("September"),tsc("Oktober"),tsc("November"),tsc("Desember")},.d_t_fmt=tsc("%a %d %b %Y %r"),.d_fmt=tsc("%d//%m//%y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %r %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1}},.messages={.yesexpr=tsc("^[+1yY]"),.noexpr=tsc("^[-0tTnN]"),.yesstr=tsc("ya"),.nostr=tsc("tidak")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("001,008,007,009"),.int_prefix=tsc("62")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Indonesia"),.country_ab2=tsc("ID"),.country_ab3=tsc("IDN"),.country_num=360,.country_car=tsc("RI"),.lang_name=tsc("Indonesia"),.lang_ab=tsc("id"),.lang_term=tsc("ind"),.lang_lib=tsc("ind")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Indonesian locale for Indonesia"),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Indonesian"),.territory=tsc(L"Indonesia"),.revision=tsc(L"1.0"),.date=tsc(L"2000-06-29")},.monetary={.int_curr_symbol=tsc(L"IDR "),.currency_symbol=tsc(L"Rp"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"Min"),tsc(L"Sen"),tsc(L"Sel"),tsc(L"Rab"),tsc(L"Kam"),tsc(L"Jum"),tsc(L"Sab")},.day={tsc(L"Minggu"),tsc(L"Senin"),tsc(L"Selasa"),tsc(L"Rabu"),tsc(L"Kamis"),tsc(L"Jumat"),tsc(L"Sabtu")},.abmon={tsc(L"Jan"),tsc(L"Feb"),tsc(L"Mar"),tsc(L"Apr"),tsc(L"Mei"),tsc(L"Jun"),tsc(L"Jul"),tsc(L"Agu"),tsc(L"Sep"),tsc(L"Okt"),tsc(L"Nov"),tsc(L"Des")},.mon={tsc(L"Januari"),tsc(L"Februari"),tsc(L"Maret"),tsc(L"April"),tsc(L"Mei"),tsc(L"Juni"),tsc(L"Juli"),tsc(L"Agustus"),tsc(L"September"),tsc(L"Oktober"),tsc(L"November"),tsc(L"Desember")},.d_t_fmt=tsc(L"%a %d %b %Y %r"),.d_fmt=tsc(L"%d//%m//%y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %r %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(L"^[+1yY]"),.noexpr=tsc(L"^[-0tTnN]"),.yesstr=tsc(L"ya"),.nostr=tsc(L"tidak")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"001,008,007,009"),.int_prefix=tsc(L"62")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Indonesia"),.country_ab2=tsc(L"ID"),.country_ab3=tsc(L"IDN"),.country_num=360,.country_car=tsc(L"RI"),.lang_name=tsc(L"Indonesia"),.lang_ab=tsc(L"id"),.lang_term=tsc(L"ind"),.lang_lib=tsc(L"ind")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Indonesian locale for Indonesia"),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Indonesian"),.territory=tsc(u8"Indonesia"),.revision=tsc(u8"1.0"),.date=tsc(u8"2000-06-29")},.monetary={.int_curr_symbol=tsc(u8"IDR "),.currency_symbol=tsc(u8"Rp"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"Min"),tsc(u8"Sen"),tsc(u8"Sel"),tsc(u8"Rab"),tsc(u8"Kam"),tsc(u8"Jum"),tsc(u8"Sab")},.day={tsc(u8"Minggu"),tsc(u8"Senin"),tsc(u8"Selasa"),tsc(u8"Rabu"),tsc(u8"Kamis"),tsc(u8"Jumat"),tsc(u8"Sabtu")},.abmon={tsc(u8"Jan"),tsc(u8"Feb"),tsc(u8"Mar"),tsc(u8"Apr"),tsc(u8"Mei"),tsc(u8"Jun"),tsc(u8"Jul"),tsc(u8"Agu"),tsc(u8"Sep"),tsc(u8"Okt"),tsc(u8"Nov"),tsc(u8"Des")},.mon={tsc(u8"Januari"),tsc(u8"Februari"),tsc(u8"Maret"),tsc(u8"April"),tsc(u8"Mei"),tsc(u8"Juni"),tsc(u8"Juli"),tsc(u8"Agustus"),tsc(u8"September"),tsc(u8"Oktober"),tsc(u8"November"),tsc(u8"Desember")},.d_t_fmt=tsc(u8"%a %d %b %Y %r"),.d_fmt=tsc(u8"%d//%m//%y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %r %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u8"^[+1yY]"),.noexpr=tsc(u8"^[-0tTnN]"),.yesstr=tsc(u8"ya"),.nostr=tsc(u8"tidak")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"001,008,007,009"),.int_prefix=tsc(u8"62")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Indonesia"),.country_ab2=tsc(u8"ID"),.country_ab3=tsc(u8"IDN"),.country_num=360,.country_car=tsc(u8"RI"),.lang_name=tsc(u8"Indonesia"),.lang_ab=tsc(u8"id"),.lang_term=tsc(u8"ind"),.lang_lib=tsc(u8"ind")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Indonesian locale for Indonesia"),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Indonesian"),.territory=tsc(u"Indonesia"),.revision=tsc(u"1.0"),.date=tsc(u"2000-06-29")},.monetary={.int_curr_symbol=tsc(u"IDR "),.currency_symbol=tsc(u"Rp"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"Min"),tsc(u"Sen"),tsc(u"Sel"),tsc(u"Rab"),tsc(u"Kam"),tsc(u"Jum"),tsc(u"Sab")},.day={tsc(u"Minggu"),tsc(u"Senin"),tsc(u"Selasa"),tsc(u"Rabu"),tsc(u"Kamis"),tsc(u"Jumat"),tsc(u"Sabtu")},.abmon={tsc(u"Jan"),tsc(u"Feb"),tsc(u"Mar"),tsc(u"Apr"),tsc(u"Mei"),tsc(u"Jun"),tsc(u"Jul"),tsc(u"Agu"),tsc(u"Sep"),tsc(u"Okt"),tsc(u"Nov"),tsc(u"Des")},.mon={tsc(u"Januari"),tsc(u"Februari"),tsc(u"Maret"),tsc(u"April"),tsc(u"Mei"),tsc(u"Juni"),tsc(u"Juli"),tsc(u"Agustus"),tsc(u"September"),tsc(u"Oktober"),tsc(u"November"),tsc(u"Desember")},.d_t_fmt=tsc(u"%a %d %b %Y %r"),.d_fmt=tsc(u"%d//%m//%y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %r %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u"^[+1yY]"),.noexpr=tsc(u"^[-0tTnN]"),.yesstr=tsc(u"ya"),.nostr=tsc(u"tidak")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"001,008,007,009"),.int_prefix=tsc(u"62")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Indonesia"),.country_ab2=tsc(u"ID"),.country_ab3=tsc(u"IDN"),.country_num=360,.country_car=tsc(u"RI"),.lang_name=tsc(u"Indonesia"),.lang_ab=tsc(u"id"),.lang_term=tsc(u"ind"),.lang_lib=tsc(u"ind")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Indonesian locale for Indonesia"),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Indonesian"),.territory=tsc(U"Indonesia"),.revision=tsc(U"1.0"),.date=tsc(U"2000-06-29")},.monetary={.int_curr_symbol=tsc(U"IDR "),.currency_symbol=tsc(U"Rp"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"Min"),tsc(U"Sen"),tsc(U"Sel"),tsc(U"Rab"),tsc(U"Kam"),tsc(U"Jum"),tsc(U"Sab")},.day={tsc(U"Minggu"),tsc(U"Senin"),tsc(U"Selasa"),tsc(U"Rabu"),tsc(U"Kamis"),tsc(U"Jumat"),tsc(U"Sabtu")},.abmon={tsc(U"Jan"),tsc(U"Feb"),tsc(U"Mar"),tsc(U"Apr"),tsc(U"Mei"),tsc(U"Jun"),tsc(U"Jul"),tsc(U"Agu"),tsc(U"Sep"),tsc(U"Okt"),tsc(U"Nov"),tsc(U"Des")},.mon={tsc(U"Januari"),tsc(U"Februari"),tsc(U"Maret"),tsc(U"April"),tsc(U"Mei"),tsc(U"Juni"),tsc(U"Juli"),tsc(U"Agustus"),tsc(U"September"),tsc(U"Oktober"),tsc(U"November"),tsc(U"Desember")},.d_t_fmt=tsc(U"%a %d %b %Y %r"),.d_fmt=tsc(U"%d//%m//%y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %r %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(U"^[+1yY]"),.noexpr=tsc(U"^[-0tTnN]"),.yesstr=tsc(U"ya"),.nostr=tsc(U"tidak")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"001,008,007,009"),.int_prefix=tsc(U"62")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Indonesia"),.country_ab2=tsc(U"ID"),.country_ab3=tsc(U"IDN"),.country_num=360,.country_car=tsc(U"RI"),.lang_name=tsc(U"Indonesia"),.lang_ab=tsc(U"id"),.lang_term=tsc(U"ind"),.lang_lib=tsc(U"ind")},.measurement={.measurement=1}};


}
}

#include"../main.h"