#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Igbo locale for Nigeria"),.source=tsc("fast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("pablo@mandriva.com;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Igbo"),.territory=tsc("Nigeria"),.revision=tsc("0.2"),.date=tsc("2005-12-14")},.monetary={.int_curr_symbol=tsc("NGN "),.currency_symbol=tsc("₦"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("sọn"),tsc("mọn"),tsc("tuz"),tsc("wen"),tsc("tọs"),tsc("fra"),tsc("sat")},.day={tsc("sọnde"),tsc("mọnde"),tsc("tuzde"),tsc("wenzde"),tsc("tọsde"),tsc("fraịde"),tsc("satọde")},.abmon={tsc("Jen"),tsc("Feb"),tsc("Maa"),tsc("Epr"),tsc("Mee"),tsc("Juu"),tsc("Jul"),tsc("Ọgọ"),tsc("Sep"),tsc("Ọkt"),tsc("Nov"),tsc("Dis")},.mon={tsc("Jenụwarị"),tsc("Febrụwarị"),tsc("Maachị"),tsc("Eprel"),tsc("Mee"),tsc("Juun"),tsc("Julaị"),tsc("Ọgọọst"),tsc("Septemba"),tsc("Ọktoba"),tsc("Novemba"),tsc("Disemba")},.d_t_fmt=tsc("%A, %d %B %Y %T"),.d_fmt=tsc("%d//%m//%y"),.t_fmt=tsc("%r"),.t_fmt_ampm=tsc("%I:%M:%S %p"),.date_fmt=tsc("%A, %d %B %Y %T %Z"),.am_pm={tsc("AM"),tsc("PM")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1EeIiYy]"),.noexpr=tsc("^[-0MmNn]"),.yesstr=tsc("Eye"),.nostr=tsc("Mba")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.tel_dom_fmt=tsc("(%A) %l"),.int_select=tsc("009"),.int_prefix=tsc("234")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Naịjịrịa"),.country_ab2=tsc("NG"),.country_ab3=tsc("NGA"),.country_num=566,.country_car=tsc("WAN"),.country_isbn=tsc("978"),.lang_name=tsc("Asụsụ Igbo"),.lang_ab=tsc("ig"),.lang_term=tsc("ibo"),.lang_lib=tsc("ibo")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Igbo locale for Nigeria"),.source=tsc(L"fast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"pablo@mandriva.com;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Igbo"),.territory=tsc(L"Nigeria"),.revision=tsc(L"0.2"),.date=tsc(L"2005-12-14")},.monetary={.int_curr_symbol=tsc(L"NGN "),.currency_symbol=tsc(L"₦"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"sọn"),tsc(L"mọn"),tsc(L"tuz"),tsc(L"wen"),tsc(L"tọs"),tsc(L"fra"),tsc(L"sat")},.day={tsc(L"sọnde"),tsc(L"mọnde"),tsc(L"tuzde"),tsc(L"wenzde"),tsc(L"tọsde"),tsc(L"fraịde"),tsc(L"satọde")},.abmon={tsc(L"Jen"),tsc(L"Feb"),tsc(L"Maa"),tsc(L"Epr"),tsc(L"Mee"),tsc(L"Juu"),tsc(L"Jul"),tsc(L"Ọgọ"),tsc(L"Sep"),tsc(L"Ọkt"),tsc(L"Nov"),tsc(L"Dis")},.mon={tsc(L"Jenụwarị"),tsc(L"Febrụwarị"),tsc(L"Maachị"),tsc(L"Eprel"),tsc(L"Mee"),tsc(L"Juun"),tsc(L"Julaị"),tsc(L"Ọgọọst"),tsc(L"Septemba"),tsc(L"Ọktoba"),tsc(L"Novemba"),tsc(L"Disemba")},.d_t_fmt=tsc(L"%A, %d %B %Y %T"),.d_fmt=tsc(L"%d//%m//%y"),.t_fmt=tsc(L"%r"),.t_fmt_ampm=tsc(L"%I:%M:%S %p"),.date_fmt=tsc(L"%A, %d %B %Y %T %Z"),.am_pm={tsc(L"AM"),tsc(L"PM")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1EeIiYy]"),.noexpr=tsc(L"^[-0MmNn]"),.yesstr=tsc(L"Eye"),.nostr=tsc(L"Mba")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.tel_dom_fmt=tsc(L"(%A) %l"),.int_select=tsc(L"009"),.int_prefix=tsc(L"234")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Naịjịrịa"),.country_ab2=tsc(L"NG"),.country_ab3=tsc(L"NGA"),.country_num=566,.country_car=tsc(L"WAN"),.country_isbn=tsc(L"978"),.lang_name=tsc(L"Asụsụ Igbo"),.lang_ab=tsc(L"ig"),.lang_term=tsc(L"ibo"),.lang_lib=tsc(L"ibo")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Igbo locale for Nigeria"),.source=tsc(u8"fast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"pablo@mandriva.com;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Igbo"),.territory=tsc(u8"Nigeria"),.revision=tsc(u8"0.2"),.date=tsc(u8"2005-12-14")},.monetary={.int_curr_symbol=tsc(u8"NGN "),.currency_symbol=tsc(u8"₦"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"sọn"),tsc(u8"mọn"),tsc(u8"tuz"),tsc(u8"wen"),tsc(u8"tọs"),tsc(u8"fra"),tsc(u8"sat")},.day={tsc(u8"sọnde"),tsc(u8"mọnde"),tsc(u8"tuzde"),tsc(u8"wenzde"),tsc(u8"tọsde"),tsc(u8"fraịde"),tsc(u8"satọde")},.abmon={tsc(u8"Jen"),tsc(u8"Feb"),tsc(u8"Maa"),tsc(u8"Epr"),tsc(u8"Mee"),tsc(u8"Juu"),tsc(u8"Jul"),tsc(u8"Ọgọ"),tsc(u8"Sep"),tsc(u8"Ọkt"),tsc(u8"Nov"),tsc(u8"Dis")},.mon={tsc(u8"Jenụwarị"),tsc(u8"Febrụwarị"),tsc(u8"Maachị"),tsc(u8"Eprel"),tsc(u8"Mee"),tsc(u8"Juun"),tsc(u8"Julaị"),tsc(u8"Ọgọọst"),tsc(u8"Septemba"),tsc(u8"Ọktoba"),tsc(u8"Novemba"),tsc(u8"Disemba")},.d_t_fmt=tsc(u8"%A, %d %B %Y %T"),.d_fmt=tsc(u8"%d//%m//%y"),.t_fmt=tsc(u8"%r"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p"),.date_fmt=tsc(u8"%A, %d %B %Y %T %Z"),.am_pm={tsc(u8"AM"),tsc(u8"PM")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1EeIiYy]"),.noexpr=tsc(u8"^[-0MmNn]"),.yesstr=tsc(u8"Eye"),.nostr=tsc(u8"Mba")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.tel_dom_fmt=tsc(u8"(%A) %l"),.int_select=tsc(u8"009"),.int_prefix=tsc(u8"234")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Naịjịrịa"),.country_ab2=tsc(u8"NG"),.country_ab3=tsc(u8"NGA"),.country_num=566,.country_car=tsc(u8"WAN"),.country_isbn=tsc(u8"978"),.lang_name=tsc(u8"Asụsụ Igbo"),.lang_ab=tsc(u8"ig"),.lang_term=tsc(u8"ibo"),.lang_lib=tsc(u8"ibo")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Igbo locale for Nigeria"),.source=tsc(u"fast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"pablo@mandriva.com;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Igbo"),.territory=tsc(u"Nigeria"),.revision=tsc(u"0.2"),.date=tsc(u"2005-12-14")},.monetary={.int_curr_symbol=tsc(u"NGN "),.currency_symbol=tsc(u"₦"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"sọn"),tsc(u"mọn"),tsc(u"tuz"),tsc(u"wen"),tsc(u"tọs"),tsc(u"fra"),tsc(u"sat")},.day={tsc(u"sọnde"),tsc(u"mọnde"),tsc(u"tuzde"),tsc(u"wenzde"),tsc(u"tọsde"),tsc(u"fraịde"),tsc(u"satọde")},.abmon={tsc(u"Jen"),tsc(u"Feb"),tsc(u"Maa"),tsc(u"Epr"),tsc(u"Mee"),tsc(u"Juu"),tsc(u"Jul"),tsc(u"Ọgọ"),tsc(u"Sep"),tsc(u"Ọkt"),tsc(u"Nov"),tsc(u"Dis")},.mon={tsc(u"Jenụwarị"),tsc(u"Febrụwarị"),tsc(u"Maachị"),tsc(u"Eprel"),tsc(u"Mee"),tsc(u"Juun"),tsc(u"Julaị"),tsc(u"Ọgọọst"),tsc(u"Septemba"),tsc(u"Ọktoba"),tsc(u"Novemba"),tsc(u"Disemba")},.d_t_fmt=tsc(u"%A, %d %B %Y %T"),.d_fmt=tsc(u"%d//%m//%y"),.t_fmt=tsc(u"%r"),.t_fmt_ampm=tsc(u"%I:%M:%S %p"),.date_fmt=tsc(u"%A, %d %B %Y %T %Z"),.am_pm={tsc(u"AM"),tsc(u"PM")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1EeIiYy]"),.noexpr=tsc(u"^[-0MmNn]"),.yesstr=tsc(u"Eye"),.nostr=tsc(u"Mba")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.tel_dom_fmt=tsc(u"(%A) %l"),.int_select=tsc(u"009"),.int_prefix=tsc(u"234")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Naịjịrịa"),.country_ab2=tsc(u"NG"),.country_ab3=tsc(u"NGA"),.country_num=566,.country_car=tsc(u"WAN"),.country_isbn=tsc(u"978"),.lang_name=tsc(u"Asụsụ Igbo"),.lang_ab=tsc(u"ig"),.lang_term=tsc(u"ibo"),.lang_lib=tsc(u"ibo")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Igbo locale for Nigeria"),.source=tsc(U"fast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"pablo@mandriva.com;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Igbo"),.territory=tsc(U"Nigeria"),.revision=tsc(U"0.2"),.date=tsc(U"2005-12-14")},.monetary={.int_curr_symbol=tsc(U"NGN "),.currency_symbol=tsc(U"₦"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"sọn"),tsc(U"mọn"),tsc(U"tuz"),tsc(U"wen"),tsc(U"tọs"),tsc(U"fra"),tsc(U"sat")},.day={tsc(U"sọnde"),tsc(U"mọnde"),tsc(U"tuzde"),tsc(U"wenzde"),tsc(U"tọsde"),tsc(U"fraịde"),tsc(U"satọde")},.abmon={tsc(U"Jen"),tsc(U"Feb"),tsc(U"Maa"),tsc(U"Epr"),tsc(U"Mee"),tsc(U"Juu"),tsc(U"Jul"),tsc(U"Ọgọ"),tsc(U"Sep"),tsc(U"Ọkt"),tsc(U"Nov"),tsc(U"Dis")},.mon={tsc(U"Jenụwarị"),tsc(U"Febrụwarị"),tsc(U"Maachị"),tsc(U"Eprel"),tsc(U"Mee"),tsc(U"Juun"),tsc(U"Julaị"),tsc(U"Ọgọọst"),tsc(U"Septemba"),tsc(U"Ọktoba"),tsc(U"Novemba"),tsc(U"Disemba")},.d_t_fmt=tsc(U"%A, %d %B %Y %T"),.d_fmt=tsc(U"%d//%m//%y"),.t_fmt=tsc(U"%r"),.t_fmt_ampm=tsc(U"%I:%M:%S %p"),.date_fmt=tsc(U"%A, %d %B %Y %T %Z"),.am_pm={tsc(U"AM"),tsc(U"PM")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1EeIiYy]"),.noexpr=tsc(U"^[-0MmNn]"),.yesstr=tsc(U"Eye"),.nostr=tsc(U"Mba")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.tel_dom_fmt=tsc(U"(%A) %l"),.int_select=tsc(U"009"),.int_prefix=tsc(U"234")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Naịjịrịa"),.country_ab2=tsc(U"NG"),.country_ab3=tsc(U"NGA"),.country_num=566,.country_car=tsc(U"WAN"),.country_isbn=tsc(U"978"),.lang_name=tsc(U"Asụsụ Igbo"),.lang_ab=tsc(U"ig"),.lang_term=tsc(U"ibo"),.lang_lib=tsc(U"ibo")},.measurement={.measurement=1}};


}
}

#include"../main.h"