#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Kyrgyz Language Locale for Kyrgyzstan"),.source=tsc("Timur Jamakeev\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Pablo Saratxaga, Timur Jamakeev\t\t;\t\tfast_io"),.email=tsc("srtxg@mandrakesoft.com, ztimur@mail.ru;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Kyrgyz"),.territory=tsc("Kyrgyzstan"),.revision=tsc("0.2"),.date=tsc("2004-10-14")},.monetary={.int_curr_symbol=tsc("KGS "),.currency_symbol=tsc("сом"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("жк"),tsc("дш"),tsc("ше"),tsc("ша"),tsc("бш"),tsc("жм"),tsc("иш")},.day={tsc("жекшемби"),tsc("дүйшөмбү"),tsc("шейшемби"),tsc("шаршемби"),tsc("бейшемби"),tsc("жума"),tsc("ишемби")},.abmon={tsc("янв"),tsc("фев"),tsc("мар"),tsc("апр"),tsc("май"),tsc("июн"),tsc("июл"),tsc("авг"),tsc("сен"),tsc("окт"),tsc("ноя"),tsc("дек")},.mon={tsc("январь"),tsc("февраль"),tsc("март"),tsc("апрель"),tsc("май"),tsc("июнь"),tsc("июль"),tsc("август"),tsc("сентябрь"),tsc("октябрь"),tsc("ноябрь"),tsc("декабрь")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a, %e-%b %Y ж, %H:%M:%S %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1yYОо]"),.noexpr=tsc("^[-0nNЖж]"),.yesstr=tsc("ооба"),.nostr=tsc("жок")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("996")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Кыргызстан"),.country_ab2=tsc("KG"),.country_ab3=tsc("KGZ"),.country_num=417,.country_car=tsc("KS"),.lang_name=tsc("кыргызча"),.lang_ab=tsc("ky"),.lang_term=tsc("kir"),.lang_lib=tsc("kir")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Kyrgyz Language Locale for Kyrgyzstan"),.source=tsc(L"Timur Jamakeev\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Pablo Saratxaga, Timur Jamakeev\t\t;\t\tfast_io"),.email=tsc(L"srtxg@mandrakesoft.com, ztimur@mail.ru;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Kyrgyz"),.territory=tsc(L"Kyrgyzstan"),.revision=tsc(L"0.2"),.date=tsc(L"2004-10-14")},.monetary={.int_curr_symbol=tsc(L"KGS "),.currency_symbol=tsc(L"сом"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"жк"),tsc(L"дш"),tsc(L"ше"),tsc(L"ша"),tsc(L"бш"),tsc(L"жм"),tsc(L"иш")},.day={tsc(L"жекшемби"),tsc(L"дүйшөмбү"),tsc(L"шейшемби"),tsc(L"шаршемби"),tsc(L"бейшемби"),tsc(L"жума"),tsc(L"ишемби")},.abmon={tsc(L"янв"),tsc(L"фев"),tsc(L"мар"),tsc(L"апр"),tsc(L"май"),tsc(L"июн"),tsc(L"июл"),tsc(L"авг"),tsc(L"сен"),tsc(L"окт"),tsc(L"ноя"),tsc(L"дек")},.mon={tsc(L"январь"),tsc(L"февраль"),tsc(L"март"),tsc(L"апрель"),tsc(L"май"),tsc(L"июнь"),tsc(L"июль"),tsc(L"август"),tsc(L"сентябрь"),tsc(L"октябрь"),tsc(L"ноябрь"),tsc(L"декабрь")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a, %e-%b %Y ж, %H:%M:%S %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1yYОо]"),.noexpr=tsc(L"^[-0nNЖж]"),.yesstr=tsc(L"ооба"),.nostr=tsc(L"жок")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"996")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Кыргызстан"),.country_ab2=tsc(L"KG"),.country_ab3=tsc(L"KGZ"),.country_num=417,.country_car=tsc(L"KS"),.lang_name=tsc(L"кыргызча"),.lang_ab=tsc(L"ky"),.lang_term=tsc(L"kir"),.lang_lib=tsc(L"kir")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Kyrgyz Language Locale for Kyrgyzstan"),.source=tsc(u8"Timur Jamakeev\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Pablo Saratxaga, Timur Jamakeev\t\t;\t\tfast_io"),.email=tsc(u8"srtxg@mandrakesoft.com, ztimur@mail.ru;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Kyrgyz"),.territory=tsc(u8"Kyrgyzstan"),.revision=tsc(u8"0.2"),.date=tsc(u8"2004-10-14")},.monetary={.int_curr_symbol=tsc(u8"KGS "),.currency_symbol=tsc(u8"сом"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"жк"),tsc(u8"дш"),tsc(u8"ше"),tsc(u8"ша"),tsc(u8"бш"),tsc(u8"жм"),tsc(u8"иш")},.day={tsc(u8"жекшемби"),tsc(u8"дүйшөмбү"),tsc(u8"шейшемби"),tsc(u8"шаршемби"),tsc(u8"бейшемби"),tsc(u8"жума"),tsc(u8"ишемби")},.abmon={tsc(u8"янв"),tsc(u8"фев"),tsc(u8"мар"),tsc(u8"апр"),tsc(u8"май"),tsc(u8"июн"),tsc(u8"июл"),tsc(u8"авг"),tsc(u8"сен"),tsc(u8"окт"),tsc(u8"ноя"),tsc(u8"дек")},.mon={tsc(u8"январь"),tsc(u8"февраль"),tsc(u8"март"),tsc(u8"апрель"),tsc(u8"май"),tsc(u8"июнь"),tsc(u8"июль"),tsc(u8"август"),tsc(u8"сентябрь"),tsc(u8"октябрь"),tsc(u8"ноябрь"),tsc(u8"декабрь")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a, %e-%b %Y ж, %H:%M:%S %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1yYОо]"),.noexpr=tsc(u8"^[-0nNЖж]"),.yesstr=tsc(u8"ооба"),.nostr=tsc(u8"жок")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"996")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Кыргызстан"),.country_ab2=tsc(u8"KG"),.country_ab3=tsc(u8"KGZ"),.country_num=417,.country_car=tsc(u8"KS"),.lang_name=tsc(u8"кыргызча"),.lang_ab=tsc(u8"ky"),.lang_term=tsc(u8"kir"),.lang_lib=tsc(u8"kir")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Kyrgyz Language Locale for Kyrgyzstan"),.source=tsc(u"Timur Jamakeev\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Pablo Saratxaga, Timur Jamakeev\t\t;\t\tfast_io"),.email=tsc(u"srtxg@mandrakesoft.com, ztimur@mail.ru;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Kyrgyz"),.territory=tsc(u"Kyrgyzstan"),.revision=tsc(u"0.2"),.date=tsc(u"2004-10-14")},.monetary={.int_curr_symbol=tsc(u"KGS "),.currency_symbol=tsc(u"сом"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"жк"),tsc(u"дш"),tsc(u"ше"),tsc(u"ша"),tsc(u"бш"),tsc(u"жм"),tsc(u"иш")},.day={tsc(u"жекшемби"),tsc(u"дүйшөмбү"),tsc(u"шейшемби"),tsc(u"шаршемби"),tsc(u"бейшемби"),tsc(u"жума"),tsc(u"ишемби")},.abmon={tsc(u"янв"),tsc(u"фев"),tsc(u"мар"),tsc(u"апр"),tsc(u"май"),tsc(u"июн"),tsc(u"июл"),tsc(u"авг"),tsc(u"сен"),tsc(u"окт"),tsc(u"ноя"),tsc(u"дек")},.mon={tsc(u"январь"),tsc(u"февраль"),tsc(u"март"),tsc(u"апрель"),tsc(u"май"),tsc(u"июнь"),tsc(u"июль"),tsc(u"август"),tsc(u"сентябрь"),tsc(u"октябрь"),tsc(u"ноябрь"),tsc(u"декабрь")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a, %e-%b %Y ж, %H:%M:%S %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1yYОо]"),.noexpr=tsc(u"^[-0nNЖж]"),.yesstr=tsc(u"ооба"),.nostr=tsc(u"жок")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"996")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Кыргызстан"),.country_ab2=tsc(u"KG"),.country_ab3=tsc(u"KGZ"),.country_num=417,.country_car=tsc(u"KS"),.lang_name=tsc(u"кыргызча"),.lang_ab=tsc(u"ky"),.lang_term=tsc(u"kir"),.lang_lib=tsc(u"kir")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Kyrgyz Language Locale for Kyrgyzstan"),.source=tsc(U"Timur Jamakeev\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Pablo Saratxaga, Timur Jamakeev\t\t;\t\tfast_io"),.email=tsc(U"srtxg@mandrakesoft.com, ztimur@mail.ru;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Kyrgyz"),.territory=tsc(U"Kyrgyzstan"),.revision=tsc(U"0.2"),.date=tsc(U"2004-10-14")},.monetary={.int_curr_symbol=tsc(U"KGS "),.currency_symbol=tsc(U"сом"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"жк"),tsc(U"дш"),tsc(U"ше"),tsc(U"ша"),tsc(U"бш"),tsc(U"жм"),tsc(U"иш")},.day={tsc(U"жекшемби"),tsc(U"дүйшөмбү"),tsc(U"шейшемби"),tsc(U"шаршемби"),tsc(U"бейшемби"),tsc(U"жума"),tsc(U"ишемби")},.abmon={tsc(U"янв"),tsc(U"фев"),tsc(U"мар"),tsc(U"апр"),tsc(U"май"),tsc(U"июн"),tsc(U"июл"),tsc(U"авг"),tsc(U"сен"),tsc(U"окт"),tsc(U"ноя"),tsc(U"дек")},.mon={tsc(U"январь"),tsc(U"февраль"),tsc(U"март"),tsc(U"апрель"),tsc(U"май"),tsc(U"июнь"),tsc(U"июль"),tsc(U"август"),tsc(U"сентябрь"),tsc(U"октябрь"),tsc(U"ноябрь"),tsc(U"декабрь")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a, %e-%b %Y ж, %H:%M:%S %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1yYОо]"),.noexpr=tsc(U"^[-0nNЖж]"),.yesstr=tsc(U"ооба"),.nostr=tsc(U"жок")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"996")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Кыргызстан"),.country_ab2=tsc(U"KG"),.country_ab3=tsc(U"KGZ"),.country_num=417,.country_car=tsc(U"KS"),.lang_name=tsc(U"кыргызча"),.lang_ab=tsc(U"ky"),.lang_term=tsc(U"kir"),.lang_lib=tsc(U"kir")},.measurement={.measurement=1}};


}
}

#include"../main.h"