#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Latvian locale for Latvia"),.source=tsc("Latvian Standard LVS 24-93\t\t;\t\tfast_io"),.address=tsc("LU MII, Rainis boul. 29, LV-1459 Riga, Latvia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Latvian"),.territory=tsc("Latvia"),.revision=tsc("1.0"),.date=tsc("2000-06-29")},.monetary={.int_curr_symbol=tsc("EUR "),.currency_symbol=tsc("€"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=3,.n_sign_posn=3},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("Sv"),tsc("P "),tsc("O "),tsc("T "),tsc("C "),tsc("Pk"),tsc("S ")},.day={tsc("svētdiena"),tsc("pirmdiena"),tsc("otrdiena"),tsc("trešdiena"),tsc("ceturtdiena"),tsc("piektdiena"),tsc("sestdiena")},.abmon={tsc("jan"),tsc("feb"),tsc("mar"),tsc("apr"),tsc("mai"),tsc("jūn"),tsc("jūl"),tsc("aug"),tsc("sep"),tsc("okt"),tsc("nov"),tsc("dec")},.mon={tsc("janvāris"),tsc("februāris"),tsc("marts"),tsc("aprīlis"),tsc("maijs"),tsc("jūnijs"),tsc("jūlijs"),tsc("augusts"),tsc("septembris"),tsc("oktobris"),tsc("novembris"),tsc("decembris")},.d_t_fmt=tsc("%A, %Y. gada %e. %B, %H:%M:%S"),.d_fmt=tsc("%Y.%m.%d."),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%A, %Y. gada %e. %B, %H:%M:%S %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1JjYy]"),.noexpr=tsc("^[-0Nn]"),.yesstr=tsc("jā"),.nostr=tsc("nē")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("371")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Latvija"),.country_ab2=tsc("LV"),.country_ab3=tsc("LVA"),.country_num=428,.country_car=tsc("LV"),.lang_name=tsc("latviešu"),.lang_ab=tsc("lv"),.lang_term=tsc("lav"),.lang_lib=tsc("lav")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Latvian locale for Latvia"),.source=tsc(L"Latvian Standard LVS 24-93\t\t;\t\tfast_io"),.address=tsc(L"LU MII, Rainis boul. 29, LV-1459 Riga, Latvia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Latvian"),.territory=tsc(L"Latvia"),.revision=tsc(L"1.0"),.date=tsc(L"2000-06-29")},.monetary={.int_curr_symbol=tsc(L"EUR "),.currency_symbol=tsc(L"€"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=3,.n_sign_posn=3},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"Sv"),tsc(L"P "),tsc(L"O "),tsc(L"T "),tsc(L"C "),tsc(L"Pk"),tsc(L"S ")},.day={tsc(L"svētdiena"),tsc(L"pirmdiena"),tsc(L"otrdiena"),tsc(L"trešdiena"),tsc(L"ceturtdiena"),tsc(L"piektdiena"),tsc(L"sestdiena")},.abmon={tsc(L"jan"),tsc(L"feb"),tsc(L"mar"),tsc(L"apr"),tsc(L"mai"),tsc(L"jūn"),tsc(L"jūl"),tsc(L"aug"),tsc(L"sep"),tsc(L"okt"),tsc(L"nov"),tsc(L"dec")},.mon={tsc(L"janvāris"),tsc(L"februāris"),tsc(L"marts"),tsc(L"aprīlis"),tsc(L"maijs"),tsc(L"jūnijs"),tsc(L"jūlijs"),tsc(L"augusts"),tsc(L"septembris"),tsc(L"oktobris"),tsc(L"novembris"),tsc(L"decembris")},.d_t_fmt=tsc(L"%A, %Y. gada %e. %B, %H:%M:%S"),.d_fmt=tsc(L"%Y.%m.%d."),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%A, %Y. gada %e. %B, %H:%M:%S %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1JjYy]"),.noexpr=tsc(L"^[-0Nn]"),.yesstr=tsc(L"jā"),.nostr=tsc(L"nē")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"371")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Latvija"),.country_ab2=tsc(L"LV"),.country_ab3=tsc(L"LVA"),.country_num=428,.country_car=tsc(L"LV"),.lang_name=tsc(L"latviešu"),.lang_ab=tsc(L"lv"),.lang_term=tsc(L"lav"),.lang_lib=tsc(L"lav")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Latvian locale for Latvia"),.source=tsc(u8"Latvian Standard LVS 24-93\t\t;\t\tfast_io"),.address=tsc(u8"LU MII, Rainis boul. 29, LV-1459 Riga, Latvia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Latvian"),.territory=tsc(u8"Latvia"),.revision=tsc(u8"1.0"),.date=tsc(u8"2000-06-29")},.monetary={.int_curr_symbol=tsc(u8"EUR "),.currency_symbol=tsc(u8"€"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=3,.n_sign_posn=3},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"Sv"),tsc(u8"P "),tsc(u8"O "),tsc(u8"T "),tsc(u8"C "),tsc(u8"Pk"),tsc(u8"S ")},.day={tsc(u8"svētdiena"),tsc(u8"pirmdiena"),tsc(u8"otrdiena"),tsc(u8"trešdiena"),tsc(u8"ceturtdiena"),tsc(u8"piektdiena"),tsc(u8"sestdiena")},.abmon={tsc(u8"jan"),tsc(u8"feb"),tsc(u8"mar"),tsc(u8"apr"),tsc(u8"mai"),tsc(u8"jūn"),tsc(u8"jūl"),tsc(u8"aug"),tsc(u8"sep"),tsc(u8"okt"),tsc(u8"nov"),tsc(u8"dec")},.mon={tsc(u8"janvāris"),tsc(u8"februāris"),tsc(u8"marts"),tsc(u8"aprīlis"),tsc(u8"maijs"),tsc(u8"jūnijs"),tsc(u8"jūlijs"),tsc(u8"augusts"),tsc(u8"septembris"),tsc(u8"oktobris"),tsc(u8"novembris"),tsc(u8"decembris")},.d_t_fmt=tsc(u8"%A, %Y. gada %e. %B, %H:%M:%S"),.d_fmt=tsc(u8"%Y.%m.%d."),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%A, %Y. gada %e. %B, %H:%M:%S %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1JjYy]"),.noexpr=tsc(u8"^[-0Nn]"),.yesstr=tsc(u8"jā"),.nostr=tsc(u8"nē")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"371")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Latvija"),.country_ab2=tsc(u8"LV"),.country_ab3=tsc(u8"LVA"),.country_num=428,.country_car=tsc(u8"LV"),.lang_name=tsc(u8"latviešu"),.lang_ab=tsc(u8"lv"),.lang_term=tsc(u8"lav"),.lang_lib=tsc(u8"lav")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Latvian locale for Latvia"),.source=tsc(u"Latvian Standard LVS 24-93\t\t;\t\tfast_io"),.address=tsc(u"LU MII, Rainis boul. 29, LV-1459 Riga, Latvia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Latvian"),.territory=tsc(u"Latvia"),.revision=tsc(u"1.0"),.date=tsc(u"2000-06-29")},.monetary={.int_curr_symbol=tsc(u"EUR "),.currency_symbol=tsc(u"€"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=3,.n_sign_posn=3},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"Sv"),tsc(u"P "),tsc(u"O "),tsc(u"T "),tsc(u"C "),tsc(u"Pk"),tsc(u"S ")},.day={tsc(u"svētdiena"),tsc(u"pirmdiena"),tsc(u"otrdiena"),tsc(u"trešdiena"),tsc(u"ceturtdiena"),tsc(u"piektdiena"),tsc(u"sestdiena")},.abmon={tsc(u"jan"),tsc(u"feb"),tsc(u"mar"),tsc(u"apr"),tsc(u"mai"),tsc(u"jūn"),tsc(u"jūl"),tsc(u"aug"),tsc(u"sep"),tsc(u"okt"),tsc(u"nov"),tsc(u"dec")},.mon={tsc(u"janvāris"),tsc(u"februāris"),tsc(u"marts"),tsc(u"aprīlis"),tsc(u"maijs"),tsc(u"jūnijs"),tsc(u"jūlijs"),tsc(u"augusts"),tsc(u"septembris"),tsc(u"oktobris"),tsc(u"novembris"),tsc(u"decembris")},.d_t_fmt=tsc(u"%A, %Y. gada %e. %B, %H:%M:%S"),.d_fmt=tsc(u"%Y.%m.%d."),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%A, %Y. gada %e. %B, %H:%M:%S %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1JjYy]"),.noexpr=tsc(u"^[-0Nn]"),.yesstr=tsc(u"jā"),.nostr=tsc(u"nē")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"371")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Latvija"),.country_ab2=tsc(u"LV"),.country_ab3=tsc(u"LVA"),.country_num=428,.country_car=tsc(u"LV"),.lang_name=tsc(u"latviešu"),.lang_ab=tsc(u"lv"),.lang_term=tsc(u"lav"),.lang_lib=tsc(u"lav")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Latvian locale for Latvia"),.source=tsc(U"Latvian Standard LVS 24-93\t\t;\t\tfast_io"),.address=tsc(U"LU MII, Rainis boul. 29, LV-1459 Riga, Latvia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Latvian"),.territory=tsc(U"Latvia"),.revision=tsc(U"1.0"),.date=tsc(U"2000-06-29")},.monetary={.int_curr_symbol=tsc(U"EUR "),.currency_symbol=tsc(U"€"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=3,.n_sign_posn=3},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"Sv"),tsc(U"P "),tsc(U"O "),tsc(U"T "),tsc(U"C "),tsc(U"Pk"),tsc(U"S ")},.day={tsc(U"svētdiena"),tsc(U"pirmdiena"),tsc(U"otrdiena"),tsc(U"trešdiena"),tsc(U"ceturtdiena"),tsc(U"piektdiena"),tsc(U"sestdiena")},.abmon={tsc(U"jan"),tsc(U"feb"),tsc(U"mar"),tsc(U"apr"),tsc(U"mai"),tsc(U"jūn"),tsc(U"jūl"),tsc(U"aug"),tsc(U"sep"),tsc(U"okt"),tsc(U"nov"),tsc(U"dec")},.mon={tsc(U"janvāris"),tsc(U"februāris"),tsc(U"marts"),tsc(U"aprīlis"),tsc(U"maijs"),tsc(U"jūnijs"),tsc(U"jūlijs"),tsc(U"augusts"),tsc(U"septembris"),tsc(U"oktobris"),tsc(U"novembris"),tsc(U"decembris")},.d_t_fmt=tsc(U"%A, %Y. gada %e. %B, %H:%M:%S"),.d_fmt=tsc(U"%Y.%m.%d."),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%A, %Y. gada %e. %B, %H:%M:%S %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1JjYy]"),.noexpr=tsc(U"^[-0Nn]"),.yesstr=tsc(U"jā"),.nostr=tsc(U"nē")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"371")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Latvija"),.country_ab2=tsc(U"LV"),.country_ab3=tsc(U"LVA"),.country_num=428,.country_car=tsc(U"LV"),.lang_name=tsc(U"latviešu"),.lang_ab=tsc(U"lv"),.lang_term=tsc(U"lav"),.lang_lib=tsc(U"lav")},.measurement={.measurement=1}};


}
}

#include"../main.h"