#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t monetary_mon_grouping_storage[]{3,2};

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Maithili language locale for India"),.source=tsc("Maithili Computing Research Center, Pune, India\t\t;\t\tfast_io"),.address=tsc("B-3/302, Lunkad Daffodills, Viman Nagar, Pune, India\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("rajeshkajha@yahoo.com,akhilesh.k@samusng.com;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Maithili"),.territory=tsc("India"),.revision=tsc("1.1"),.date=tsc("2017-07-24")},.monetary={.int_curr_symbol=tsc("INR "),.currency_symbol=tsc("₹"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("रवि"),tsc("सोम"),tsc("मंगल"),tsc("बुध"),tsc("बृहस्पती"),tsc("शुक्र"),tsc("शनी")},.day={tsc("रविदिन"),tsc("सोमदिन"),tsc("मंगलदिन"),tsc("बुधदिन"),tsc("बृहस्पतीदिन"),tsc("शुक्रदिन"),tsc("शनीदिन")},.abmon={tsc("बैसाख"),tsc("जेठ"),tsc("अषाढ़"),tsc("सावोन"),tsc("भादो"),tsc("आसिन"),tsc("कातिक"),tsc("अगहन"),tsc("पूस"),tsc("माघ"),tsc("फागुन"),tsc("चैति")},.mon={tsc("बैसाख"),tsc("जेठ"),tsc("अषाढ़"),tsc("सावोन"),tsc("भादो"),tsc("आसिन"),tsc("कातिक"),tsc("अगहन"),tsc("पूस"),tsc("माघ"),tsc("फागुन"),tsc("चैति")},.d_t_fmt=tsc("%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc("%-d//%-m//%y"),.t_fmt=tsc("%I:%M:%S %p %Z"),.t_fmt_ampm=tsc("%I:%M:%S %p %Z"),.date_fmt=tsc("%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc("पूर्वाह्न"),tsc("अपराह्न")},.week={7,19971130,1}},.messages={.yesexpr=tsc("^[+1yYह]"),.noexpr=tsc("^[-0nNन]"),.yesstr=tsc("हाँ"),.nostr=tsc("नहीं")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c ;%a ;%l"),.int_select=tsc("00"),.int_prefix=tsc("91")},.name={.name_fmt=tsc("%p%t%f%t%g"),.name_gen=tsc(""),.name_miss=tsc("कुमारी"),.name_mr=tsc("श्रीमान्"),.name_mrs=tsc("श्रीमती"),.name_ms=tsc("सुश्री")},.address={.postal_fmt=tsc("%z%c%T%s%b%e%r"),.country_name=tsc("भारत"),.country_ab2=tsc("IN"),.country_ab3=tsc("IND"),.country_num=356,.country_car=tsc("IND"),.lang_name=tsc("मैथिली"),.lang_term=tsc("mai"),.lang_lib=tsc("mai")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Maithili language locale for India"),.source=tsc(L"Maithili Computing Research Center, Pune, India\t\t;\t\tfast_io"),.address=tsc(L"B-3/302, Lunkad Daffodills, Viman Nagar, Pune, India\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"rajeshkajha@yahoo.com,akhilesh.k@samusng.com;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Maithili"),.territory=tsc(L"India"),.revision=tsc(L"1.1"),.date=tsc(L"2017-07-24")},.monetary={.int_curr_symbol=tsc(L"INR "),.currency_symbol=tsc(L"₹"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"रवि"),tsc(L"सोम"),tsc(L"मंगल"),tsc(L"बुध"),tsc(L"बृहस्पती"),tsc(L"शुक्र"),tsc(L"शनी")},.day={tsc(L"रविदिन"),tsc(L"सोमदिन"),tsc(L"मंगलदिन"),tsc(L"बुधदिन"),tsc(L"बृहस्पतीदिन"),tsc(L"शुक्रदिन"),tsc(L"शनीदिन")},.abmon={tsc(L"बैसाख"),tsc(L"जेठ"),tsc(L"अषाढ़"),tsc(L"सावोन"),tsc(L"भादो"),tsc(L"आसिन"),tsc(L"कातिक"),tsc(L"अगहन"),tsc(L"पूस"),tsc(L"माघ"),tsc(L"फागुन"),tsc(L"चैति")},.mon={tsc(L"बैसाख"),tsc(L"जेठ"),tsc(L"अषाढ़"),tsc(L"सावोन"),tsc(L"भादो"),tsc(L"आसिन"),tsc(L"कातिक"),tsc(L"अगहन"),tsc(L"पूस"),tsc(L"माघ"),tsc(L"फागुन"),tsc(L"चैति")},.d_t_fmt=tsc(L"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(L"%-d//%-m//%y"),.t_fmt=tsc(L"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(L"%I:%M:%S %p %Z"),.date_fmt=tsc(L"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(L"पूर्वाह्न"),tsc(L"अपराह्न")},.week={7,19971130,1}},.messages={.yesexpr=tsc(L"^[+1yYह]"),.noexpr=tsc(L"^[-0nNन]"),.yesstr=tsc(L"हाँ"),.nostr=tsc(L"नहीं")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c ;%a ;%l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"91")},.name={.name_fmt=tsc(L"%p%t%f%t%g"),.name_gen=tsc(L""),.name_miss=tsc(L"कुमारी"),.name_mr=tsc(L"श्रीमान्"),.name_mrs=tsc(L"श्रीमती"),.name_ms=tsc(L"सुश्री")},.address={.postal_fmt=tsc(L"%z%c%T%s%b%e%r"),.country_name=tsc(L"भारत"),.country_ab2=tsc(L"IN"),.country_ab3=tsc(L"IND"),.country_num=356,.country_car=tsc(L"IND"),.lang_name=tsc(L"मैथिली"),.lang_term=tsc(L"mai"),.lang_lib=tsc(L"mai")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Maithili language locale for India"),.source=tsc(u8"Maithili Computing Research Center, Pune, India\t\t;\t\tfast_io"),.address=tsc(u8"B-3/302, Lunkad Daffodills, Viman Nagar, Pune, India\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"rajeshkajha@yahoo.com,akhilesh.k@samusng.com;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Maithili"),.territory=tsc(u8"India"),.revision=tsc(u8"1.1"),.date=tsc(u8"2017-07-24")},.monetary={.int_curr_symbol=tsc(u8"INR "),.currency_symbol=tsc(u8"₹"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"रवि"),tsc(u8"सोम"),tsc(u8"मंगल"),tsc(u8"बुध"),tsc(u8"बृहस्पती"),tsc(u8"शुक्र"),tsc(u8"शनी")},.day={tsc(u8"रविदिन"),tsc(u8"सोमदिन"),tsc(u8"मंगलदिन"),tsc(u8"बुधदिन"),tsc(u8"बृहस्पतीदिन"),tsc(u8"शुक्रदिन"),tsc(u8"शनीदिन")},.abmon={tsc(u8"बैसाख"),tsc(u8"जेठ"),tsc(u8"अषाढ़"),tsc(u8"सावोन"),tsc(u8"भादो"),tsc(u8"आसिन"),tsc(u8"कातिक"),tsc(u8"अगहन"),tsc(u8"पूस"),tsc(u8"माघ"),tsc(u8"फागुन"),tsc(u8"चैति")},.mon={tsc(u8"बैसाख"),tsc(u8"जेठ"),tsc(u8"अषाढ़"),tsc(u8"सावोन"),tsc(u8"भादो"),tsc(u8"आसिन"),tsc(u8"कातिक"),tsc(u8"अगहन"),tsc(u8"पूस"),tsc(u8"माघ"),tsc(u8"फागुन"),tsc(u8"चैति")},.d_t_fmt=tsc(u8"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(u8"%-d//%-m//%y"),.t_fmt=tsc(u8"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p %Z"),.date_fmt=tsc(u8"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(u8"पूर्वाह्न"),tsc(u8"अपराह्न")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u8"^[+1yYह]"),.noexpr=tsc(u8"^[-0nNन]"),.yesstr=tsc(u8"हाँ"),.nostr=tsc(u8"नहीं")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c ;%a ;%l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"91")},.name={.name_fmt=tsc(u8"%p%t%f%t%g"),.name_gen=tsc(u8""),.name_miss=tsc(u8"कुमारी"),.name_mr=tsc(u8"श्रीमान्"),.name_mrs=tsc(u8"श्रीमती"),.name_ms=tsc(u8"सुश्री")},.address={.postal_fmt=tsc(u8"%z%c%T%s%b%e%r"),.country_name=tsc(u8"भारत"),.country_ab2=tsc(u8"IN"),.country_ab3=tsc(u8"IND"),.country_num=356,.country_car=tsc(u8"IND"),.lang_name=tsc(u8"मैथिली"),.lang_term=tsc(u8"mai"),.lang_lib=tsc(u8"mai")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Maithili language locale for India"),.source=tsc(u"Maithili Computing Research Center, Pune, India\t\t;\t\tfast_io"),.address=tsc(u"B-3/302, Lunkad Daffodills, Viman Nagar, Pune, India\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"rajeshkajha@yahoo.com,akhilesh.k@samusng.com;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Maithili"),.territory=tsc(u"India"),.revision=tsc(u"1.1"),.date=tsc(u"2017-07-24")},.monetary={.int_curr_symbol=tsc(u"INR "),.currency_symbol=tsc(u"₹"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"रवि"),tsc(u"सोम"),tsc(u"मंगल"),tsc(u"बुध"),tsc(u"बृहस्पती"),tsc(u"शुक्र"),tsc(u"शनी")},.day={tsc(u"रविदिन"),tsc(u"सोमदिन"),tsc(u"मंगलदिन"),tsc(u"बुधदिन"),tsc(u"बृहस्पतीदिन"),tsc(u"शुक्रदिन"),tsc(u"शनीदिन")},.abmon={tsc(u"बैसाख"),tsc(u"जेठ"),tsc(u"अषाढ़"),tsc(u"सावोन"),tsc(u"भादो"),tsc(u"आसिन"),tsc(u"कातिक"),tsc(u"अगहन"),tsc(u"पूस"),tsc(u"माघ"),tsc(u"फागुन"),tsc(u"चैति")},.mon={tsc(u"बैसाख"),tsc(u"जेठ"),tsc(u"अषाढ़"),tsc(u"सावोन"),tsc(u"भादो"),tsc(u"आसिन"),tsc(u"कातिक"),tsc(u"अगहन"),tsc(u"पूस"),tsc(u"माघ"),tsc(u"फागुन"),tsc(u"चैति")},.d_t_fmt=tsc(u"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(u"%-d//%-m//%y"),.t_fmt=tsc(u"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(u"%I:%M:%S %p %Z"),.date_fmt=tsc(u"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(u"पूर्वाह्न"),tsc(u"अपराह्न")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u"^[+1yYह]"),.noexpr=tsc(u"^[-0nNन]"),.yesstr=tsc(u"हाँ"),.nostr=tsc(u"नहीं")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c ;%a ;%l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"91")},.name={.name_fmt=tsc(u"%p%t%f%t%g"),.name_gen=tsc(u""),.name_miss=tsc(u"कुमारी"),.name_mr=tsc(u"श्रीमान्"),.name_mrs=tsc(u"श्रीमती"),.name_ms=tsc(u"सुश्री")},.address={.postal_fmt=tsc(u"%z%c%T%s%b%e%r"),.country_name=tsc(u"भारत"),.country_ab2=tsc(u"IN"),.country_ab3=tsc(u"IND"),.country_num=356,.country_car=tsc(u"IND"),.lang_name=tsc(u"मैथिली"),.lang_term=tsc(u"mai"),.lang_lib=tsc(u"mai")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Maithili language locale for India"),.source=tsc(U"Maithili Computing Research Center, Pune, India\t\t;\t\tfast_io"),.address=tsc(U"B-3/302, Lunkad Daffodills, Viman Nagar, Pune, India\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"rajeshkajha@yahoo.com,akhilesh.k@samusng.com;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Maithili"),.territory=tsc(U"India"),.revision=tsc(U"1.1"),.date=tsc(U"2017-07-24")},.monetary={.int_curr_symbol=tsc(U"INR "),.currency_symbol=tsc(U"₹"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"रवि"),tsc(U"सोम"),tsc(U"मंगल"),tsc(U"बुध"),tsc(U"बृहस्पती"),tsc(U"शुक्र"),tsc(U"शनी")},.day={tsc(U"रविदिन"),tsc(U"सोमदिन"),tsc(U"मंगलदिन"),tsc(U"बुधदिन"),tsc(U"बृहस्पतीदिन"),tsc(U"शुक्रदिन"),tsc(U"शनीदिन")},.abmon={tsc(U"बैसाख"),tsc(U"जेठ"),tsc(U"अषाढ़"),tsc(U"सावोन"),tsc(U"भादो"),tsc(U"आसिन"),tsc(U"कातिक"),tsc(U"अगहन"),tsc(U"पूस"),tsc(U"माघ"),tsc(U"फागुन"),tsc(U"चैति")},.mon={tsc(U"बैसाख"),tsc(U"जेठ"),tsc(U"अषाढ़"),tsc(U"सावोन"),tsc(U"भादो"),tsc(U"आसिन"),tsc(U"कातिक"),tsc(U"अगहन"),tsc(U"पूस"),tsc(U"माघ"),tsc(U"फागुन"),tsc(U"चैति")},.d_t_fmt=tsc(U"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(U"%-d//%-m//%y"),.t_fmt=tsc(U"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(U"%I:%M:%S %p %Z"),.date_fmt=tsc(U"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(U"पूर्वाह्न"),tsc(U"अपराह्न")},.week={7,19971130,1}},.messages={.yesexpr=tsc(U"^[+1yYह]"),.noexpr=tsc(U"^[-0nNन]"),.yesstr=tsc(U"हाँ"),.nostr=tsc(U"नहीं")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c ;%a ;%l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"91")},.name={.name_fmt=tsc(U"%p%t%f%t%g"),.name_gen=tsc(U""),.name_miss=tsc(U"कुमारी"),.name_mr=tsc(U"श्रीमान्"),.name_mrs=tsc(U"श्रीमती"),.name_ms=tsc(U"सुश्री")},.address={.postal_fmt=tsc(U"%z%c%T%s%b%e%r"),.country_name=tsc(U"भारत"),.country_ab2=tsc(U"IN"),.country_ab3=tsc(U"IND"),.country_num=356,.country_car=tsc(U"IND"),.lang_name=tsc(U"मैथिली"),.lang_term=tsc(U"mai"),.lang_lib=tsc(U"mai")},.measurement={.measurement=1}};


}
}

#include"../main.h"