#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t monetary_mon_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Malagasy locale for Madagascar"),.source=tsc("The Debian Project modified by GNU//Linux Malagasy\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Rado Ramarotafika,Do-Risika RAFIEFERANTSIARONJY\t\t;\t\tfast_io"),.email=tsc("rado@linuxmg.org,dourix@free.fr;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Malagasy"),.territory=tsc("Madagascar"),.revision=tsc("1.1"),.date=tsc("2005-02-02")},.monetary={.int_curr_symbol=tsc("MGA "),.currency_symbol=tsc("Ar"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("")},.time={.abday={tsc("lhd"),tsc("lts"),tsc("tlt"),tsc("lrb"),tsc("lkm"),tsc("zom"),tsc("sab")},.day={tsc("alahady"),tsc("alatsinainy"),tsc("talata"),tsc("alarobia"),tsc("alakamisy"),tsc("zoma"),tsc("sabotsy")},.abmon={tsc("Jan"),tsc("Feb"),tsc("Mar"),tsc("Apr"),tsc("Mey"),tsc("Jon"),tsc("Jol"),tsc("Aog"),tsc("Sep"),tsc("Okt"),tsc("Nov"),tsc("Des")},.mon={tsc("Janoary"),tsc("Febroary"),tsc("Martsa"),tsc("Aprily"),tsc("Mey"),tsc("Jona"),tsc("Jolay"),tsc("Aogositra"),tsc("Septambra"),tsc("Oktobra"),tsc("Novambra"),tsc("Desambra")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1eEyY]"),.noexpr=tsc("^[-0tTnN]"),.yesstr=tsc("Eny"),.nostr=tsc("Tsia")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.tel_dom_fmt=tsc("%a %l"),.int_select=tsc("00"),.int_prefix=tsc("261")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Madagasikara"),.country_ab2=tsc("MG"),.country_ab3=tsc("MDG"),.country_num=450,.country_car=tsc("RM"),.lang_name=tsc("Malagasy"),.lang_ab=tsc("mg"),.lang_term=tsc("mlg"),.lang_lib=tsc("mlg")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Malagasy locale for Madagascar"),.source=tsc(L"The Debian Project modified by GNU//Linux Malagasy\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Rado Ramarotafika,Do-Risika RAFIEFERANTSIARONJY\t\t;\t\tfast_io"),.email=tsc(L"rado@linuxmg.org,dourix@free.fr;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Malagasy"),.territory=tsc(L"Madagascar"),.revision=tsc(L"1.1"),.date=tsc(L"2005-02-02")},.monetary={.int_curr_symbol=tsc(L"MGA "),.currency_symbol=tsc(L"Ar"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"")},.time={.abday={tsc(L"lhd"),tsc(L"lts"),tsc(L"tlt"),tsc(L"lrb"),tsc(L"lkm"),tsc(L"zom"),tsc(L"sab")},.day={tsc(L"alahady"),tsc(L"alatsinainy"),tsc(L"talata"),tsc(L"alarobia"),tsc(L"alakamisy"),tsc(L"zoma"),tsc(L"sabotsy")},.abmon={tsc(L"Jan"),tsc(L"Feb"),tsc(L"Mar"),tsc(L"Apr"),tsc(L"Mey"),tsc(L"Jon"),tsc(L"Jol"),tsc(L"Aog"),tsc(L"Sep"),tsc(L"Okt"),tsc(L"Nov"),tsc(L"Des")},.mon={tsc(L"Janoary"),tsc(L"Febroary"),tsc(L"Martsa"),tsc(L"Aprily"),tsc(L"Mey"),tsc(L"Jona"),tsc(L"Jolay"),tsc(L"Aogositra"),tsc(L"Septambra"),tsc(L"Oktobra"),tsc(L"Novambra"),tsc(L"Desambra")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1eEyY]"),.noexpr=tsc(L"^[-0tTnN]"),.yesstr=tsc(L"Eny"),.nostr=tsc(L"Tsia")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.tel_dom_fmt=tsc(L"%a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"261")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Madagasikara"),.country_ab2=tsc(L"MG"),.country_ab3=tsc(L"MDG"),.country_num=450,.country_car=tsc(L"RM"),.lang_name=tsc(L"Malagasy"),.lang_ab=tsc(L"mg"),.lang_term=tsc(L"mlg"),.lang_lib=tsc(L"mlg")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Malagasy locale for Madagascar"),.source=tsc(u8"The Debian Project modified by GNU//Linux Malagasy\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Rado Ramarotafika,Do-Risika RAFIEFERANTSIARONJY\t\t;\t\tfast_io"),.email=tsc(u8"rado@linuxmg.org,dourix@free.fr;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Malagasy"),.territory=tsc(u8"Madagascar"),.revision=tsc(u8"1.1"),.date=tsc(u8"2005-02-02")},.monetary={.int_curr_symbol=tsc(u8"MGA "),.currency_symbol=tsc(u8"Ar"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"")},.time={.abday={tsc(u8"lhd"),tsc(u8"lts"),tsc(u8"tlt"),tsc(u8"lrb"),tsc(u8"lkm"),tsc(u8"zom"),tsc(u8"sab")},.day={tsc(u8"alahady"),tsc(u8"alatsinainy"),tsc(u8"talata"),tsc(u8"alarobia"),tsc(u8"alakamisy"),tsc(u8"zoma"),tsc(u8"sabotsy")},.abmon={tsc(u8"Jan"),tsc(u8"Feb"),tsc(u8"Mar"),tsc(u8"Apr"),tsc(u8"Mey"),tsc(u8"Jon"),tsc(u8"Jol"),tsc(u8"Aog"),tsc(u8"Sep"),tsc(u8"Okt"),tsc(u8"Nov"),tsc(u8"Des")},.mon={tsc(u8"Janoary"),tsc(u8"Febroary"),tsc(u8"Martsa"),tsc(u8"Aprily"),tsc(u8"Mey"),tsc(u8"Jona"),tsc(u8"Jolay"),tsc(u8"Aogositra"),tsc(u8"Septambra"),tsc(u8"Oktobra"),tsc(u8"Novambra"),tsc(u8"Desambra")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1eEyY]"),.noexpr=tsc(u8"^[-0tTnN]"),.yesstr=tsc(u8"Eny"),.nostr=tsc(u8"Tsia")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.tel_dom_fmt=tsc(u8"%a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"261")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Madagasikara"),.country_ab2=tsc(u8"MG"),.country_ab3=tsc(u8"MDG"),.country_num=450,.country_car=tsc(u8"RM"),.lang_name=tsc(u8"Malagasy"),.lang_ab=tsc(u8"mg"),.lang_term=tsc(u8"mlg"),.lang_lib=tsc(u8"mlg")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Malagasy locale for Madagascar"),.source=tsc(u"The Debian Project modified by GNU//Linux Malagasy\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Rado Ramarotafika,Do-Risika RAFIEFERANTSIARONJY\t\t;\t\tfast_io"),.email=tsc(u"rado@linuxmg.org,dourix@free.fr;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Malagasy"),.territory=tsc(u"Madagascar"),.revision=tsc(u"1.1"),.date=tsc(u"2005-02-02")},.monetary={.int_curr_symbol=tsc(u"MGA "),.currency_symbol=tsc(u"Ar"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"")},.time={.abday={tsc(u"lhd"),tsc(u"lts"),tsc(u"tlt"),tsc(u"lrb"),tsc(u"lkm"),tsc(u"zom"),tsc(u"sab")},.day={tsc(u"alahady"),tsc(u"alatsinainy"),tsc(u"talata"),tsc(u"alarobia"),tsc(u"alakamisy"),tsc(u"zoma"),tsc(u"sabotsy")},.abmon={tsc(u"Jan"),tsc(u"Feb"),tsc(u"Mar"),tsc(u"Apr"),tsc(u"Mey"),tsc(u"Jon"),tsc(u"Jol"),tsc(u"Aog"),tsc(u"Sep"),tsc(u"Okt"),tsc(u"Nov"),tsc(u"Des")},.mon={tsc(u"Janoary"),tsc(u"Febroary"),tsc(u"Martsa"),tsc(u"Aprily"),tsc(u"Mey"),tsc(u"Jona"),tsc(u"Jolay"),tsc(u"Aogositra"),tsc(u"Septambra"),tsc(u"Oktobra"),tsc(u"Novambra"),tsc(u"Desambra")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1eEyY]"),.noexpr=tsc(u"^[-0tTnN]"),.yesstr=tsc(u"Eny"),.nostr=tsc(u"Tsia")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.tel_dom_fmt=tsc(u"%a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"261")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Madagasikara"),.country_ab2=tsc(u"MG"),.country_ab3=tsc(u"MDG"),.country_num=450,.country_car=tsc(u"RM"),.lang_name=tsc(u"Malagasy"),.lang_ab=tsc(u"mg"),.lang_term=tsc(u"mlg"),.lang_lib=tsc(u"mlg")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Malagasy locale for Madagascar"),.source=tsc(U"The Debian Project modified by GNU//Linux Malagasy\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Rado Ramarotafika,Do-Risika RAFIEFERANTSIARONJY\t\t;\t\tfast_io"),.email=tsc(U"rado@linuxmg.org,dourix@free.fr;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Malagasy"),.territory=tsc(U"Madagascar"),.revision=tsc(U"1.1"),.date=tsc(U"2005-02-02")},.monetary={.int_curr_symbol=tsc(U"MGA "),.currency_symbol=tsc(U"Ar"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"")},.time={.abday={tsc(U"lhd"),tsc(U"lts"),tsc(U"tlt"),tsc(U"lrb"),tsc(U"lkm"),tsc(U"zom"),tsc(U"sab")},.day={tsc(U"alahady"),tsc(U"alatsinainy"),tsc(U"talata"),tsc(U"alarobia"),tsc(U"alakamisy"),tsc(U"zoma"),tsc(U"sabotsy")},.abmon={tsc(U"Jan"),tsc(U"Feb"),tsc(U"Mar"),tsc(U"Apr"),tsc(U"Mey"),tsc(U"Jon"),tsc(U"Jol"),tsc(U"Aog"),tsc(U"Sep"),tsc(U"Okt"),tsc(U"Nov"),tsc(U"Des")},.mon={tsc(U"Janoary"),tsc(U"Febroary"),tsc(U"Martsa"),tsc(U"Aprily"),tsc(U"Mey"),tsc(U"Jona"),tsc(U"Jolay"),tsc(U"Aogositra"),tsc(U"Septambra"),tsc(U"Oktobra"),tsc(U"Novambra"),tsc(U"Desambra")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1eEyY]"),.noexpr=tsc(U"^[-0tTnN]"),.yesstr=tsc(U"Eny"),.nostr=tsc(U"Tsia")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.tel_dom_fmt=tsc(U"%a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"261")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Madagasikara"),.country_ab2=tsc(U"MG"),.country_ab3=tsc(U"MDG"),.country_num=450,.country_car=tsc(U"RM"),.lang_name=tsc(U"Malagasy"),.lang_ab=tsc(U"mg"),.lang_term=tsc(U"mlg"),.lang_lib=tsc(U"mlg")},.measurement={.measurement=1}};


}
}

#include"../main.h"