#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Maori language locale for New Zealand"),.source=tsc("James Gasson\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("James Gasson, Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc("james.gasson@clear.net.nz, pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Maori"),.territory=tsc("New Zealand"),.revision=tsc("0.3"),.date=tsc("2001-01-28")},.monetary={.int_curr_symbol=tsc("NZD "),.currency_symbol=tsc("$"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("Ta"),tsc("Ma"),tsc("Tū"),tsc("We"),tsc("Tāi"),tsc("Pa"),tsc("Hā")},.day={tsc("Rātapu"),tsc("Mane"),tsc("Tūrei"),tsc("Wenerei"),tsc("Tāite"),tsc("Paraire"),tsc("Hātarei")},.abmon={tsc("Kohi"),tsc("Hui"),tsc("Pou"),tsc("Pae"),tsc("Hara"),tsc("Pipi"),tsc("Hōngoi"),tsc("Here"),tsc("Mahu"),tsc("Whi-nu"),tsc("Whi-ra"),tsc("Haki")},.mon={tsc("Kohi-tātea"),tsc("Hui-tanguru"),tsc("Poutū-te-rangi"),tsc("Paenga-whāwhā"),tsc("Haratua"),tsc("Pipiri"),tsc("Hōngoingoi"),tsc("Here-turi-kōkā"),tsc("Mahuru"),tsc("Whiringa-ā-nuku"),tsc("Whiringa-ā-rangi"),tsc("Hakihea")},.d_t_fmt=tsc("Te %A, te %d o %B, %Y %T"),.d_fmt=tsc("%d//%m//%y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("Te %A, te %d o %B, %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1}},.messages={.yesexpr=tsc("^[+1yYāĀäÄaA]"),.noexpr=tsc("^[-0nNkK]"),.yesstr=tsc("āe"),.nostr=tsc("kāore")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("64")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Aotearoa"),.country_ab2=tsc("NZ"),.country_ab3=tsc("NZL"),.country_num=554,.country_car=tsc("NZ"),.lang_name=tsc("Māori"),.lang_ab=tsc("mi"),.lang_term=tsc("mri"),.lang_lib=tsc("mao")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Maori language locale for New Zealand"),.source=tsc(L"James Gasson\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"James Gasson, Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(L"james.gasson@clear.net.nz, pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Maori"),.territory=tsc(L"New Zealand"),.revision=tsc(L"0.3"),.date=tsc(L"2001-01-28")},.monetary={.int_curr_symbol=tsc(L"NZD "),.currency_symbol=tsc(L"$"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"Ta"),tsc(L"Ma"),tsc(L"Tū"),tsc(L"We"),tsc(L"Tāi"),tsc(L"Pa"),tsc(L"Hā")},.day={tsc(L"Rātapu"),tsc(L"Mane"),tsc(L"Tūrei"),tsc(L"Wenerei"),tsc(L"Tāite"),tsc(L"Paraire"),tsc(L"Hātarei")},.abmon={tsc(L"Kohi"),tsc(L"Hui"),tsc(L"Pou"),tsc(L"Pae"),tsc(L"Hara"),tsc(L"Pipi"),tsc(L"Hōngoi"),tsc(L"Here"),tsc(L"Mahu"),tsc(L"Whi-nu"),tsc(L"Whi-ra"),tsc(L"Haki")},.mon={tsc(L"Kohi-tātea"),tsc(L"Hui-tanguru"),tsc(L"Poutū-te-rangi"),tsc(L"Paenga-whāwhā"),tsc(L"Haratua"),tsc(L"Pipiri"),tsc(L"Hōngoingoi"),tsc(L"Here-turi-kōkā"),tsc(L"Mahuru"),tsc(L"Whiringa-ā-nuku"),tsc(L"Whiringa-ā-rangi"),tsc(L"Hakihea")},.d_t_fmt=tsc(L"Te %A, te %d o %B, %Y %T"),.d_fmt=tsc(L"%d//%m//%y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"Te %A, te %d o %B, %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(L"^[+1yYāĀäÄaA]"),.noexpr=tsc(L"^[-0nNkK]"),.yesstr=tsc(L"āe"),.nostr=tsc(L"kāore")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"64")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Aotearoa"),.country_ab2=tsc(L"NZ"),.country_ab3=tsc(L"NZL"),.country_num=554,.country_car=tsc(L"NZ"),.lang_name=tsc(L"Māori"),.lang_ab=tsc(L"mi"),.lang_term=tsc(L"mri"),.lang_lib=tsc(L"mao")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Maori language locale for New Zealand"),.source=tsc(u8"James Gasson\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"James Gasson, Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(u8"james.gasson@clear.net.nz, pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Maori"),.territory=tsc(u8"New Zealand"),.revision=tsc(u8"0.3"),.date=tsc(u8"2001-01-28")},.monetary={.int_curr_symbol=tsc(u8"NZD "),.currency_symbol=tsc(u8"$"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"Ta"),tsc(u8"Ma"),tsc(u8"Tū"),tsc(u8"We"),tsc(u8"Tāi"),tsc(u8"Pa"),tsc(u8"Hā")},.day={tsc(u8"Rātapu"),tsc(u8"Mane"),tsc(u8"Tūrei"),tsc(u8"Wenerei"),tsc(u8"Tāite"),tsc(u8"Paraire"),tsc(u8"Hātarei")},.abmon={tsc(u8"Kohi"),tsc(u8"Hui"),tsc(u8"Pou"),tsc(u8"Pae"),tsc(u8"Hara"),tsc(u8"Pipi"),tsc(u8"Hōngoi"),tsc(u8"Here"),tsc(u8"Mahu"),tsc(u8"Whi-nu"),tsc(u8"Whi-ra"),tsc(u8"Haki")},.mon={tsc(u8"Kohi-tātea"),tsc(u8"Hui-tanguru"),tsc(u8"Poutū-te-rangi"),tsc(u8"Paenga-whāwhā"),tsc(u8"Haratua"),tsc(u8"Pipiri"),tsc(u8"Hōngoingoi"),tsc(u8"Here-turi-kōkā"),tsc(u8"Mahuru"),tsc(u8"Whiringa-ā-nuku"),tsc(u8"Whiringa-ā-rangi"),tsc(u8"Hakihea")},.d_t_fmt=tsc(u8"Te %A, te %d o %B, %Y %T"),.d_fmt=tsc(u8"%d//%m//%y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"Te %A, te %d o %B, %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u8"^[+1yYāĀäÄaA]"),.noexpr=tsc(u8"^[-0nNkK]"),.yesstr=tsc(u8"āe"),.nostr=tsc(u8"kāore")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"64")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Aotearoa"),.country_ab2=tsc(u8"NZ"),.country_ab3=tsc(u8"NZL"),.country_num=554,.country_car=tsc(u8"NZ"),.lang_name=tsc(u8"Māori"),.lang_ab=tsc(u8"mi"),.lang_term=tsc(u8"mri"),.lang_lib=tsc(u8"mao")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Maori language locale for New Zealand"),.source=tsc(u"James Gasson\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"James Gasson, Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(u"james.gasson@clear.net.nz, pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Maori"),.territory=tsc(u"New Zealand"),.revision=tsc(u"0.3"),.date=tsc(u"2001-01-28")},.monetary={.int_curr_symbol=tsc(u"NZD "),.currency_symbol=tsc(u"$"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"Ta"),tsc(u"Ma"),tsc(u"Tū"),tsc(u"We"),tsc(u"Tāi"),tsc(u"Pa"),tsc(u"Hā")},.day={tsc(u"Rātapu"),tsc(u"Mane"),tsc(u"Tūrei"),tsc(u"Wenerei"),tsc(u"Tāite"),tsc(u"Paraire"),tsc(u"Hātarei")},.abmon={tsc(u"Kohi"),tsc(u"Hui"),tsc(u"Pou"),tsc(u"Pae"),tsc(u"Hara"),tsc(u"Pipi"),tsc(u"Hōngoi"),tsc(u"Here"),tsc(u"Mahu"),tsc(u"Whi-nu"),tsc(u"Whi-ra"),tsc(u"Haki")},.mon={tsc(u"Kohi-tātea"),tsc(u"Hui-tanguru"),tsc(u"Poutū-te-rangi"),tsc(u"Paenga-whāwhā"),tsc(u"Haratua"),tsc(u"Pipiri"),tsc(u"Hōngoingoi"),tsc(u"Here-turi-kōkā"),tsc(u"Mahuru"),tsc(u"Whiringa-ā-nuku"),tsc(u"Whiringa-ā-rangi"),tsc(u"Hakihea")},.d_t_fmt=tsc(u"Te %A, te %d o %B, %Y %T"),.d_fmt=tsc(u"%d//%m//%y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"Te %A, te %d o %B, %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u"^[+1yYāĀäÄaA]"),.noexpr=tsc(u"^[-0nNkK]"),.yesstr=tsc(u"āe"),.nostr=tsc(u"kāore")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"64")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Aotearoa"),.country_ab2=tsc(u"NZ"),.country_ab3=tsc(u"NZL"),.country_num=554,.country_car=tsc(u"NZ"),.lang_name=tsc(u"Māori"),.lang_ab=tsc(u"mi"),.lang_term=tsc(u"mri"),.lang_lib=tsc(u"mao")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Maori language locale for New Zealand"),.source=tsc(U"James Gasson\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"James Gasson, Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(U"james.gasson@clear.net.nz, pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Maori"),.territory=tsc(U"New Zealand"),.revision=tsc(U"0.3"),.date=tsc(U"2001-01-28")},.monetary={.int_curr_symbol=tsc(U"NZD "),.currency_symbol=tsc(U"$"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"Ta"),tsc(U"Ma"),tsc(U"Tū"),tsc(U"We"),tsc(U"Tāi"),tsc(U"Pa"),tsc(U"Hā")},.day={tsc(U"Rātapu"),tsc(U"Mane"),tsc(U"Tūrei"),tsc(U"Wenerei"),tsc(U"Tāite"),tsc(U"Paraire"),tsc(U"Hātarei")},.abmon={tsc(U"Kohi"),tsc(U"Hui"),tsc(U"Pou"),tsc(U"Pae"),tsc(U"Hara"),tsc(U"Pipi"),tsc(U"Hōngoi"),tsc(U"Here"),tsc(U"Mahu"),tsc(U"Whi-nu"),tsc(U"Whi-ra"),tsc(U"Haki")},.mon={tsc(U"Kohi-tātea"),tsc(U"Hui-tanguru"),tsc(U"Poutū-te-rangi"),tsc(U"Paenga-whāwhā"),tsc(U"Haratua"),tsc(U"Pipiri"),tsc(U"Hōngoingoi"),tsc(U"Here-turi-kōkā"),tsc(U"Mahuru"),tsc(U"Whiringa-ā-nuku"),tsc(U"Whiringa-ā-rangi"),tsc(U"Hakihea")},.d_t_fmt=tsc(U"Te %A, te %d o %B, %Y %T"),.d_fmt=tsc(U"%d//%m//%y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"Te %A, te %d o %B, %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1}},.messages={.yesexpr=tsc(U"^[+1yYāĀäÄaA]"),.noexpr=tsc(U"^[-0nNkK]"),.yesstr=tsc(U"āe"),.nostr=tsc(U"kāore")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"64")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Aotearoa"),.country_ab2=tsc(U"NZ"),.country_ab3=tsc(U"NZL"),.country_num=554,.country_car=tsc(U"NZ"),.lang_name=tsc(U"Māori"),.lang_ab=tsc(U"mi"),.lang_term=tsc(U"mri"),.lang_lib=tsc(U"mao")},.measurement={.measurement=1}};


}
}

#include"../main.h"