#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Miskito language locale for Nicaragua"),.language=tsc("Miskito"),.territory=tsc("Nicaragua"),.revision=tsc("1.0"),.date=tsc("2016-08-20")},.monetary={.int_curr_symbol=tsc("NIO "),.currency_symbol=tsc("C$"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("san"),tsc("mun"),tsc("tius"),tsc("wens"),tsc("taus"),tsc("prai"),tsc("sat")},.day={tsc("sandi"),tsc("mundi"),tsc("tiusdi"),tsc("wensde"),tsc("tausde"),tsc("praidi"),tsc("satadi")},.abmon={tsc("siakwa kati"),tsc("kuswa kati"),tsc("kakamuk kati"),tsc("lî wainhka kati"),tsc("lih mairin kati"),tsc("lî kati"),tsc("pastara kati"),tsc("sikla kati"),tsc("wîs kati"),tsc("waupasa kati"),tsc("yahbra kati"),tsc("trisu kati")},.mon={tsc("siakwa kati"),tsc("kuswa kati"),tsc("kakamuk kati"),tsc("lî wainhka kati"),tsc("lih mairin kati"),tsc("lî kati"),tsc("pastara kati"),tsc("sikla kati"),tsc("wîs kati"),tsc("waupasa kati"),tsc("yahbra kati"),tsc("trisu kati")},.d_t_fmt=tsc("%a %d %b %Y %T %Z"),.d_fmt=tsc("%d//%m//%y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc("%I:%M:%S %p"),.date_fmt=tsc("%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc("VM"),tsc("NM")},.week={7,19971130,7},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc("^[+1sSyY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("sí"),.nostr=tsc("no")},.paper={.width=216,.height=279},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("505")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Nicaragua"),.country_ab2=tsc("NI"),.country_ab3=tsc("NIC"),.country_num=558,.country_car=tsc("NIC"),.lang_name=tsc("Mískitu"),.lang_term=tsc("miq"),.lang_lib=tsc("miq")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Miskito language locale for Nicaragua"),.language=tsc(L"Miskito"),.territory=tsc(L"Nicaragua"),.revision=tsc(L"1.0"),.date=tsc(L"2016-08-20")},.monetary={.int_curr_symbol=tsc(L"NIO "),.currency_symbol=tsc(L"C$"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"san"),tsc(L"mun"),tsc(L"tius"),tsc(L"wens"),tsc(L"taus"),tsc(L"prai"),tsc(L"sat")},.day={tsc(L"sandi"),tsc(L"mundi"),tsc(L"tiusdi"),tsc(L"wensde"),tsc(L"tausde"),tsc(L"praidi"),tsc(L"satadi")},.abmon={tsc(L"siakwa kati"),tsc(L"kuswa kati"),tsc(L"kakamuk kati"),tsc(L"lî wainhka kati"),tsc(L"lih mairin kati"),tsc(L"lî kati"),tsc(L"pastara kati"),tsc(L"sikla kati"),tsc(L"wîs kati"),tsc(L"waupasa kati"),tsc(L"yahbra kati"),tsc(L"trisu kati")},.mon={tsc(L"siakwa kati"),tsc(L"kuswa kati"),tsc(L"kakamuk kati"),tsc(L"lî wainhka kati"),tsc(L"lih mairin kati"),tsc(L"lî kati"),tsc(L"pastara kati"),tsc(L"sikla kati"),tsc(L"wîs kati"),tsc(L"waupasa kati"),tsc(L"yahbra kati"),tsc(L"trisu kati")},.d_t_fmt=tsc(L"%a %d %b %Y %T %Z"),.d_fmt=tsc(L"%d//%m//%y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L"%I:%M:%S %p"),.date_fmt=tsc(L"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(L"VM"),tsc(L"NM")},.week={7,19971130,7},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc(L"^[+1sSyY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"sí"),.nostr=tsc(L"no")},.paper={.width=216,.height=279},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"505")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Nicaragua"),.country_ab2=tsc(L"NI"),.country_ab3=tsc(L"NIC"),.country_num=558,.country_car=tsc(L"NIC"),.lang_name=tsc(L"Mískitu"),.lang_term=tsc(L"miq"),.lang_lib=tsc(L"miq")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Miskito language locale for Nicaragua"),.language=tsc(u8"Miskito"),.territory=tsc(u8"Nicaragua"),.revision=tsc(u8"1.0"),.date=tsc(u8"2016-08-20")},.monetary={.int_curr_symbol=tsc(u8"NIO "),.currency_symbol=tsc(u8"C$"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"san"),tsc(u8"mun"),tsc(u8"tius"),tsc(u8"wens"),tsc(u8"taus"),tsc(u8"prai"),tsc(u8"sat")},.day={tsc(u8"sandi"),tsc(u8"mundi"),tsc(u8"tiusdi"),tsc(u8"wensde"),tsc(u8"tausde"),tsc(u8"praidi"),tsc(u8"satadi")},.abmon={tsc(u8"siakwa kati"),tsc(u8"kuswa kati"),tsc(u8"kakamuk kati"),tsc(u8"lî wainhka kati"),tsc(u8"lih mairin kati"),tsc(u8"lî kati"),tsc(u8"pastara kati"),tsc(u8"sikla kati"),tsc(u8"wîs kati"),tsc(u8"waupasa kati"),tsc(u8"yahbra kati"),tsc(u8"trisu kati")},.mon={tsc(u8"siakwa kati"),tsc(u8"kuswa kati"),tsc(u8"kakamuk kati"),tsc(u8"lî wainhka kati"),tsc(u8"lih mairin kati"),tsc(u8"lî kati"),tsc(u8"pastara kati"),tsc(u8"sikla kati"),tsc(u8"wîs kati"),tsc(u8"waupasa kati"),tsc(u8"yahbra kati"),tsc(u8"trisu kati")},.d_t_fmt=tsc(u8"%a %d %b %Y %T %Z"),.d_fmt=tsc(u8"%d//%m//%y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p"),.date_fmt=tsc(u8"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(u8"VM"),tsc(u8"NM")},.week={7,19971130,7},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc(u8"^[+1sSyY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"sí"),.nostr=tsc(u8"no")},.paper={.width=216,.height=279},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"505")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Nicaragua"),.country_ab2=tsc(u8"NI"),.country_ab3=tsc(u8"NIC"),.country_num=558,.country_car=tsc(u8"NIC"),.lang_name=tsc(u8"Mískitu"),.lang_term=tsc(u8"miq"),.lang_lib=tsc(u8"miq")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Miskito language locale for Nicaragua"),.language=tsc(u"Miskito"),.territory=tsc(u"Nicaragua"),.revision=tsc(u"1.0"),.date=tsc(u"2016-08-20")},.monetary={.int_curr_symbol=tsc(u"NIO "),.currency_symbol=tsc(u"C$"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"san"),tsc(u"mun"),tsc(u"tius"),tsc(u"wens"),tsc(u"taus"),tsc(u"prai"),tsc(u"sat")},.day={tsc(u"sandi"),tsc(u"mundi"),tsc(u"tiusdi"),tsc(u"wensde"),tsc(u"tausde"),tsc(u"praidi"),tsc(u"satadi")},.abmon={tsc(u"siakwa kati"),tsc(u"kuswa kati"),tsc(u"kakamuk kati"),tsc(u"lî wainhka kati"),tsc(u"lih mairin kati"),tsc(u"lî kati"),tsc(u"pastara kati"),tsc(u"sikla kati"),tsc(u"wîs kati"),tsc(u"waupasa kati"),tsc(u"yahbra kati"),tsc(u"trisu kati")},.mon={tsc(u"siakwa kati"),tsc(u"kuswa kati"),tsc(u"kakamuk kati"),tsc(u"lî wainhka kati"),tsc(u"lih mairin kati"),tsc(u"lî kati"),tsc(u"pastara kati"),tsc(u"sikla kati"),tsc(u"wîs kati"),tsc(u"waupasa kati"),tsc(u"yahbra kati"),tsc(u"trisu kati")},.d_t_fmt=tsc(u"%a %d %b %Y %T %Z"),.d_fmt=tsc(u"%d//%m//%y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u"%I:%M:%S %p"),.date_fmt=tsc(u"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(u"VM"),tsc(u"NM")},.week={7,19971130,7},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc(u"^[+1sSyY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"sí"),.nostr=tsc(u"no")},.paper={.width=216,.height=279},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"505")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Nicaragua"),.country_ab2=tsc(u"NI"),.country_ab3=tsc(u"NIC"),.country_num=558,.country_car=tsc(u"NIC"),.lang_name=tsc(u"Mískitu"),.lang_term=tsc(u"miq"),.lang_lib=tsc(u"miq")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Miskito language locale for Nicaragua"),.language=tsc(U"Miskito"),.territory=tsc(U"Nicaragua"),.revision=tsc(U"1.0"),.date=tsc(U"2016-08-20")},.monetary={.int_curr_symbol=tsc(U"NIO "),.currency_symbol=tsc(U"C$"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"san"),tsc(U"mun"),tsc(U"tius"),tsc(U"wens"),tsc(U"taus"),tsc(U"prai"),tsc(U"sat")},.day={tsc(U"sandi"),tsc(U"mundi"),tsc(U"tiusdi"),tsc(U"wensde"),tsc(U"tausde"),tsc(U"praidi"),tsc(U"satadi")},.abmon={tsc(U"siakwa kati"),tsc(U"kuswa kati"),tsc(U"kakamuk kati"),tsc(U"lî wainhka kati"),tsc(U"lih mairin kati"),tsc(U"lî kati"),tsc(U"pastara kati"),tsc(U"sikla kati"),tsc(U"wîs kati"),tsc(U"waupasa kati"),tsc(U"yahbra kati"),tsc(U"trisu kati")},.mon={tsc(U"siakwa kati"),tsc(U"kuswa kati"),tsc(U"kakamuk kati"),tsc(U"lî wainhka kati"),tsc(U"lih mairin kati"),tsc(U"lî kati"),tsc(U"pastara kati"),tsc(U"sikla kati"),tsc(U"wîs kati"),tsc(U"waupasa kati"),tsc(U"yahbra kati"),tsc(U"trisu kati")},.d_t_fmt=tsc(U"%a %d %b %Y %T %Z"),.d_fmt=tsc(U"%d//%m//%y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U"%I:%M:%S %p"),.date_fmt=tsc(U"%a %b %e %H:%M:%S %Z %Y"),.am_pm={tsc(U"VM"),tsc(U"NM")},.week={7,19971130,7},.first_weekday=1,.first_workday=2},.messages={.yesexpr=tsc(U"^[+1sSyY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"sí"),.nostr=tsc(U"no")},.paper={.width=216,.height=279},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"505")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Nicaragua"),.country_ab2=tsc(U"NI"),.country_ab3=tsc(U"NIC"),.country_num=558,.country_car=tsc(U"NIC"),.lang_name=tsc(U"Mískitu"),.lang_term=tsc(U"miq"),.lang_lib=tsc(U"miq")},.measurement={.measurement=1}};


}
}

#include"../main.h"