#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3,2};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Karbi language locale for India"),.source=tsc("Jor Teron\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Karbi"),.territory=tsc("India"),.revision=tsc("1.1"),.date=tsc("2013-08-08")},.monetary={.int_curr_symbol=tsc("INR "),.currency_symbol=tsc("₹"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,2},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,2}},.time={.abday={tsc("Bhom"),tsc("Ur"),tsc("Dur"),tsc("Tkel"),tsc("Tkem"),tsc("Bhta"),tsc("Bhti")},.day={tsc("Bhomkuru"),tsc("Urmi"),tsc("Durmi"),tsc("Thelang"),tsc("Theman"),tsc("Bhomta"),tsc("Bhomti")},.abmon={tsc("Ark"),tsc("Thang"),tsc("The"),tsc("Jang"),tsc("Aru"),tsc("Vos"),tsc("Jak"),tsc("Pai"),tsc("Chi"),tsc("Phe"),tsc("Phai"),tsc("Mati")},.mon={tsc("Arkoi"),tsc("Thangthang"),tsc("There"),tsc("Jangmi"),tsc("Aru"),tsc("Vosik"),tsc("Jakhong"),tsc("Paipai"),tsc("Chiti"),tsc("Phere"),tsc("Phaikuni"),tsc("Matijong")},.d_t_fmt=tsc("%A %d %B %Y %I:%M:%S %p"),.d_fmt=tsc("%-d//%-m//%y"),.t_fmt=tsc("%I:%M:%S %p %Z"),.t_fmt_ampm=tsc("%I:%M:%S %p %Z"),.date_fmt=tsc("%A %d %B %Y %I:%M:%S %p %Z"),.am_pm={tsc("AM"),tsc("PM")},.week={7,19971130,1},.first_weekday=1},.messages={.yesexpr=tsc("^[+1yY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("yes"),.nostr=tsc("no")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c ;%a ;%l"),.int_select=tsc("00"),.int_prefix=tsc("91")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f"),.name_gen=tsc(""),.name_miss=tsc("Sami"),.name_mrs=tsc("Sangpi"),.name_ms=tsc("")},.address={.postal_fmt=tsc("%z%c%T%s%b%e%r"),.country_name=tsc("Bhorot"),.country_ab2=tsc("IN"),.country_ab3=tsc("IND"),.country_num=356,.country_car=tsc("IND"),.lang_name=tsc("Karbi"),.lang_term=tsc("mjw"),.lang_lib=tsc("mjw")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Karbi language locale for India"),.source=tsc(L"Jor Teron\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Karbi"),.territory=tsc(L"India"),.revision=tsc(L"1.1"),.date=tsc(L"2013-08-08")},.monetary={.int_curr_symbol=tsc(L"INR "),.currency_symbol=tsc(L"₹"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,2},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,2}},.time={.abday={tsc(L"Bhom"),tsc(L"Ur"),tsc(L"Dur"),tsc(L"Tkel"),tsc(L"Tkem"),tsc(L"Bhta"),tsc(L"Bhti")},.day={tsc(L"Bhomkuru"),tsc(L"Urmi"),tsc(L"Durmi"),tsc(L"Thelang"),tsc(L"Theman"),tsc(L"Bhomta"),tsc(L"Bhomti")},.abmon={tsc(L"Ark"),tsc(L"Thang"),tsc(L"The"),tsc(L"Jang"),tsc(L"Aru"),tsc(L"Vos"),tsc(L"Jak"),tsc(L"Pai"),tsc(L"Chi"),tsc(L"Phe"),tsc(L"Phai"),tsc(L"Mati")},.mon={tsc(L"Arkoi"),tsc(L"Thangthang"),tsc(L"There"),tsc(L"Jangmi"),tsc(L"Aru"),tsc(L"Vosik"),tsc(L"Jakhong"),tsc(L"Paipai"),tsc(L"Chiti"),tsc(L"Phere"),tsc(L"Phaikuni"),tsc(L"Matijong")},.d_t_fmt=tsc(L"%A %d %B %Y %I:%M:%S %p"),.d_fmt=tsc(L"%-d//%-m//%y"),.t_fmt=tsc(L"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(L"%I:%M:%S %p %Z"),.date_fmt=tsc(L"%A %d %B %Y %I:%M:%S %p %Z"),.am_pm={tsc(L"AM"),tsc(L"PM")},.week={7,19971130,1},.first_weekday=1},.messages={.yesexpr=tsc(L"^[+1yY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"yes"),.nostr=tsc(L"no")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c ;%a ;%l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"91")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f"),.name_gen=tsc(L""),.name_miss=tsc(L"Sami"),.name_mrs=tsc(L"Sangpi"),.name_ms=tsc(L"")},.address={.postal_fmt=tsc(L"%z%c%T%s%b%e%r"),.country_name=tsc(L"Bhorot"),.country_ab2=tsc(L"IN"),.country_ab3=tsc(L"IND"),.country_num=356,.country_car=tsc(L"IND"),.lang_name=tsc(L"Karbi"),.lang_term=tsc(L"mjw"),.lang_lib=tsc(L"mjw")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Karbi language locale for India"),.source=tsc(u8"Jor Teron\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Karbi"),.territory=tsc(u8"India"),.revision=tsc(u8"1.1"),.date=tsc(u8"2013-08-08")},.monetary={.int_curr_symbol=tsc(u8"INR "),.currency_symbol=tsc(u8"₹"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,2},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,2}},.time={.abday={tsc(u8"Bhom"),tsc(u8"Ur"),tsc(u8"Dur"),tsc(u8"Tkel"),tsc(u8"Tkem"),tsc(u8"Bhta"),tsc(u8"Bhti")},.day={tsc(u8"Bhomkuru"),tsc(u8"Urmi"),tsc(u8"Durmi"),tsc(u8"Thelang"),tsc(u8"Theman"),tsc(u8"Bhomta"),tsc(u8"Bhomti")},.abmon={tsc(u8"Ark"),tsc(u8"Thang"),tsc(u8"The"),tsc(u8"Jang"),tsc(u8"Aru"),tsc(u8"Vos"),tsc(u8"Jak"),tsc(u8"Pai"),tsc(u8"Chi"),tsc(u8"Phe"),tsc(u8"Phai"),tsc(u8"Mati")},.mon={tsc(u8"Arkoi"),tsc(u8"Thangthang"),tsc(u8"There"),tsc(u8"Jangmi"),tsc(u8"Aru"),tsc(u8"Vosik"),tsc(u8"Jakhong"),tsc(u8"Paipai"),tsc(u8"Chiti"),tsc(u8"Phere"),tsc(u8"Phaikuni"),tsc(u8"Matijong")},.d_t_fmt=tsc(u8"%A %d %B %Y %I:%M:%S %p"),.d_fmt=tsc(u8"%-d//%-m//%y"),.t_fmt=tsc(u8"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p %Z"),.date_fmt=tsc(u8"%A %d %B %Y %I:%M:%S %p %Z"),.am_pm={tsc(u8"AM"),tsc(u8"PM")},.week={7,19971130,1},.first_weekday=1},.messages={.yesexpr=tsc(u8"^[+1yY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"yes"),.nostr=tsc(u8"no")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c ;%a ;%l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"91")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f"),.name_gen=tsc(u8""),.name_miss=tsc(u8"Sami"),.name_mrs=tsc(u8"Sangpi"),.name_ms=tsc(u8"")},.address={.postal_fmt=tsc(u8"%z%c%T%s%b%e%r"),.country_name=tsc(u8"Bhorot"),.country_ab2=tsc(u8"IN"),.country_ab3=tsc(u8"IND"),.country_num=356,.country_car=tsc(u8"IND"),.lang_name=tsc(u8"Karbi"),.lang_term=tsc(u8"mjw"),.lang_lib=tsc(u8"mjw")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Karbi language locale for India"),.source=tsc(u"Jor Teron\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Karbi"),.territory=tsc(u"India"),.revision=tsc(u"1.1"),.date=tsc(u"2013-08-08")},.monetary={.int_curr_symbol=tsc(u"INR "),.currency_symbol=tsc(u"₹"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,2},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,2}},.time={.abday={tsc(u"Bhom"),tsc(u"Ur"),tsc(u"Dur"),tsc(u"Tkel"),tsc(u"Tkem"),tsc(u"Bhta"),tsc(u"Bhti")},.day={tsc(u"Bhomkuru"),tsc(u"Urmi"),tsc(u"Durmi"),tsc(u"Thelang"),tsc(u"Theman"),tsc(u"Bhomta"),tsc(u"Bhomti")},.abmon={tsc(u"Ark"),tsc(u"Thang"),tsc(u"The"),tsc(u"Jang"),tsc(u"Aru"),tsc(u"Vos"),tsc(u"Jak"),tsc(u"Pai"),tsc(u"Chi"),tsc(u"Phe"),tsc(u"Phai"),tsc(u"Mati")},.mon={tsc(u"Arkoi"),tsc(u"Thangthang"),tsc(u"There"),tsc(u"Jangmi"),tsc(u"Aru"),tsc(u"Vosik"),tsc(u"Jakhong"),tsc(u"Paipai"),tsc(u"Chiti"),tsc(u"Phere"),tsc(u"Phaikuni"),tsc(u"Matijong")},.d_t_fmt=tsc(u"%A %d %B %Y %I:%M:%S %p"),.d_fmt=tsc(u"%-d//%-m//%y"),.t_fmt=tsc(u"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(u"%I:%M:%S %p %Z"),.date_fmt=tsc(u"%A %d %B %Y %I:%M:%S %p %Z"),.am_pm={tsc(u"AM"),tsc(u"PM")},.week={7,19971130,1},.first_weekday=1},.messages={.yesexpr=tsc(u"^[+1yY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"yes"),.nostr=tsc(u"no")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c ;%a ;%l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"91")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f"),.name_gen=tsc(u""),.name_miss=tsc(u"Sami"),.name_mrs=tsc(u"Sangpi"),.name_ms=tsc(u"")},.address={.postal_fmt=tsc(u"%z%c%T%s%b%e%r"),.country_name=tsc(u"Bhorot"),.country_ab2=tsc(u"IN"),.country_ab3=tsc(u"IND"),.country_num=356,.country_car=tsc(u"IND"),.lang_name=tsc(u"Karbi"),.lang_term=tsc(u"mjw"),.lang_lib=tsc(u"mjw")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Karbi language locale for India"),.source=tsc(U"Jor Teron\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Karbi"),.territory=tsc(U"India"),.revision=tsc(U"1.1"),.date=tsc(U"2013-08-08")},.monetary={.int_curr_symbol=tsc(U"INR "),.currency_symbol=tsc(U"₹"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,2},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,2}},.time={.abday={tsc(U"Bhom"),tsc(U"Ur"),tsc(U"Dur"),tsc(U"Tkel"),tsc(U"Tkem"),tsc(U"Bhta"),tsc(U"Bhti")},.day={tsc(U"Bhomkuru"),tsc(U"Urmi"),tsc(U"Durmi"),tsc(U"Thelang"),tsc(U"Theman"),tsc(U"Bhomta"),tsc(U"Bhomti")},.abmon={tsc(U"Ark"),tsc(U"Thang"),tsc(U"The"),tsc(U"Jang"),tsc(U"Aru"),tsc(U"Vos"),tsc(U"Jak"),tsc(U"Pai"),tsc(U"Chi"),tsc(U"Phe"),tsc(U"Phai"),tsc(U"Mati")},.mon={tsc(U"Arkoi"),tsc(U"Thangthang"),tsc(U"There"),tsc(U"Jangmi"),tsc(U"Aru"),tsc(U"Vosik"),tsc(U"Jakhong"),tsc(U"Paipai"),tsc(U"Chiti"),tsc(U"Phere"),tsc(U"Phaikuni"),tsc(U"Matijong")},.d_t_fmt=tsc(U"%A %d %B %Y %I:%M:%S %p"),.d_fmt=tsc(U"%-d//%-m//%y"),.t_fmt=tsc(U"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(U"%I:%M:%S %p %Z"),.date_fmt=tsc(U"%A %d %B %Y %I:%M:%S %p %Z"),.am_pm={tsc(U"AM"),tsc(U"PM")},.week={7,19971130,1},.first_weekday=1},.messages={.yesexpr=tsc(U"^[+1yY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"yes"),.nostr=tsc(U"no")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c ;%a ;%l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"91")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f"),.name_gen=tsc(U""),.name_miss=tsc(U"Sami"),.name_mrs=tsc(U"Sangpi"),.name_ms=tsc(U"")},.address={.postal_fmt=tsc(U"%z%c%T%s%b%e%r"),.country_name=tsc(U"Bhorot"),.country_ab2=tsc(U"IN"),.country_ab3=tsc(U"IND"),.country_num=356,.country_car=tsc(U"IND"),.lang_name=tsc(U"Karbi"),.lang_term=tsc(U"mjw"),.lang_lib=tsc(U"mjw")},.measurement={.measurement=1}};


}
}

#include"../main.h"