#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t monetary_mon_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Papiamento Language for Aruba"),.source=tsc("information from native speaker\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc("pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Papiamento"),.territory=tsc("Aruba"),.revision=tsc("1.0"),.date=tsc("2013-09-27")},.monetary={.int_curr_symbol=tsc("AWG "),.currency_symbol=tsc("ƒ"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=2},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("")},.time={.abday={tsc("do"),tsc("lu"),tsc("ma"),tsc("we"),tsc("ra"),tsc("bi"),tsc("sa")},.day={tsc("Djadomingo"),tsc("Djaluna"),tsc("Djamars"),tsc("Djawebs"),tsc("Djarason"),tsc("Djabierne"),tsc("Djasabra")},.abmon={tsc("Yan"),tsc("Feb"),tsc("Mar"),tsc("Apr"),tsc("Mei"),tsc("Yün"),tsc("Yül"),tsc("Oug"),tsc("Sèp"),tsc("Okt"),tsc("Nov"),tsc("Des")},.mon={tsc("Yanüari"),tsc("Febrüari"),tsc("Mart"),tsc("Aprel"),tsc("Mei"),tsc("Yüni"),tsc("Yüli"),tsc("Ougùstùs"),tsc("Sèptèmber"),tsc("Oktober"),tsc("Novèmber"),tsc("Desèmber")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d-%m-%y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1sSyY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("sí"),.nostr=tsc("nò")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("297")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%d%N%f%N%d%N%b%N%s %h 5e %r%N%C%z %T%N%c%N"),.country_name=tsc("Aruba"),.country_post=tsc("AW"),.country_ab2=tsc("AW"),.country_ab3=tsc("ABW"),.country_num=533,.country_car=tsc("AUA"),.country_isbn=tsc(""),.lang_name=tsc("Papiamento"),.lang_term=tsc("pap"),.lang_lib=tsc("pap")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Papiamento Language for Aruba"),.source=tsc(L"information from native speaker\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(L"pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Papiamento"),.territory=tsc(L"Aruba"),.revision=tsc(L"1.0"),.date=tsc(L"2013-09-27")},.monetary={.int_curr_symbol=tsc(L"AWG "),.currency_symbol=tsc(L"ƒ"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=2},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"")},.time={.abday={tsc(L"do"),tsc(L"lu"),tsc(L"ma"),tsc(L"we"),tsc(L"ra"),tsc(L"bi"),tsc(L"sa")},.day={tsc(L"Djadomingo"),tsc(L"Djaluna"),tsc(L"Djamars"),tsc(L"Djawebs"),tsc(L"Djarason"),tsc(L"Djabierne"),tsc(L"Djasabra")},.abmon={tsc(L"Yan"),tsc(L"Feb"),tsc(L"Mar"),tsc(L"Apr"),tsc(L"Mei"),tsc(L"Yün"),tsc(L"Yül"),tsc(L"Oug"),tsc(L"Sèp"),tsc(L"Okt"),tsc(L"Nov"),tsc(L"Des")},.mon={tsc(L"Yanüari"),tsc(L"Febrüari"),tsc(L"Mart"),tsc(L"Aprel"),tsc(L"Mei"),tsc(L"Yüni"),tsc(L"Yüli"),tsc(L"Ougùstùs"),tsc(L"Sèptèmber"),tsc(L"Oktober"),tsc(L"Novèmber"),tsc(L"Desèmber")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d-%m-%y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1sSyY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"sí"),.nostr=tsc(L"nò")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"297")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%d%N%f%N%d%N%b%N%s %h 5e %r%N%C%z %T%N%c%N"),.country_name=tsc(L"Aruba"),.country_post=tsc(L"AW"),.country_ab2=tsc(L"AW"),.country_ab3=tsc(L"ABW"),.country_num=533,.country_car=tsc(L"AUA"),.country_isbn=tsc(L""),.lang_name=tsc(L"Papiamento"),.lang_term=tsc(L"pap"),.lang_lib=tsc(L"pap")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Papiamento Language for Aruba"),.source=tsc(u8"information from native speaker\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(u8"pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Papiamento"),.territory=tsc(u8"Aruba"),.revision=tsc(u8"1.0"),.date=tsc(u8"2013-09-27")},.monetary={.int_curr_symbol=tsc(u8"AWG "),.currency_symbol=tsc(u8"ƒ"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=2},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"")},.time={.abday={tsc(u8"do"),tsc(u8"lu"),tsc(u8"ma"),tsc(u8"we"),tsc(u8"ra"),tsc(u8"bi"),tsc(u8"sa")},.day={tsc(u8"Djadomingo"),tsc(u8"Djaluna"),tsc(u8"Djamars"),tsc(u8"Djawebs"),tsc(u8"Djarason"),tsc(u8"Djabierne"),tsc(u8"Djasabra")},.abmon={tsc(u8"Yan"),tsc(u8"Feb"),tsc(u8"Mar"),tsc(u8"Apr"),tsc(u8"Mei"),tsc(u8"Yün"),tsc(u8"Yül"),tsc(u8"Oug"),tsc(u8"Sèp"),tsc(u8"Okt"),tsc(u8"Nov"),tsc(u8"Des")},.mon={tsc(u8"Yanüari"),tsc(u8"Febrüari"),tsc(u8"Mart"),tsc(u8"Aprel"),tsc(u8"Mei"),tsc(u8"Yüni"),tsc(u8"Yüli"),tsc(u8"Ougùstùs"),tsc(u8"Sèptèmber"),tsc(u8"Oktober"),tsc(u8"Novèmber"),tsc(u8"Desèmber")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d-%m-%y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1sSyY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"sí"),.nostr=tsc(u8"nò")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"297")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%d%N%f%N%d%N%b%N%s %h 5e %r%N%C%z %T%N%c%N"),.country_name=tsc(u8"Aruba"),.country_post=tsc(u8"AW"),.country_ab2=tsc(u8"AW"),.country_ab3=tsc(u8"ABW"),.country_num=533,.country_car=tsc(u8"AUA"),.country_isbn=tsc(u8""),.lang_name=tsc(u8"Papiamento"),.lang_term=tsc(u8"pap"),.lang_lib=tsc(u8"pap")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Papiamento Language for Aruba"),.source=tsc(u"information from native speaker\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(u"pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Papiamento"),.territory=tsc(u"Aruba"),.revision=tsc(u"1.0"),.date=tsc(u"2013-09-27")},.monetary={.int_curr_symbol=tsc(u"AWG "),.currency_symbol=tsc(u"ƒ"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=2},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"")},.time={.abday={tsc(u"do"),tsc(u"lu"),tsc(u"ma"),tsc(u"we"),tsc(u"ra"),tsc(u"bi"),tsc(u"sa")},.day={tsc(u"Djadomingo"),tsc(u"Djaluna"),tsc(u"Djamars"),tsc(u"Djawebs"),tsc(u"Djarason"),tsc(u"Djabierne"),tsc(u"Djasabra")},.abmon={tsc(u"Yan"),tsc(u"Feb"),tsc(u"Mar"),tsc(u"Apr"),tsc(u"Mei"),tsc(u"Yün"),tsc(u"Yül"),tsc(u"Oug"),tsc(u"Sèp"),tsc(u"Okt"),tsc(u"Nov"),tsc(u"Des")},.mon={tsc(u"Yanüari"),tsc(u"Febrüari"),tsc(u"Mart"),tsc(u"Aprel"),tsc(u"Mei"),tsc(u"Yüni"),tsc(u"Yüli"),tsc(u"Ougùstùs"),tsc(u"Sèptèmber"),tsc(u"Oktober"),tsc(u"Novèmber"),tsc(u"Desèmber")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d-%m-%y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1sSyY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"sí"),.nostr=tsc(u"nò")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"297")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%d%N%f%N%d%N%b%N%s %h 5e %r%N%C%z %T%N%c%N"),.country_name=tsc(u"Aruba"),.country_post=tsc(u"AW"),.country_ab2=tsc(u"AW"),.country_ab3=tsc(u"ABW"),.country_num=533,.country_car=tsc(u"AUA"),.country_isbn=tsc(u""),.lang_name=tsc(u"Papiamento"),.lang_term=tsc(u"pap"),.lang_lib=tsc(u"pap")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Papiamento Language for Aruba"),.source=tsc(U"information from native speaker\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Pablo Saratxaga\t\t;\t\tfast_io"),.email=tsc(U"pablo@mandrakesoft.com;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Papiamento"),.territory=tsc(U"Aruba"),.revision=tsc(U"1.0"),.date=tsc(U"2013-09-27")},.monetary={.int_curr_symbol=tsc(U"AWG "),.currency_symbol=tsc(U"ƒ"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=2},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"")},.time={.abday={tsc(U"do"),tsc(U"lu"),tsc(U"ma"),tsc(U"we"),tsc(U"ra"),tsc(U"bi"),tsc(U"sa")},.day={tsc(U"Djadomingo"),tsc(U"Djaluna"),tsc(U"Djamars"),tsc(U"Djawebs"),tsc(U"Djarason"),tsc(U"Djabierne"),tsc(U"Djasabra")},.abmon={tsc(U"Yan"),tsc(U"Feb"),tsc(U"Mar"),tsc(U"Apr"),tsc(U"Mei"),tsc(U"Yün"),tsc(U"Yül"),tsc(U"Oug"),tsc(U"Sèp"),tsc(U"Okt"),tsc(U"Nov"),tsc(U"Des")},.mon={tsc(U"Yanüari"),tsc(U"Febrüari"),tsc(U"Mart"),tsc(U"Aprel"),tsc(U"Mei"),tsc(U"Yüni"),tsc(U"Yüli"),tsc(U"Ougùstùs"),tsc(U"Sèptèmber"),tsc(U"Oktober"),tsc(U"Novèmber"),tsc(U"Desèmber")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d-%m-%y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1sSyY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"sí"),.nostr=tsc(U"nò")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"297")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%d%N%f%N%d%N%b%N%s %h 5e %r%N%C%z %T%N%c%N"),.country_name=tsc(U"Aruba"),.country_post=tsc(U"AW"),.country_ab2=tsc(U"AW"),.country_ab3=tsc(U"ABW"),.country_num=533,.country_car=tsc(U"AUA"),.country_isbn=tsc(U""),.lang_name=tsc(U"Papiamento"),.lang_term=tsc(U"pap"),.lang_lib=tsc(U"pap")},.measurement={.measurement=1}};


}
}

#include"../main.h"