#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Cusco Quechua locale for Peru"),.source=tsc("Sugar Labs // OLPC\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("sugarlabs.org\t\t;\t\tfast_io"),.email=tsc("libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Cusco Quechua"),.territory=tsc("Peru"),.revision=tsc("1.0"),.date=tsc("2013-08-24")},.monetary={.int_curr_symbol=tsc("PEN "),.currency_symbol=tsc("S//"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("tum"),tsc("lun"),tsc("mar"),tsc("miy"),tsc("juy"),tsc("wiy"),tsc("saw")},.day={tsc("tuminku"),tsc("lunis"),tsc("martis"),tsc("miyirkulis"),tsc("juywis"),tsc("wiyirnis"),tsc("sawatu")},.abmon={tsc("ini"),tsc("phi"),tsc("mar"),tsc("awr"),tsc("may"),tsc("hun"),tsc("hul"),tsc("agu"),tsc("sip"),tsc("ukt"),tsc("nuw"),tsc("tis")},.mon={tsc("iniru"),tsc("phiwriru"),tsc("marsu"),tsc("awril"),tsc("mayu"),tsc("huniyu"),tsc("huliyu"),tsc("agustu"),tsc("siptiyimri"),tsc("uktuwri"),tsc("nuwiyimri"),tsc("tisiyimri")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d//%m//%y"),.t_fmt=tsc("%I:%M:%S %p"),.t_fmt_ampm=tsc("%I:%M:%S %p"),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc("AM"),tsc("PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc("^[+1aAsSyY]"),.noexpr=tsc("^[-0mMnN]"),.yesstr=tsc("Arí"),.nostr=tsc("Manan")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("51")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_ab2=tsc("PE"),.country_ab3=tsc("PER"),.country_num=604,.country_car=tsc("PE"),.lang_name=tsc("Qusqu runasimi"),.lang_term=tsc("quz"),.lang_lib=tsc("quz")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Cusco Quechua locale for Peru"),.source=tsc(L"Sugar Labs // OLPC\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"sugarlabs.org\t\t;\t\tfast_io"),.email=tsc(L"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Cusco Quechua"),.territory=tsc(L"Peru"),.revision=tsc(L"1.0"),.date=tsc(L"2013-08-24")},.monetary={.int_curr_symbol=tsc(L"PEN "),.currency_symbol=tsc(L"S//"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"tum"),tsc(L"lun"),tsc(L"mar"),tsc(L"miy"),tsc(L"juy"),tsc(L"wiy"),tsc(L"saw")},.day={tsc(L"tuminku"),tsc(L"lunis"),tsc(L"martis"),tsc(L"miyirkulis"),tsc(L"juywis"),tsc(L"wiyirnis"),tsc(L"sawatu")},.abmon={tsc(L"ini"),tsc(L"phi"),tsc(L"mar"),tsc(L"awr"),tsc(L"may"),tsc(L"hun"),tsc(L"hul"),tsc(L"agu"),tsc(L"sip"),tsc(L"ukt"),tsc(L"nuw"),tsc(L"tis")},.mon={tsc(L"iniru"),tsc(L"phiwriru"),tsc(L"marsu"),tsc(L"awril"),tsc(L"mayu"),tsc(L"huniyu"),tsc(L"huliyu"),tsc(L"agustu"),tsc(L"siptiyimri"),tsc(L"uktuwri"),tsc(L"nuwiyimri"),tsc(L"tisiyimri")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d//%m//%y"),.t_fmt=tsc(L"%I:%M:%S %p"),.t_fmt_ampm=tsc(L"%I:%M:%S %p"),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L"AM"),tsc(L"PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(L"^[+1aAsSyY]"),.noexpr=tsc(L"^[-0mMnN]"),.yesstr=tsc(L"Arí"),.nostr=tsc(L"Manan")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"51")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_ab2=tsc(L"PE"),.country_ab3=tsc(L"PER"),.country_num=604,.country_car=tsc(L"PE"),.lang_name=tsc(L"Qusqu runasimi"),.lang_term=tsc(L"quz"),.lang_lib=tsc(L"quz")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Cusco Quechua locale for Peru"),.source=tsc(u8"Sugar Labs // OLPC\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"sugarlabs.org\t\t;\t\tfast_io"),.email=tsc(u8"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Cusco Quechua"),.territory=tsc(u8"Peru"),.revision=tsc(u8"1.0"),.date=tsc(u8"2013-08-24")},.monetary={.int_curr_symbol=tsc(u8"PEN "),.currency_symbol=tsc(u8"S//"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"tum"),tsc(u8"lun"),tsc(u8"mar"),tsc(u8"miy"),tsc(u8"juy"),tsc(u8"wiy"),tsc(u8"saw")},.day={tsc(u8"tuminku"),tsc(u8"lunis"),tsc(u8"martis"),tsc(u8"miyirkulis"),tsc(u8"juywis"),tsc(u8"wiyirnis"),tsc(u8"sawatu")},.abmon={tsc(u8"ini"),tsc(u8"phi"),tsc(u8"mar"),tsc(u8"awr"),tsc(u8"may"),tsc(u8"hun"),tsc(u8"hul"),tsc(u8"agu"),tsc(u8"sip"),tsc(u8"ukt"),tsc(u8"nuw"),tsc(u8"tis")},.mon={tsc(u8"iniru"),tsc(u8"phiwriru"),tsc(u8"marsu"),tsc(u8"awril"),tsc(u8"mayu"),tsc(u8"huniyu"),tsc(u8"huliyu"),tsc(u8"agustu"),tsc(u8"siptiyimri"),tsc(u8"uktuwri"),tsc(u8"nuwiyimri"),tsc(u8"tisiyimri")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d//%m//%y"),.t_fmt=tsc(u8"%I:%M:%S %p"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p"),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8"AM"),tsc(u8"PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u8"^[+1aAsSyY]"),.noexpr=tsc(u8"^[-0mMnN]"),.yesstr=tsc(u8"Arí"),.nostr=tsc(u8"Manan")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"51")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_ab2=tsc(u8"PE"),.country_ab3=tsc(u8"PER"),.country_num=604,.country_car=tsc(u8"PE"),.lang_name=tsc(u8"Qusqu runasimi"),.lang_term=tsc(u8"quz"),.lang_lib=tsc(u8"quz")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Cusco Quechua locale for Peru"),.source=tsc(u"Sugar Labs // OLPC\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"sugarlabs.org\t\t;\t\tfast_io"),.email=tsc(u"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Cusco Quechua"),.territory=tsc(u"Peru"),.revision=tsc(u"1.0"),.date=tsc(u"2013-08-24")},.monetary={.int_curr_symbol=tsc(u"PEN "),.currency_symbol=tsc(u"S//"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"tum"),tsc(u"lun"),tsc(u"mar"),tsc(u"miy"),tsc(u"juy"),tsc(u"wiy"),tsc(u"saw")},.day={tsc(u"tuminku"),tsc(u"lunis"),tsc(u"martis"),tsc(u"miyirkulis"),tsc(u"juywis"),tsc(u"wiyirnis"),tsc(u"sawatu")},.abmon={tsc(u"ini"),tsc(u"phi"),tsc(u"mar"),tsc(u"awr"),tsc(u"may"),tsc(u"hun"),tsc(u"hul"),tsc(u"agu"),tsc(u"sip"),tsc(u"ukt"),tsc(u"nuw"),tsc(u"tis")},.mon={tsc(u"iniru"),tsc(u"phiwriru"),tsc(u"marsu"),tsc(u"awril"),tsc(u"mayu"),tsc(u"huniyu"),tsc(u"huliyu"),tsc(u"agustu"),tsc(u"siptiyimri"),tsc(u"uktuwri"),tsc(u"nuwiyimri"),tsc(u"tisiyimri")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d//%m//%y"),.t_fmt=tsc(u"%I:%M:%S %p"),.t_fmt_ampm=tsc(u"%I:%M:%S %p"),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u"AM"),tsc(u"PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u"^[+1aAsSyY]"),.noexpr=tsc(u"^[-0mMnN]"),.yesstr=tsc(u"Arí"),.nostr=tsc(u"Manan")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"51")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_ab2=tsc(u"PE"),.country_ab3=tsc(u"PER"),.country_num=604,.country_car=tsc(u"PE"),.lang_name=tsc(u"Qusqu runasimi"),.lang_term=tsc(u"quz"),.lang_lib=tsc(u"quz")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Cusco Quechua locale for Peru"),.source=tsc(U"Sugar Labs // OLPC\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"sugarlabs.org\t\t;\t\tfast_io"),.email=tsc(U"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Cusco Quechua"),.territory=tsc(U"Peru"),.revision=tsc(U"1.0"),.date=tsc(U"2013-08-24")},.monetary={.int_curr_symbol=tsc(U"PEN "),.currency_symbol=tsc(U"S//"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"tum"),tsc(U"lun"),tsc(U"mar"),tsc(U"miy"),tsc(U"juy"),tsc(U"wiy"),tsc(U"saw")},.day={tsc(U"tuminku"),tsc(U"lunis"),tsc(U"martis"),tsc(U"miyirkulis"),tsc(U"juywis"),tsc(U"wiyirnis"),tsc(U"sawatu")},.abmon={tsc(U"ini"),tsc(U"phi"),tsc(U"mar"),tsc(U"awr"),tsc(U"may"),tsc(U"hun"),tsc(U"hul"),tsc(U"agu"),tsc(U"sip"),tsc(U"ukt"),tsc(U"nuw"),tsc(U"tis")},.mon={tsc(U"iniru"),tsc(U"phiwriru"),tsc(U"marsu"),tsc(U"awril"),tsc(U"mayu"),tsc(U"huniyu"),tsc(U"huliyu"),tsc(U"agustu"),tsc(U"siptiyimri"),tsc(U"uktuwri"),tsc(U"nuwiyimri"),tsc(U"tisiyimri")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d//%m//%y"),.t_fmt=tsc(U"%I:%M:%S %p"),.t_fmt_ampm=tsc(U"%I:%M:%S %p"),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U"AM"),tsc(U"PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(U"^[+1aAsSyY]"),.noexpr=tsc(U"^[-0mMnN]"),.yesstr=tsc(U"Arí"),.nostr=tsc(U"Manan")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"51")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_ab2=tsc(U"PE"),.country_ab3=tsc(U"PER"),.country_num=604,.country_car=tsc(U"PE"),.lang_name=tsc(U"Qusqu runasimi"),.lang_term=tsc(U"quz"),.lang_lib=tsc(U"quz")},.measurement={.measurement=1}};


}
}

#include"../main.h"