#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t monetary_mon_grouping_storage[]{3,2};

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Santali language locale for India"),.source=tsc("Red Hat Pune\t\t;\t\tfast_io"),.address=tsc("Level 1, Tower X, Cybercity, Magarpatta City, Hadapsar, Pune-411013 \t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Santali"),.territory=tsc("India"),.revision=tsc("1.0"),.date=tsc("2012-01-17")},.monetary={.int_curr_symbol=tsc("INR "),.currency_symbol=tsc("₹"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("सिंगे"),tsc("ओते"),tsc("बाले"),tsc("सागुन"),tsc("सारदी"),tsc("जारुम"),tsc("ञुहुम")},.day={tsc("सिंगेमाँहाँ"),tsc("ओतेमाँहाँ"),tsc("बालेमाँहाँ"),tsc("सागुनमाँहाँ"),tsc("सारदीमाँहाँ"),tsc("जारुममाँहाँ"),tsc("ञुहुममाँहाँ")},.abmon={tsc("जनवरी"),tsc("फरवरी"),tsc("मार्च"),tsc("अप्रेल"),tsc("मई"),tsc("जुन"),tsc("जुलाई"),tsc("अगस्त"),tsc("सितम्बर"),tsc("अखथबर"),tsc("नवम्बर"),tsc("दिसम्बर")},.mon={tsc("जनवरी"),tsc("फरवरी"),tsc("मार्च"),tsc("अप्रेल"),tsc("मई"),tsc("जुन"),tsc("जुलाई"),tsc("अगस्त"),tsc("सितम्बर"),tsc("अखथबर"),tsc("नवम्बर"),tsc("दिसम्बर")},.d_t_fmt=tsc("%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc("%-d//%-m//%y"),.t_fmt=tsc("%I:%M:%S %p %Z"),.t_fmt_ampm=tsc("%I:%M:%S %p %Z"),.date_fmt=tsc("%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc("AM"),tsc("PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc("^[+1yYह]"),.noexpr=tsc("^[-0nNब]"),.yesstr=tsc("होय"),.nostr=tsc("बाङ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c ;%a ;%l"),.int_select=tsc("00"),.int_prefix=tsc("91")},.name={.name_fmt=tsc("%p%t%f%t%g"),.name_gen=tsc(""),.name_miss=tsc("माई"),.name_mr=tsc("मान"),.name_mrs=tsc("मानी"),.name_ms=tsc("")},.address={.postal_fmt=tsc("%z%c%T%s%b%e%r"),.country_name=tsc("ᱥᱤᱧᱚᱛ"),.country_ab2=tsc("IN"),.country_ab3=tsc("IND"),.country_num=356,.country_car=tsc("IND"),.lang_name=tsc("ᱥᱟᱱᱛᱟᱲᱤ"),.lang_term=tsc("sat"),.lang_lib=tsc("sat")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Santali language locale for India"),.source=tsc(L"Red Hat Pune\t\t;\t\tfast_io"),.address=tsc(L"Level 1, Tower X, Cybercity, Magarpatta City, Hadapsar, Pune-411013 \t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Santali"),.territory=tsc(L"India"),.revision=tsc(L"1.0"),.date=tsc(L"2012-01-17")},.monetary={.int_curr_symbol=tsc(L"INR "),.currency_symbol=tsc(L"₹"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"सिंगे"),tsc(L"ओते"),tsc(L"बाले"),tsc(L"सागुन"),tsc(L"सारदी"),tsc(L"जारुम"),tsc(L"ञुहुम")},.day={tsc(L"सिंगेमाँहाँ"),tsc(L"ओतेमाँहाँ"),tsc(L"बालेमाँहाँ"),tsc(L"सागुनमाँहाँ"),tsc(L"सारदीमाँहाँ"),tsc(L"जारुममाँहाँ"),tsc(L"ञुहुममाँहाँ")},.abmon={tsc(L"जनवरी"),tsc(L"फरवरी"),tsc(L"मार्च"),tsc(L"अप्रेल"),tsc(L"मई"),tsc(L"जुन"),tsc(L"जुलाई"),tsc(L"अगस्त"),tsc(L"सितम्बर"),tsc(L"अखथबर"),tsc(L"नवम्बर"),tsc(L"दिसम्बर")},.mon={tsc(L"जनवरी"),tsc(L"फरवरी"),tsc(L"मार्च"),tsc(L"अप्रेल"),tsc(L"मई"),tsc(L"जुन"),tsc(L"जुलाई"),tsc(L"अगस्त"),tsc(L"सितम्बर"),tsc(L"अखथबर"),tsc(L"नवम्बर"),tsc(L"दिसम्बर")},.d_t_fmt=tsc(L"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(L"%-d//%-m//%y"),.t_fmt=tsc(L"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(L"%I:%M:%S %p %Z"),.date_fmt=tsc(L"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(L"AM"),tsc(L"PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(L"^[+1yYह]"),.noexpr=tsc(L"^[-0nNब]"),.yesstr=tsc(L"होय"),.nostr=tsc(L"बाङ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c ;%a ;%l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"91")},.name={.name_fmt=tsc(L"%p%t%f%t%g"),.name_gen=tsc(L""),.name_miss=tsc(L"माई"),.name_mr=tsc(L"मान"),.name_mrs=tsc(L"मानी"),.name_ms=tsc(L"")},.address={.postal_fmt=tsc(L"%z%c%T%s%b%e%r"),.country_name=tsc(L"ᱥᱤᱧᱚᱛ"),.country_ab2=tsc(L"IN"),.country_ab3=tsc(L"IND"),.country_num=356,.country_car=tsc(L"IND"),.lang_name=tsc(L"ᱥᱟᱱᱛᱟᱲᱤ"),.lang_term=tsc(L"sat"),.lang_lib=tsc(L"sat")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Santali language locale for India"),.source=tsc(u8"Red Hat Pune\t\t;\t\tfast_io"),.address=tsc(u8"Level 1, Tower X, Cybercity, Magarpatta City, Hadapsar, Pune-411013 \t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Santali"),.territory=tsc(u8"India"),.revision=tsc(u8"1.0"),.date=tsc(u8"2012-01-17")},.monetary={.int_curr_symbol=tsc(u8"INR "),.currency_symbol=tsc(u8"₹"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"सिंगे"),tsc(u8"ओते"),tsc(u8"बाले"),tsc(u8"सागुन"),tsc(u8"सारदी"),tsc(u8"जारुम"),tsc(u8"ञुहुम")},.day={tsc(u8"सिंगेमाँहाँ"),tsc(u8"ओतेमाँहाँ"),tsc(u8"बालेमाँहाँ"),tsc(u8"सागुनमाँहाँ"),tsc(u8"सारदीमाँहाँ"),tsc(u8"जारुममाँहाँ"),tsc(u8"ञुहुममाँहाँ")},.abmon={tsc(u8"जनवरी"),tsc(u8"फरवरी"),tsc(u8"मार्च"),tsc(u8"अप्रेल"),tsc(u8"मई"),tsc(u8"जुन"),tsc(u8"जुलाई"),tsc(u8"अगस्त"),tsc(u8"सितम्बर"),tsc(u8"अखथबर"),tsc(u8"नवम्बर"),tsc(u8"दिसम्बर")},.mon={tsc(u8"जनवरी"),tsc(u8"फरवरी"),tsc(u8"मार्च"),tsc(u8"अप्रेल"),tsc(u8"मई"),tsc(u8"जुन"),tsc(u8"जुलाई"),tsc(u8"अगस्त"),tsc(u8"सितम्बर"),tsc(u8"अखथबर"),tsc(u8"नवम्बर"),tsc(u8"दिसम्बर")},.d_t_fmt=tsc(u8"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(u8"%-d//%-m//%y"),.t_fmt=tsc(u8"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(u8"%I:%M:%S %p %Z"),.date_fmt=tsc(u8"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(u8"AM"),tsc(u8"PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u8"^[+1yYह]"),.noexpr=tsc(u8"^[-0nNब]"),.yesstr=tsc(u8"होय"),.nostr=tsc(u8"बाङ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c ;%a ;%l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"91")},.name={.name_fmt=tsc(u8"%p%t%f%t%g"),.name_gen=tsc(u8""),.name_miss=tsc(u8"माई"),.name_mr=tsc(u8"मान"),.name_mrs=tsc(u8"मानी"),.name_ms=tsc(u8"")},.address={.postal_fmt=tsc(u8"%z%c%T%s%b%e%r"),.country_name=tsc(u8"ᱥᱤᱧᱚᱛ"),.country_ab2=tsc(u8"IN"),.country_ab3=tsc(u8"IND"),.country_num=356,.country_car=tsc(u8"IND"),.lang_name=tsc(u8"ᱥᱟᱱᱛᱟᱲᱤ"),.lang_term=tsc(u8"sat"),.lang_lib=tsc(u8"sat")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Santali language locale for India"),.source=tsc(u"Red Hat Pune\t\t;\t\tfast_io"),.address=tsc(u"Level 1, Tower X, Cybercity, Magarpatta City, Hadapsar, Pune-411013 \t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Santali"),.territory=tsc(u"India"),.revision=tsc(u"1.0"),.date=tsc(u"2012-01-17")},.monetary={.int_curr_symbol=tsc(u"INR "),.currency_symbol=tsc(u"₹"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"सिंगे"),tsc(u"ओते"),tsc(u"बाले"),tsc(u"सागुन"),tsc(u"सारदी"),tsc(u"जारुम"),tsc(u"ञुहुम")},.day={tsc(u"सिंगेमाँहाँ"),tsc(u"ओतेमाँहाँ"),tsc(u"बालेमाँहाँ"),tsc(u"सागुनमाँहाँ"),tsc(u"सारदीमाँहाँ"),tsc(u"जारुममाँहाँ"),tsc(u"ञुहुममाँहाँ")},.abmon={tsc(u"जनवरी"),tsc(u"फरवरी"),tsc(u"मार्च"),tsc(u"अप्रेल"),tsc(u"मई"),tsc(u"जुन"),tsc(u"जुलाई"),tsc(u"अगस्त"),tsc(u"सितम्बर"),tsc(u"अखथबर"),tsc(u"नवम्बर"),tsc(u"दिसम्बर")},.mon={tsc(u"जनवरी"),tsc(u"फरवरी"),tsc(u"मार्च"),tsc(u"अप्रेल"),tsc(u"मई"),tsc(u"जुन"),tsc(u"जुलाई"),tsc(u"अगस्त"),tsc(u"सितम्बर"),tsc(u"अखथबर"),tsc(u"नवम्बर"),tsc(u"दिसम्बर")},.d_t_fmt=tsc(u"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(u"%-d//%-m//%y"),.t_fmt=tsc(u"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(u"%I:%M:%S %p %Z"),.date_fmt=tsc(u"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(u"AM"),tsc(u"PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u"^[+1yYह]"),.noexpr=tsc(u"^[-0nNब]"),.yesstr=tsc(u"होय"),.nostr=tsc(u"बाङ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c ;%a ;%l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"91")},.name={.name_fmt=tsc(u"%p%t%f%t%g"),.name_gen=tsc(u""),.name_miss=tsc(u"माई"),.name_mr=tsc(u"मान"),.name_mrs=tsc(u"मानी"),.name_ms=tsc(u"")},.address={.postal_fmt=tsc(u"%z%c%T%s%b%e%r"),.country_name=tsc(u"ᱥᱤᱧᱚᱛ"),.country_ab2=tsc(u"IN"),.country_ab3=tsc(u"IND"),.country_num=356,.country_car=tsc(u"IND"),.lang_name=tsc(u"ᱥᱟᱱᱛᱟᱲᱤ"),.lang_term=tsc(u"sat"),.lang_lib=tsc(u"sat")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Santali language locale for India"),.source=tsc(U"Red Hat Pune\t\t;\t\tfast_io"),.address=tsc(U"Level 1, Tower X, Cybercity, Magarpatta City, Hadapsar, Pune-411013 \t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Santali"),.territory=tsc(U"India"),.revision=tsc(U"1.0"),.date=tsc(U"2012-01-17")},.monetary={.int_curr_symbol=tsc(U"INR "),.currency_symbol=tsc(U"₹"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={monetary_mon_grouping_storage,2},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"सिंगे"),tsc(U"ओते"),tsc(U"बाले"),tsc(U"सागुन"),tsc(U"सारदी"),tsc(U"जारुम"),tsc(U"ञुहुम")},.day={tsc(U"सिंगेमाँहाँ"),tsc(U"ओतेमाँहाँ"),tsc(U"बालेमाँहाँ"),tsc(U"सागुनमाँहाँ"),tsc(U"सारदीमाँहाँ"),tsc(U"जारुममाँहाँ"),tsc(U"ञुहुममाँहाँ")},.abmon={tsc(U"जनवरी"),tsc(U"फरवरी"),tsc(U"मार्च"),tsc(U"अप्रेल"),tsc(U"मई"),tsc(U"जुन"),tsc(U"जुलाई"),tsc(U"अगस्त"),tsc(U"सितम्बर"),tsc(U"अखथबर"),tsc(U"नवम्बर"),tsc(U"दिसम्बर")},.mon={tsc(U"जनवरी"),tsc(U"फरवरी"),tsc(U"मार्च"),tsc(U"अप्रेल"),tsc(U"मई"),tsc(U"जुन"),tsc(U"जुलाई"),tsc(U"अगस्त"),tsc(U"सितम्बर"),tsc(U"अखथबर"),tsc(U"नवम्बर"),tsc(U"दिसम्बर")},.d_t_fmt=tsc(U"%A %d %b %Y %I:%M:%S %p"),.d_fmt=tsc(U"%-d//%-m//%y"),.t_fmt=tsc(U"%I:%M:%S %p %Z"),.t_fmt_ampm=tsc(U"%I:%M:%S %p %Z"),.date_fmt=tsc(U"%A %d %b %Y %I:%M:%S %p %Z"),.am_pm={tsc(U"AM"),tsc(U"PM")},.week={7,19971130,1}},.messages={.yesexpr=tsc(U"^[+1yYह]"),.noexpr=tsc(U"^[-0nNब]"),.yesstr=tsc(U"होय"),.nostr=tsc(U"बाङ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c ;%a ;%l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"91")},.name={.name_fmt=tsc(U"%p%t%f%t%g"),.name_gen=tsc(U""),.name_miss=tsc(U"माई"),.name_mr=tsc(U"मान"),.name_mrs=tsc(U"मानी"),.name_ms=tsc(U"")},.address={.postal_fmt=tsc(U"%z%c%T%s%b%e%r"),.country_name=tsc(U"ᱥᱤᱧᱚᱛ"),.country_ab2=tsc(U"IN"),.country_ab3=tsc(U"IND"),.country_num=356,.country_car=tsc(U"IND"),.lang_name=tsc(U"ᱥᱟᱱᱛᱟᱲᱤ"),.lang_term=tsc(U"sat"),.lang_lib=tsc(U"sat")},.measurement={.measurement=1}};


}
}

#include"../main.h"