#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Sardinian locale for Italy"),.source=tsc("Sardinian Translators Team\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Massimeddu Cireddu\t\t;\t\tfast_io"),.email=tsc("massimeddu@gmail.com;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Sardinian"),.territory=tsc("Italy"),.revision=tsc("0.2"),.date=tsc("2017-07-21")},.monetary={.int_curr_symbol=tsc("EUR "),.currency_symbol=tsc("€"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc("."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("Dom"),tsc("Lun"),tsc("Mar"),tsc("Mèr"),tsc("Giò"),tsc("Che"),tsc("Sàb")},.day={tsc("Domìnigu"),tsc("Lunis"),tsc("Martis"),tsc("Mèrcuris"),tsc("Giòbia"),tsc("Chenàbura"),tsc("Sàbadu")},.abmon={tsc("Ghe"),tsc("Fre"),tsc("Mar"),tsc("Abr"),tsc("Maj"),tsc("Làm"),tsc("Arg"),tsc("Aus"),tsc("Cab"),tsc("Lad"),tsc("Onn"),tsc("Nad")},.mon={tsc("Ghennàrgiu"),tsc("Freàrgiu"),tsc("Martzu"),tsc("Abrile"),tsc("Maju"),tsc("Làmpadas"),tsc("Argiolas//Trìulas"),tsc("Austu"),tsc("Cabudanni"),tsc("Santugaine//Ladàmine"),tsc("Onniasantu//Santandria"),tsc("Nadale//Idas")},.d_t_fmt=tsc("%a %d %b %Y %T %Z"),.d_fmt=tsc("%d. %m. %y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc("^[+1eEaAsSoOyY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("eja"),.nostr=tsc("nono")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("39")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Itàlia"),.country_ab2=tsc("IT"),.country_ab3=tsc("ITA"),.country_num=380,.country_car=tsc("I"),.country_isbn=tsc("978-88,979-12"),.lang_name=tsc("sardu"),.lang_ab=tsc("sc"),.lang_term=tsc("srd"),.lang_lib=tsc("srd")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Sardinian locale for Italy"),.source=tsc(L"Sardinian Translators Team\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Massimeddu Cireddu\t\t;\t\tfast_io"),.email=tsc(L"massimeddu@gmail.com;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Sardinian"),.territory=tsc(L"Italy"),.revision=tsc(L"0.2"),.date=tsc(L"2017-07-21")},.monetary={.int_curr_symbol=tsc(L"EUR "),.currency_symbol=tsc(L"€"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"Dom"),tsc(L"Lun"),tsc(L"Mar"),tsc(L"Mèr"),tsc(L"Giò"),tsc(L"Che"),tsc(L"Sàb")},.day={tsc(L"Domìnigu"),tsc(L"Lunis"),tsc(L"Martis"),tsc(L"Mèrcuris"),tsc(L"Giòbia"),tsc(L"Chenàbura"),tsc(L"Sàbadu")},.abmon={tsc(L"Ghe"),tsc(L"Fre"),tsc(L"Mar"),tsc(L"Abr"),tsc(L"Maj"),tsc(L"Làm"),tsc(L"Arg"),tsc(L"Aus"),tsc(L"Cab"),tsc(L"Lad"),tsc(L"Onn"),tsc(L"Nad")},.mon={tsc(L"Ghennàrgiu"),tsc(L"Freàrgiu"),tsc(L"Martzu"),tsc(L"Abrile"),tsc(L"Maju"),tsc(L"Làmpadas"),tsc(L"Argiolas//Trìulas"),tsc(L"Austu"),tsc(L"Cabudanni"),tsc(L"Santugaine//Ladàmine"),tsc(L"Onniasantu//Santandria"),tsc(L"Nadale//Idas")},.d_t_fmt=tsc(L"%a %d %b %Y %T %Z"),.d_fmt=tsc(L"%d. %m. %y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1eEaAsSoOyY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"eja"),.nostr=tsc(L"nono")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"39")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Itàlia"),.country_ab2=tsc(L"IT"),.country_ab3=tsc(L"ITA"),.country_num=380,.country_car=tsc(L"I"),.country_isbn=tsc(L"978-88,979-12"),.lang_name=tsc(L"sardu"),.lang_ab=tsc(L"sc"),.lang_term=tsc(L"srd"),.lang_lib=tsc(L"srd")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Sardinian locale for Italy"),.source=tsc(u8"Sardinian Translators Team\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Massimeddu Cireddu\t\t;\t\tfast_io"),.email=tsc(u8"massimeddu@gmail.com;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Sardinian"),.territory=tsc(u8"Italy"),.revision=tsc(u8"0.2"),.date=tsc(u8"2017-07-21")},.monetary={.int_curr_symbol=tsc(u8"EUR "),.currency_symbol=tsc(u8"€"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"Dom"),tsc(u8"Lun"),tsc(u8"Mar"),tsc(u8"Mèr"),tsc(u8"Giò"),tsc(u8"Che"),tsc(u8"Sàb")},.day={tsc(u8"Domìnigu"),tsc(u8"Lunis"),tsc(u8"Martis"),tsc(u8"Mèrcuris"),tsc(u8"Giòbia"),tsc(u8"Chenàbura"),tsc(u8"Sàbadu")},.abmon={tsc(u8"Ghe"),tsc(u8"Fre"),tsc(u8"Mar"),tsc(u8"Abr"),tsc(u8"Maj"),tsc(u8"Làm"),tsc(u8"Arg"),tsc(u8"Aus"),tsc(u8"Cab"),tsc(u8"Lad"),tsc(u8"Onn"),tsc(u8"Nad")},.mon={tsc(u8"Ghennàrgiu"),tsc(u8"Freàrgiu"),tsc(u8"Martzu"),tsc(u8"Abrile"),tsc(u8"Maju"),tsc(u8"Làmpadas"),tsc(u8"Argiolas//Trìulas"),tsc(u8"Austu"),tsc(u8"Cabudanni"),tsc(u8"Santugaine//Ladàmine"),tsc(u8"Onniasantu//Santandria"),tsc(u8"Nadale//Idas")},.d_t_fmt=tsc(u8"%a %d %b %Y %T %Z"),.d_fmt=tsc(u8"%d. %m. %y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1eEaAsSoOyY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"eja"),.nostr=tsc(u8"nono")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"39")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Itàlia"),.country_ab2=tsc(u8"IT"),.country_ab3=tsc(u8"ITA"),.country_num=380,.country_car=tsc(u8"I"),.country_isbn=tsc(u8"978-88,979-12"),.lang_name=tsc(u8"sardu"),.lang_ab=tsc(u8"sc"),.lang_term=tsc(u8"srd"),.lang_lib=tsc(u8"srd")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Sardinian locale for Italy"),.source=tsc(u"Sardinian Translators Team\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Massimeddu Cireddu\t\t;\t\tfast_io"),.email=tsc(u"massimeddu@gmail.com;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Sardinian"),.territory=tsc(u"Italy"),.revision=tsc(u"0.2"),.date=tsc(u"2017-07-21")},.monetary={.int_curr_symbol=tsc(u"EUR "),.currency_symbol=tsc(u"€"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"Dom"),tsc(u"Lun"),tsc(u"Mar"),tsc(u"Mèr"),tsc(u"Giò"),tsc(u"Che"),tsc(u"Sàb")},.day={tsc(u"Domìnigu"),tsc(u"Lunis"),tsc(u"Martis"),tsc(u"Mèrcuris"),tsc(u"Giòbia"),tsc(u"Chenàbura"),tsc(u"Sàbadu")},.abmon={tsc(u"Ghe"),tsc(u"Fre"),tsc(u"Mar"),tsc(u"Abr"),tsc(u"Maj"),tsc(u"Làm"),tsc(u"Arg"),tsc(u"Aus"),tsc(u"Cab"),tsc(u"Lad"),tsc(u"Onn"),tsc(u"Nad")},.mon={tsc(u"Ghennàrgiu"),tsc(u"Freàrgiu"),tsc(u"Martzu"),tsc(u"Abrile"),tsc(u"Maju"),tsc(u"Làmpadas"),tsc(u"Argiolas//Trìulas"),tsc(u"Austu"),tsc(u"Cabudanni"),tsc(u"Santugaine//Ladàmine"),tsc(u"Onniasantu//Santandria"),tsc(u"Nadale//Idas")},.d_t_fmt=tsc(u"%a %d %b %Y %T %Z"),.d_fmt=tsc(u"%d. %m. %y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1eEaAsSoOyY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"eja"),.nostr=tsc(u"nono")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"39")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Itàlia"),.country_ab2=tsc(u"IT"),.country_ab3=tsc(u"ITA"),.country_num=380,.country_car=tsc(u"I"),.country_isbn=tsc(u"978-88,979-12"),.lang_name=tsc(u"sardu"),.lang_ab=tsc(u"sc"),.lang_term=tsc(u"srd"),.lang_lib=tsc(u"srd")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Sardinian locale for Italy"),.source=tsc(U"Sardinian Translators Team\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Massimeddu Cireddu\t\t;\t\tfast_io"),.email=tsc(U"massimeddu@gmail.com;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Sardinian"),.territory=tsc(U"Italy"),.revision=tsc(U"0.2"),.date=tsc(U"2017-07-21")},.monetary={.int_curr_symbol=tsc(U"EUR "),.currency_symbol=tsc(U"€"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U"."),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=1,.n_cs_precedes=1,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"."),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"Dom"),tsc(U"Lun"),tsc(U"Mar"),tsc(U"Mèr"),tsc(U"Giò"),tsc(U"Che"),tsc(U"Sàb")},.day={tsc(U"Domìnigu"),tsc(U"Lunis"),tsc(U"Martis"),tsc(U"Mèrcuris"),tsc(U"Giòbia"),tsc(U"Chenàbura"),tsc(U"Sàbadu")},.abmon={tsc(U"Ghe"),tsc(U"Fre"),tsc(U"Mar"),tsc(U"Abr"),tsc(U"Maj"),tsc(U"Làm"),tsc(U"Arg"),tsc(U"Aus"),tsc(U"Cab"),tsc(U"Lad"),tsc(U"Onn"),tsc(U"Nad")},.mon={tsc(U"Ghennàrgiu"),tsc(U"Freàrgiu"),tsc(U"Martzu"),tsc(U"Abrile"),tsc(U"Maju"),tsc(U"Làmpadas"),tsc(U"Argiolas//Trìulas"),tsc(U"Austu"),tsc(U"Cabudanni"),tsc(U"Santugaine//Ladàmine"),tsc(U"Onniasantu//Santandria"),tsc(U"Nadale//Idas")},.d_t_fmt=tsc(U"%a %d %b %Y %T %Z"),.d_fmt=tsc(U"%d. %m. %y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1eEaAsSoOyY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"eja"),.nostr=tsc(U"nono")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"39")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Itàlia"),.country_ab2=tsc(U"IT"),.country_ab3=tsc(U"ITA"),.country_num=380,.country_car=tsc(U"I"),.country_isbn=tsc(U"978-88,979-12"),.lang_name=tsc(U"sardu"),.lang_ab=tsc(U"sc"),.lang_term=tsc(U"srd"),.lang_lib=tsc(U"srd")},.measurement={.measurement=1}};


}
}

#include"../main.h"