#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Slovak locale for Slovak"),.source=tsc("fast_io"),.address=tsc("Narcisová 56, SK-821 01 Bratislava, Slovak Republic\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Slovak"),.territory=tsc("Slovakia"),.revision=tsc("1.0"),.date=tsc("2000-06-29")},.monetary={.int_curr_symbol=tsc("EUR "),.currency_symbol=tsc("€"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("Ne"),tsc("Po"),tsc("Ut"),tsc("St"),tsc("Št"),tsc("Pi"),tsc("So")},.day={tsc("Nedeľa"),tsc("Pondelok"),tsc("Utorok"),tsc("Streda"),tsc("Štvrtok"),tsc("Piatok"),tsc("Sobota")},.abmon={tsc("jan"),tsc("feb"),tsc("mar"),tsc("apr"),tsc("máj"),tsc("jún"),tsc("júl"),tsc("aug"),tsc("sep"),tsc("okt"),tsc("nov"),tsc("dec")},.mon={tsc("január"),tsc("február"),tsc("marec"),tsc("apríl"),tsc("máj"),tsc("jún"),tsc("júl"),tsc("august"),tsc("september"),tsc("október"),tsc("november"),tsc("december")},.d_t_fmt=tsc("%a %e. %B %Y, %H:%M:%S"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%H:%M:%S"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %e. %B %Y, %H:%M:%S %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc("^[+1aAáÁyY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("áno"),.nostr=tsc("nie")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("421")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Slovensko"),.country_ab2=tsc("SK"),.country_ab3=tsc("SVK"),.country_num=703,.country_car=tsc("SK"),.lang_name=tsc("slovenčina"),.lang_ab=tsc("sk"),.lang_term=tsc("slk"),.lang_lib=tsc("slo")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Slovak locale for Slovak"),.source=tsc(L"fast_io"),.address=tsc(L"Narcisová 56, SK-821 01 Bratislava, Slovak Republic\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Slovak"),.territory=tsc(L"Slovakia"),.revision=tsc(L"1.0"),.date=tsc(L"2000-06-29")},.monetary={.int_curr_symbol=tsc(L"EUR "),.currency_symbol=tsc(L"€"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"Ne"),tsc(L"Po"),tsc(L"Ut"),tsc(L"St"),tsc(L"Št"),tsc(L"Pi"),tsc(L"So")},.day={tsc(L"Nedeľa"),tsc(L"Pondelok"),tsc(L"Utorok"),tsc(L"Streda"),tsc(L"Štvrtok"),tsc(L"Piatok"),tsc(L"Sobota")},.abmon={tsc(L"jan"),tsc(L"feb"),tsc(L"mar"),tsc(L"apr"),tsc(L"máj"),tsc(L"jún"),tsc(L"júl"),tsc(L"aug"),tsc(L"sep"),tsc(L"okt"),tsc(L"nov"),tsc(L"dec")},.mon={tsc(L"január"),tsc(L"február"),tsc(L"marec"),tsc(L"apríl"),tsc(L"máj"),tsc(L"jún"),tsc(L"júl"),tsc(L"august"),tsc(L"september"),tsc(L"október"),tsc(L"november"),tsc(L"december")},.d_t_fmt=tsc(L"%a %e. %B %Y, %H:%M:%S"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%H:%M:%S"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %e. %B %Y, %H:%M:%S %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1aAáÁyY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"áno"),.nostr=tsc(L"nie")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"421")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Slovensko"),.country_ab2=tsc(L"SK"),.country_ab3=tsc(L"SVK"),.country_num=703,.country_car=tsc(L"SK"),.lang_name=tsc(L"slovenčina"),.lang_ab=tsc(L"sk"),.lang_term=tsc(L"slk"),.lang_lib=tsc(L"slo")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Slovak locale for Slovak"),.source=tsc(u8"fast_io"),.address=tsc(u8"Narcisová 56, SK-821 01 Bratislava, Slovak Republic\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Slovak"),.territory=tsc(u8"Slovakia"),.revision=tsc(u8"1.0"),.date=tsc(u8"2000-06-29")},.monetary={.int_curr_symbol=tsc(u8"EUR "),.currency_symbol=tsc(u8"€"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"Ne"),tsc(u8"Po"),tsc(u8"Ut"),tsc(u8"St"),tsc(u8"Št"),tsc(u8"Pi"),tsc(u8"So")},.day={tsc(u8"Nedeľa"),tsc(u8"Pondelok"),tsc(u8"Utorok"),tsc(u8"Streda"),tsc(u8"Štvrtok"),tsc(u8"Piatok"),tsc(u8"Sobota")},.abmon={tsc(u8"jan"),tsc(u8"feb"),tsc(u8"mar"),tsc(u8"apr"),tsc(u8"máj"),tsc(u8"jún"),tsc(u8"júl"),tsc(u8"aug"),tsc(u8"sep"),tsc(u8"okt"),tsc(u8"nov"),tsc(u8"dec")},.mon={tsc(u8"január"),tsc(u8"február"),tsc(u8"marec"),tsc(u8"apríl"),tsc(u8"máj"),tsc(u8"jún"),tsc(u8"júl"),tsc(u8"august"),tsc(u8"september"),tsc(u8"október"),tsc(u8"november"),tsc(u8"december")},.d_t_fmt=tsc(u8"%a %e. %B %Y, %H:%M:%S"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%H:%M:%S"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %e. %B %Y, %H:%M:%S %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1aAáÁyY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"áno"),.nostr=tsc(u8"nie")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"421")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Slovensko"),.country_ab2=tsc(u8"SK"),.country_ab3=tsc(u8"SVK"),.country_num=703,.country_car=tsc(u8"SK"),.lang_name=tsc(u8"slovenčina"),.lang_ab=tsc(u8"sk"),.lang_term=tsc(u8"slk"),.lang_lib=tsc(u8"slo")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Slovak locale for Slovak"),.source=tsc(u"fast_io"),.address=tsc(u"Narcisová 56, SK-821 01 Bratislava, Slovak Republic\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Slovak"),.territory=tsc(u"Slovakia"),.revision=tsc(u"1.0"),.date=tsc(u"2000-06-29")},.monetary={.int_curr_symbol=tsc(u"EUR "),.currency_symbol=tsc(u"€"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"Ne"),tsc(u"Po"),tsc(u"Ut"),tsc(u"St"),tsc(u"Št"),tsc(u"Pi"),tsc(u"So")},.day={tsc(u"Nedeľa"),tsc(u"Pondelok"),tsc(u"Utorok"),tsc(u"Streda"),tsc(u"Štvrtok"),tsc(u"Piatok"),tsc(u"Sobota")},.abmon={tsc(u"jan"),tsc(u"feb"),tsc(u"mar"),tsc(u"apr"),tsc(u"máj"),tsc(u"jún"),tsc(u"júl"),tsc(u"aug"),tsc(u"sep"),tsc(u"okt"),tsc(u"nov"),tsc(u"dec")},.mon={tsc(u"január"),tsc(u"február"),tsc(u"marec"),tsc(u"apríl"),tsc(u"máj"),tsc(u"jún"),tsc(u"júl"),tsc(u"august"),tsc(u"september"),tsc(u"október"),tsc(u"november"),tsc(u"december")},.d_t_fmt=tsc(u"%a %e. %B %Y, %H:%M:%S"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%H:%M:%S"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %e. %B %Y, %H:%M:%S %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1aAáÁyY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"áno"),.nostr=tsc(u"nie")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"421")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Slovensko"),.country_ab2=tsc(u"SK"),.country_ab3=tsc(u"SVK"),.country_num=703,.country_car=tsc(u"SK"),.lang_name=tsc(u"slovenčina"),.lang_ab=tsc(u"sk"),.lang_term=tsc(u"slk"),.lang_lib=tsc(u"slo")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Slovak locale for Slovak"),.source=tsc(U"fast_io"),.address=tsc(U"Narcisová 56, SK-821 01 Bratislava, Slovak Republic\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Slovak"),.territory=tsc(U"Slovakia"),.revision=tsc(U"1.0"),.date=tsc(U"2000-06-29")},.monetary={.int_curr_symbol=tsc(U"EUR "),.currency_symbol=tsc(U"€"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"Ne"),tsc(U"Po"),tsc(U"Ut"),tsc(U"St"),tsc(U"Št"),tsc(U"Pi"),tsc(U"So")},.day={tsc(U"Nedeľa"),tsc(U"Pondelok"),tsc(U"Utorok"),tsc(U"Streda"),tsc(U"Štvrtok"),tsc(U"Piatok"),tsc(U"Sobota")},.abmon={tsc(U"jan"),tsc(U"feb"),tsc(U"mar"),tsc(U"apr"),tsc(U"máj"),tsc(U"jún"),tsc(U"júl"),tsc(U"aug"),tsc(U"sep"),tsc(U"okt"),tsc(U"nov"),tsc(U"dec")},.mon={tsc(U"január"),tsc(U"február"),tsc(U"marec"),tsc(U"apríl"),tsc(U"máj"),tsc(U"jún"),tsc(U"júl"),tsc(U"august"),tsc(U"september"),tsc(U"október"),tsc(U"november"),tsc(U"december")},.d_t_fmt=tsc(U"%a %e. %B %Y, %H:%M:%S"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%H:%M:%S"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %e. %B %Y, %H:%M:%S %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1aAáÁyY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"áno"),.nostr=tsc(U"nie")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"421")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Slovensko"),.country_ab2=tsc(U"SK"),.country_ab3=tsc(U"SVK"),.country_num=703,.country_car=tsc(U"SK"),.lang_name=tsc(U"slovenčina"),.lang_ab=tsc(U"sk"),.lang_term=tsc(U"slk"),.lang_lib=tsc(U"slo")},.measurement={.measurement=1}};


}
}

#include"../main.h"