#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t monetary_mon_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Slovenian locale for Slovenia"),.source=tsc("USM//MZT\t\t;\t\tfast_io"),.address=tsc("Kotnikova 6,, Ljubljana, Slovenia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Slovenian"),.territory=tsc("Slovenia"),.revision=tsc("1.0"),.date=tsc("2000-06-29")},.monetary={.int_curr_symbol=tsc("EUR "),.currency_symbol=tsc("€"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc("."),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(".")},.time={.abday={tsc("ned"),tsc("pon"),tsc("tor"),tsc("sre"),tsc("čet"),tsc("pet"),tsc("sob")},.day={tsc("nedelja"),tsc("ponedeljek"),tsc("torek"),tsc("sreda"),tsc("četrtek"),tsc("petek"),tsc("sobota")},.abmon={tsc("jan"),tsc("feb"),tsc("mar"),tsc("apr"),tsc("maj"),tsc("jun"),tsc("jul"),tsc("avg"),tsc("sep"),tsc("okt"),tsc("nov"),tsc("dec")},.mon={tsc("januar"),tsc("februar"),tsc("marec"),tsc("april"),tsc("maj"),tsc("junij"),tsc("julij"),tsc("avgust"),tsc("september"),tsc("oktober"),tsc("november"),tsc("december")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d. %m. %Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1YyJj]"),.noexpr=tsc("^[-0Nn]"),.yesstr=tsc("da"),.nostr=tsc("ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("386")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Slovenija"),.country_ab2=tsc("SI"),.country_ab3=tsc("SVN"),.country_num=705,.country_car=tsc("SLO"),.lang_name=tsc("slovenščina"),.lang_ab=tsc("sl"),.lang_term=tsc("slv"),.lang_lib=tsc("slv")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Slovenian locale for Slovenia"),.source=tsc(L"USM//MZT\t\t;\t\tfast_io"),.address=tsc(L"Kotnikova 6,, Ljubljana, Slovenia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Slovenian"),.territory=tsc(L"Slovenia"),.revision=tsc(L"1.0"),.date=tsc(L"2000-06-29")},.monetary={.int_curr_symbol=tsc(L"EUR "),.currency_symbol=tsc(L"€"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L"."),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L".")},.time={.abday={tsc(L"ned"),tsc(L"pon"),tsc(L"tor"),tsc(L"sre"),tsc(L"čet"),tsc(L"pet"),tsc(L"sob")},.day={tsc(L"nedelja"),tsc(L"ponedeljek"),tsc(L"torek"),tsc(L"sreda"),tsc(L"četrtek"),tsc(L"petek"),tsc(L"sobota")},.abmon={tsc(L"jan"),tsc(L"feb"),tsc(L"mar"),tsc(L"apr"),tsc(L"maj"),tsc(L"jun"),tsc(L"jul"),tsc(L"avg"),tsc(L"sep"),tsc(L"okt"),tsc(L"nov"),tsc(L"dec")},.mon={tsc(L"januar"),tsc(L"februar"),tsc(L"marec"),tsc(L"april"),tsc(L"maj"),tsc(L"junij"),tsc(L"julij"),tsc(L"avgust"),tsc(L"september"),tsc(L"oktober"),tsc(L"november"),tsc(L"december")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d. %m. %Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1YyJj]"),.noexpr=tsc(L"^[-0Nn]"),.yesstr=tsc(L"da"),.nostr=tsc(L"ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"386")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Slovenija"),.country_ab2=tsc(L"SI"),.country_ab3=tsc(L"SVN"),.country_num=705,.country_car=tsc(L"SLO"),.lang_name=tsc(L"slovenščina"),.lang_ab=tsc(L"sl"),.lang_term=tsc(L"slv"),.lang_lib=tsc(L"slv")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Slovenian locale for Slovenia"),.source=tsc(u8"USM//MZT\t\t;\t\tfast_io"),.address=tsc(u8"Kotnikova 6,, Ljubljana, Slovenia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Slovenian"),.territory=tsc(u8"Slovenia"),.revision=tsc(u8"1.0"),.date=tsc(u8"2000-06-29")},.monetary={.int_curr_symbol=tsc(u8"EUR "),.currency_symbol=tsc(u8"€"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8"."),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8".")},.time={.abday={tsc(u8"ned"),tsc(u8"pon"),tsc(u8"tor"),tsc(u8"sre"),tsc(u8"čet"),tsc(u8"pet"),tsc(u8"sob")},.day={tsc(u8"nedelja"),tsc(u8"ponedeljek"),tsc(u8"torek"),tsc(u8"sreda"),tsc(u8"četrtek"),tsc(u8"petek"),tsc(u8"sobota")},.abmon={tsc(u8"jan"),tsc(u8"feb"),tsc(u8"mar"),tsc(u8"apr"),tsc(u8"maj"),tsc(u8"jun"),tsc(u8"jul"),tsc(u8"avg"),tsc(u8"sep"),tsc(u8"okt"),tsc(u8"nov"),tsc(u8"dec")},.mon={tsc(u8"januar"),tsc(u8"februar"),tsc(u8"marec"),tsc(u8"april"),tsc(u8"maj"),tsc(u8"junij"),tsc(u8"julij"),tsc(u8"avgust"),tsc(u8"september"),tsc(u8"oktober"),tsc(u8"november"),tsc(u8"december")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d. %m. %Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1YyJj]"),.noexpr=tsc(u8"^[-0Nn]"),.yesstr=tsc(u8"da"),.nostr=tsc(u8"ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"386")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Slovenija"),.country_ab2=tsc(u8"SI"),.country_ab3=tsc(u8"SVN"),.country_num=705,.country_car=tsc(u8"SLO"),.lang_name=tsc(u8"slovenščina"),.lang_ab=tsc(u8"sl"),.lang_term=tsc(u8"slv"),.lang_lib=tsc(u8"slv")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Slovenian locale for Slovenia"),.source=tsc(u"USM//MZT\t\t;\t\tfast_io"),.address=tsc(u"Kotnikova 6,, Ljubljana, Slovenia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Slovenian"),.territory=tsc(u"Slovenia"),.revision=tsc(u"1.0"),.date=tsc(u"2000-06-29")},.monetary={.int_curr_symbol=tsc(u"EUR "),.currency_symbol=tsc(u"€"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u"."),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u".")},.time={.abday={tsc(u"ned"),tsc(u"pon"),tsc(u"tor"),tsc(u"sre"),tsc(u"čet"),tsc(u"pet"),tsc(u"sob")},.day={tsc(u"nedelja"),tsc(u"ponedeljek"),tsc(u"torek"),tsc(u"sreda"),tsc(u"četrtek"),tsc(u"petek"),tsc(u"sobota")},.abmon={tsc(u"jan"),tsc(u"feb"),tsc(u"mar"),tsc(u"apr"),tsc(u"maj"),tsc(u"jun"),tsc(u"jul"),tsc(u"avg"),tsc(u"sep"),tsc(u"okt"),tsc(u"nov"),tsc(u"dec")},.mon={tsc(u"januar"),tsc(u"februar"),tsc(u"marec"),tsc(u"april"),tsc(u"maj"),tsc(u"junij"),tsc(u"julij"),tsc(u"avgust"),tsc(u"september"),tsc(u"oktober"),tsc(u"november"),tsc(u"december")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d. %m. %Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1YyJj]"),.noexpr=tsc(u"^[-0Nn]"),.yesstr=tsc(u"da"),.nostr=tsc(u"ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"386")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Slovenija"),.country_ab2=tsc(u"SI"),.country_ab3=tsc(u"SVN"),.country_num=705,.country_car=tsc(u"SLO"),.lang_name=tsc(u"slovenščina"),.lang_ab=tsc(u"sl"),.lang_term=tsc(u"slv"),.lang_lib=tsc(u"slv")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Slovenian locale for Slovenia"),.source=tsc(U"USM//MZT\t\t;\t\tfast_io"),.address=tsc(U"Kotnikova 6,, Ljubljana, Slovenia\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Slovenian"),.territory=tsc(U"Slovenia"),.revision=tsc(U"1.0"),.date=tsc(U"2000-06-29")},.monetary={.int_curr_symbol=tsc(U"EUR "),.currency_symbol=tsc(U"€"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U"."),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U".")},.time={.abday={tsc(U"ned"),tsc(U"pon"),tsc(U"tor"),tsc(U"sre"),tsc(U"čet"),tsc(U"pet"),tsc(U"sob")},.day={tsc(U"nedelja"),tsc(U"ponedeljek"),tsc(U"torek"),tsc(U"sreda"),tsc(U"četrtek"),tsc(U"petek"),tsc(U"sobota")},.abmon={tsc(U"jan"),tsc(U"feb"),tsc(U"mar"),tsc(U"apr"),tsc(U"maj"),tsc(U"jun"),tsc(U"jul"),tsc(U"avg"),tsc(U"sep"),tsc(U"okt"),tsc(U"nov"),tsc(U"dec")},.mon={tsc(U"januar"),tsc(U"februar"),tsc(U"marec"),tsc(U"april"),tsc(U"maj"),tsc(U"junij"),tsc(U"julij"),tsc(U"avgust"),tsc(U"september"),tsc(U"oktober"),tsc(U"november"),tsc(U"december")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d. %m. %Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1YyJj]"),.noexpr=tsc(U"^[-0Nn]"),.yesstr=tsc(U"da"),.nostr=tsc(U"ne")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"386")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Slovenija"),.country_ab2=tsc(U"SI"),.country_ab3=tsc(U"SVN"),.country_num=705,.country_car=tsc(U"SLO"),.lang_name=tsc(U"slovenščina"),.lang_ab=tsc(U"sl"),.lang_term=tsc(U"slv"),.lang_lib=tsc(U"slv")},.measurement={.measurement=1}};


}
}

#include"../main.h"