#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Swedish locale for Sweden"),.source=tsc("RAP\t\t;\t\tfast_io"),.address=tsc("Sankt Jørgens Alle 8, DK-1615 København V, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Swedish"),.territory=tsc("Sweden"),.revision=tsc("1.0"),.date=tsc("2000-06-29")},.monetary={.int_curr_symbol=tsc("SEK "),.currency_symbol=tsc("kr"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("sön"),tsc("mån"),tsc("tis"),tsc("ons"),tsc("tor"),tsc("fre"),tsc("lör")},.day={tsc("söndag"),tsc("måndag"),tsc("tisdag"),tsc("onsdag"),tsc("torsdag"),tsc("fredag"),tsc("lördag")},.abmon={tsc("jan"),tsc("feb"),tsc("mar"),tsc("apr"),tsc("maj"),tsc("jun"),tsc("jul"),tsc("aug"),tsc("sep"),tsc("okt"),tsc("nov"),tsc("dec")},.mon={tsc("januari"),tsc("februari"),tsc("mars"),tsc("april"),tsc("maj"),tsc("juni"),tsc("juli"),tsc("augusti"),tsc("september"),tsc("oktober"),tsc("november"),tsc("december")},.d_t_fmt=tsc("%a %e %b %Y %H:%M:%S"),.d_fmt=tsc("%Y-%m-%d"),.t_fmt=tsc("%H:%M:%S"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc("^[+1jJyY]"),.noexpr=tsc("^[-0nN]"),.yesstr=tsc("ja"),.nostr=tsc("nej")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c-%a-%l"),.tel_dom_fmt=tsc("0%a-%l"),.int_select=tsc("00"),.int_prefix=tsc("46")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Sverige"),.country_ab2=tsc("SE"),.country_ab3=tsc("SWE"),.country_num=752,.country_car=tsc("S"),.lang_name=tsc("svenska"),.lang_ab=tsc("sv"),.lang_term=tsc("swe"),.lang_lib=tsc("swe")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Swedish locale for Sweden"),.source=tsc(L"RAP\t\t;\t\tfast_io"),.address=tsc(L"Sankt Jørgens Alle 8, DK-1615 København V, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Swedish"),.territory=tsc(L"Sweden"),.revision=tsc(L"1.0"),.date=tsc(L"2000-06-29")},.monetary={.int_curr_symbol=tsc(L"SEK "),.currency_symbol=tsc(L"kr"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"sön"),tsc(L"mån"),tsc(L"tis"),tsc(L"ons"),tsc(L"tor"),tsc(L"fre"),tsc(L"lör")},.day={tsc(L"söndag"),tsc(L"måndag"),tsc(L"tisdag"),tsc(L"onsdag"),tsc(L"torsdag"),tsc(L"fredag"),tsc(L"lördag")},.abmon={tsc(L"jan"),tsc(L"feb"),tsc(L"mar"),tsc(L"apr"),tsc(L"maj"),tsc(L"jun"),tsc(L"jul"),tsc(L"aug"),tsc(L"sep"),tsc(L"okt"),tsc(L"nov"),tsc(L"dec")},.mon={tsc(L"januari"),tsc(L"februari"),tsc(L"mars"),tsc(L"april"),tsc(L"maj"),tsc(L"juni"),tsc(L"juli"),tsc(L"augusti"),tsc(L"september"),tsc(L"oktober"),tsc(L"november"),tsc(L"december")},.d_t_fmt=tsc(L"%a %e %b %Y %H:%M:%S"),.d_fmt=tsc(L"%Y-%m-%d"),.t_fmt=tsc(L"%H:%M:%S"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1jJyY]"),.noexpr=tsc(L"^[-0nN]"),.yesstr=tsc(L"ja"),.nostr=tsc(L"nej")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c-%a-%l"),.tel_dom_fmt=tsc(L"0%a-%l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"46")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Sverige"),.country_ab2=tsc(L"SE"),.country_ab3=tsc(L"SWE"),.country_num=752,.country_car=tsc(L"S"),.lang_name=tsc(L"svenska"),.lang_ab=tsc(L"sv"),.lang_term=tsc(L"swe"),.lang_lib=tsc(L"swe")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Swedish locale for Sweden"),.source=tsc(u8"RAP\t\t;\t\tfast_io"),.address=tsc(u8"Sankt Jørgens Alle 8, DK-1615 København V, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Swedish"),.territory=tsc(u8"Sweden"),.revision=tsc(u8"1.0"),.date=tsc(u8"2000-06-29")},.monetary={.int_curr_symbol=tsc(u8"SEK "),.currency_symbol=tsc(u8"kr"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"sön"),tsc(u8"mån"),tsc(u8"tis"),tsc(u8"ons"),tsc(u8"tor"),tsc(u8"fre"),tsc(u8"lör")},.day={tsc(u8"söndag"),tsc(u8"måndag"),tsc(u8"tisdag"),tsc(u8"onsdag"),tsc(u8"torsdag"),tsc(u8"fredag"),tsc(u8"lördag")},.abmon={tsc(u8"jan"),tsc(u8"feb"),tsc(u8"mar"),tsc(u8"apr"),tsc(u8"maj"),tsc(u8"jun"),tsc(u8"jul"),tsc(u8"aug"),tsc(u8"sep"),tsc(u8"okt"),tsc(u8"nov"),tsc(u8"dec")},.mon={tsc(u8"januari"),tsc(u8"februari"),tsc(u8"mars"),tsc(u8"april"),tsc(u8"maj"),tsc(u8"juni"),tsc(u8"juli"),tsc(u8"augusti"),tsc(u8"september"),tsc(u8"oktober"),tsc(u8"november"),tsc(u8"december")},.d_t_fmt=tsc(u8"%a %e %b %Y %H:%M:%S"),.d_fmt=tsc(u8"%Y-%m-%d"),.t_fmt=tsc(u8"%H:%M:%S"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1jJyY]"),.noexpr=tsc(u8"^[-0nN]"),.yesstr=tsc(u8"ja"),.nostr=tsc(u8"nej")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c-%a-%l"),.tel_dom_fmt=tsc(u8"0%a-%l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"46")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Sverige"),.country_ab2=tsc(u8"SE"),.country_ab3=tsc(u8"SWE"),.country_num=752,.country_car=tsc(u8"S"),.lang_name=tsc(u8"svenska"),.lang_ab=tsc(u8"sv"),.lang_term=tsc(u8"swe"),.lang_lib=tsc(u8"swe")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Swedish locale for Sweden"),.source=tsc(u"RAP\t\t;\t\tfast_io"),.address=tsc(u"Sankt Jørgens Alle 8, DK-1615 København V, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Swedish"),.territory=tsc(u"Sweden"),.revision=tsc(u"1.0"),.date=tsc(u"2000-06-29")},.monetary={.int_curr_symbol=tsc(u"SEK "),.currency_symbol=tsc(u"kr"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"sön"),tsc(u"mån"),tsc(u"tis"),tsc(u"ons"),tsc(u"tor"),tsc(u"fre"),tsc(u"lör")},.day={tsc(u"söndag"),tsc(u"måndag"),tsc(u"tisdag"),tsc(u"onsdag"),tsc(u"torsdag"),tsc(u"fredag"),tsc(u"lördag")},.abmon={tsc(u"jan"),tsc(u"feb"),tsc(u"mar"),tsc(u"apr"),tsc(u"maj"),tsc(u"jun"),tsc(u"jul"),tsc(u"aug"),tsc(u"sep"),tsc(u"okt"),tsc(u"nov"),tsc(u"dec")},.mon={tsc(u"januari"),tsc(u"februari"),tsc(u"mars"),tsc(u"april"),tsc(u"maj"),tsc(u"juni"),tsc(u"juli"),tsc(u"augusti"),tsc(u"september"),tsc(u"oktober"),tsc(u"november"),tsc(u"december")},.d_t_fmt=tsc(u"%a %e %b %Y %H:%M:%S"),.d_fmt=tsc(u"%Y-%m-%d"),.t_fmt=tsc(u"%H:%M:%S"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1jJyY]"),.noexpr=tsc(u"^[-0nN]"),.yesstr=tsc(u"ja"),.nostr=tsc(u"nej")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c-%a-%l"),.tel_dom_fmt=tsc(u"0%a-%l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"46")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Sverige"),.country_ab2=tsc(u"SE"),.country_ab3=tsc(u"SWE"),.country_num=752,.country_car=tsc(u"S"),.lang_name=tsc(u"svenska"),.lang_ab=tsc(u"sv"),.lang_term=tsc(u"swe"),.lang_lib=tsc(u"swe")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Swedish locale for Sweden"),.source=tsc(U"RAP\t\t;\t\tfast_io"),.address=tsc(U"Sankt Jørgens Alle 8, DK-1615 København V, Danmark\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"bug-glibc-locales@gnu.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Swedish"),.territory=tsc(U"Sweden"),.revision=tsc(U"1.0"),.date=tsc(U"2000-06-29")},.monetary={.int_curr_symbol=tsc(U"SEK "),.currency_symbol=tsc(U"kr"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"sön"),tsc(U"mån"),tsc(U"tis"),tsc(U"ons"),tsc(U"tor"),tsc(U"fre"),tsc(U"lör")},.day={tsc(U"söndag"),tsc(U"måndag"),tsc(U"tisdag"),tsc(U"onsdag"),tsc(U"torsdag"),tsc(U"fredag"),tsc(U"lördag")},.abmon={tsc(U"jan"),tsc(U"feb"),tsc(U"mar"),tsc(U"apr"),tsc(U"maj"),tsc(U"jun"),tsc(U"jul"),tsc(U"aug"),tsc(U"sep"),tsc(U"okt"),tsc(U"nov"),tsc(U"dec")},.mon={tsc(U"januari"),tsc(U"februari"),tsc(U"mars"),tsc(U"april"),tsc(U"maj"),tsc(U"juni"),tsc(U"juli"),tsc(U"augusti"),tsc(U"september"),tsc(U"oktober"),tsc(U"november"),tsc(U"december")},.d_t_fmt=tsc(U"%a %e %b %Y %H:%M:%S"),.d_fmt=tsc(U"%Y-%m-%d"),.t_fmt=tsc(U"%H:%M:%S"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %e %b %Y %H:%M:%S %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1jJyY]"),.noexpr=tsc(U"^[-0nN]"),.yesstr=tsc(U"ja"),.nostr=tsc(U"nej")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c-%a-%l"),.tel_dom_fmt=tsc(U"0%a-%l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"46")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Sverige"),.country_ab2=tsc(U"SE"),.country_ab3=tsc(U"SWE"),.country_num=752,.country_car=tsc(U"S"),.lang_name=tsc(U"svenska"),.lang_ab=tsc(U"sv"),.lang_term=tsc(U"swe"),.lang_lib=tsc(U"swe")},.measurement={.measurement=1}};


}
}

#include"../main.h"