#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Silesian locale for Poland"),.source=tsc("szl_PL locale\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Przemyslaw Buczkowski\t\t;\t\tfast_io"),.email=tsc("libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Silesian"),.territory=tsc("Poland"),.revision=tsc("1.0"),.date=tsc("2012-07-17")},.monetary={.int_curr_symbol=tsc("PLN "),.currency_symbol=tsc("zł"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("niy"),tsc("pyń"),tsc("wto"),tsc("str"),tsc("szt"),tsc("piō"),tsc("sob")},.day={tsc("niydziela"),tsc("pyńdziałek"),tsc("wtorek"),tsc("strzoda"),tsc("sztwortek"),tsc("piōntek"),tsc("sobota")},.abmon={tsc("sty"),tsc("lut"),tsc("mar"),tsc("kwi"),tsc("moj"),tsc("czy"),tsc("lip"),tsc("sie"),tsc("wrz"),tsc("paź"),tsc("lis"),tsc("gru")},.mon={tsc("stycznia"),tsc("lutego"),tsc("marca"),tsc("kwietnia"),tsc("moja"),tsc("czyrwca"),tsc("lipca"),tsc("sierpnia"),tsc("września"),tsc("października"),tsc("listopada"),tsc("grudnia")},.d_t_fmt=tsc("%a, %-d %b %Y, %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a, %-d %b %Y, %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc("^[+1JjTtYy]"),.noexpr=tsc("^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("00"),.int_prefix=tsc("48")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Polska"),.country_ab2=tsc("PL"),.country_ab3=tsc("POL"),.country_num=616,.country_car=tsc("PL"),.lang_name=tsc("ślōnskŏ gŏdka"),.lang_term=tsc("szl"),.lang_lib=tsc("szl")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Silesian locale for Poland"),.source=tsc(L"szl_PL locale\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Przemyslaw Buczkowski\t\t;\t\tfast_io"),.email=tsc(L"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Silesian"),.territory=tsc(L"Poland"),.revision=tsc(L"1.0"),.date=tsc(L"2012-07-17")},.monetary={.int_curr_symbol=tsc(L"PLN "),.currency_symbol=tsc(L"zł"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"niy"),tsc(L"pyń"),tsc(L"wto"),tsc(L"str"),tsc(L"szt"),tsc(L"piō"),tsc(L"sob")},.day={tsc(L"niydziela"),tsc(L"pyńdziałek"),tsc(L"wtorek"),tsc(L"strzoda"),tsc(L"sztwortek"),tsc(L"piōntek"),tsc(L"sobota")},.abmon={tsc(L"sty"),tsc(L"lut"),tsc(L"mar"),tsc(L"kwi"),tsc(L"moj"),tsc(L"czy"),tsc(L"lip"),tsc(L"sie"),tsc(L"wrz"),tsc(L"paź"),tsc(L"lis"),tsc(L"gru")},.mon={tsc(L"stycznia"),tsc(L"lutego"),tsc(L"marca"),tsc(L"kwietnia"),tsc(L"moja"),tsc(L"czyrwca"),tsc(L"lipca"),tsc(L"sierpnia"),tsc(L"września"),tsc(L"października"),tsc(L"listopada"),tsc(L"grudnia")},.d_t_fmt=tsc(L"%a, %-d %b %Y, %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a, %-d %b %Y, %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1JjTtYy]"),.noexpr=tsc(L"^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"48")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Polska"),.country_ab2=tsc(L"PL"),.country_ab3=tsc(L"POL"),.country_num=616,.country_car=tsc(L"PL"),.lang_name=tsc(L"ślōnskŏ gŏdka"),.lang_term=tsc(L"szl"),.lang_lib=tsc(L"szl")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Silesian locale for Poland"),.source=tsc(u8"szl_PL locale\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Przemyslaw Buczkowski\t\t;\t\tfast_io"),.email=tsc(u8"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Silesian"),.territory=tsc(u8"Poland"),.revision=tsc(u8"1.0"),.date=tsc(u8"2012-07-17")},.monetary={.int_curr_symbol=tsc(u8"PLN "),.currency_symbol=tsc(u8"zł"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"niy"),tsc(u8"pyń"),tsc(u8"wto"),tsc(u8"str"),tsc(u8"szt"),tsc(u8"piō"),tsc(u8"sob")},.day={tsc(u8"niydziela"),tsc(u8"pyńdziałek"),tsc(u8"wtorek"),tsc(u8"strzoda"),tsc(u8"sztwortek"),tsc(u8"piōntek"),tsc(u8"sobota")},.abmon={tsc(u8"sty"),tsc(u8"lut"),tsc(u8"mar"),tsc(u8"kwi"),tsc(u8"moj"),tsc(u8"czy"),tsc(u8"lip"),tsc(u8"sie"),tsc(u8"wrz"),tsc(u8"paź"),tsc(u8"lis"),tsc(u8"gru")},.mon={tsc(u8"stycznia"),tsc(u8"lutego"),tsc(u8"marca"),tsc(u8"kwietnia"),tsc(u8"moja"),tsc(u8"czyrwca"),tsc(u8"lipca"),tsc(u8"sierpnia"),tsc(u8"września"),tsc(u8"października"),tsc(u8"listopada"),tsc(u8"grudnia")},.d_t_fmt=tsc(u8"%a, %-d %b %Y, %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a, %-d %b %Y, %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1JjTtYy]"),.noexpr=tsc(u8"^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"48")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Polska"),.country_ab2=tsc(u8"PL"),.country_ab3=tsc(u8"POL"),.country_num=616,.country_car=tsc(u8"PL"),.lang_name=tsc(u8"ślōnskŏ gŏdka"),.lang_term=tsc(u8"szl"),.lang_lib=tsc(u8"szl")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Silesian locale for Poland"),.source=tsc(u"szl_PL locale\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Przemyslaw Buczkowski\t\t;\t\tfast_io"),.email=tsc(u"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Silesian"),.territory=tsc(u"Poland"),.revision=tsc(u"1.0"),.date=tsc(u"2012-07-17")},.monetary={.int_curr_symbol=tsc(u"PLN "),.currency_symbol=tsc(u"zł"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"niy"),tsc(u"pyń"),tsc(u"wto"),tsc(u"str"),tsc(u"szt"),tsc(u"piō"),tsc(u"sob")},.day={tsc(u"niydziela"),tsc(u"pyńdziałek"),tsc(u"wtorek"),tsc(u"strzoda"),tsc(u"sztwortek"),tsc(u"piōntek"),tsc(u"sobota")},.abmon={tsc(u"sty"),tsc(u"lut"),tsc(u"mar"),tsc(u"kwi"),tsc(u"moj"),tsc(u"czy"),tsc(u"lip"),tsc(u"sie"),tsc(u"wrz"),tsc(u"paź"),tsc(u"lis"),tsc(u"gru")},.mon={tsc(u"stycznia"),tsc(u"lutego"),tsc(u"marca"),tsc(u"kwietnia"),tsc(u"moja"),tsc(u"czyrwca"),tsc(u"lipca"),tsc(u"sierpnia"),tsc(u"września"),tsc(u"października"),tsc(u"listopada"),tsc(u"grudnia")},.d_t_fmt=tsc(u"%a, %-d %b %Y, %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a, %-d %b %Y, %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1JjTtYy]"),.noexpr=tsc(u"^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"48")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Polska"),.country_ab2=tsc(u"PL"),.country_ab3=tsc(u"POL"),.country_num=616,.country_car=tsc(u"PL"),.lang_name=tsc(u"ślōnskŏ gŏdka"),.lang_term=tsc(u"szl"),.lang_lib=tsc(u"szl")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Silesian locale for Poland"),.source=tsc(U"szl_PL locale\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Przemyslaw Buczkowski\t\t;\t\tfast_io"),.email=tsc(U"libc-alpha@sourceware.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Silesian"),.territory=tsc(U"Poland"),.revision=tsc(U"1.0"),.date=tsc(U"2012-07-17")},.monetary={.int_curr_symbol=tsc(U"PLN "),.currency_symbol=tsc(U"zł"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"niy"),tsc(U"pyń"),tsc(U"wto"),tsc(U"str"),tsc(U"szt"),tsc(U"piō"),tsc(U"sob")},.day={tsc(U"niydziela"),tsc(U"pyńdziałek"),tsc(U"wtorek"),tsc(U"strzoda"),tsc(U"sztwortek"),tsc(U"piōntek"),tsc(U"sobota")},.abmon={tsc(U"sty"),tsc(U"lut"),tsc(U"mar"),tsc(U"kwi"),tsc(U"moj"),tsc(U"czy"),tsc(U"lip"),tsc(U"sie"),tsc(U"wrz"),tsc(U"paź"),tsc(U"lis"),tsc(U"gru")},.mon={tsc(U"stycznia"),tsc(U"lutego"),tsc(U"marca"),tsc(U"kwietnia"),tsc(U"moja"),tsc(U"czyrwca"),tsc(U"lipca"),tsc(U"sierpnia"),tsc(U"września"),tsc(U"października"),tsc(U"listopada"),tsc(U"grudnia")},.d_t_fmt=tsc(U"%a, %-d %b %Y, %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a, %-d %b %Y, %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,4},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1JjTtYy]"),.noexpr=tsc(U"^[-0nN]")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"48")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Polska"),.country_ab2=tsc(U"PL"),.country_ab3=tsc(U"POL"),.country_num=616,.country_car=tsc(U"PL"),.lang_name=tsc(U"ślōnskŏ gŏdka"),.lang_term=tsc(U"szl"),.lang_lib=tsc(U"szl")},.measurement={.measurement=1}};


}
}

#include"../main.h"