#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Tatar language locale for Russia"),.source=tsc("Rinat Norkin\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Pablo Saratxaga, Rinat Norkin\t\t;\t\tfast_io"),.email=tsc("pablo@mandrakesoft.com, rinat@taif.ru;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Tatar"),.territory=tsc("Russia"),.revision=tsc("0.4"),.date=tsc("2001-01-28")},.monetary={.int_curr_symbol=tsc("RUB "),.currency_symbol=tsc("₽"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc(" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("якш"),tsc("дүш"),tsc("сиш"),tsc("чәр"),tsc("пәнҗ"),tsc("җом"),tsc("шим")},.day={tsc("якшәмбе"),tsc("дүшәмбе"),tsc("сишәмбе"),tsc("чәршәмбе"),tsc("пәнҗешәмбе"),tsc("җомга"),tsc("шимбә")},.abmon={tsc("гыйн"),tsc("фев"),tsc("мар"),tsc("апр"),tsc("май"),tsc("июнь"),tsc("июль"),tsc("авг"),tsc("сент"),tsc("окт"),tsc("нояб"),tsc("дек")},.mon={tsc("гыйнвар"),tsc("февраль"),tsc("март"),tsc("апрель"),tsc("май"),tsc("июнь"),tsc("июль"),tsc("август"),tsc("сентябрь"),tsc("октябрь"),tsc("ноябрь"),tsc("декабрь")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1yYәӘ]"),.noexpr=tsc("^[-0nNюЮ]"),.yesstr=tsc("әйе"),.nostr=tsc("юк")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.int_select=tsc("0~10"),.int_prefix=tsc("7")},.name={.name_fmt=tsc("???")},.address={.postal_fmt=tsc("???"),.country_name=tsc("Русия"),.country_ab2=tsc("RU"),.country_ab3=tsc("RUS"),.country_num=643,.country_car=tsc("RUS"),.lang_name=tsc("татар"),.lang_ab=tsc("tt"),.lang_term=tsc("tat"),.lang_lib=tsc("tat")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Tatar language locale for Russia"),.source=tsc(L"Rinat Norkin\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Pablo Saratxaga, Rinat Norkin\t\t;\t\tfast_io"),.email=tsc(L"pablo@mandrakesoft.com, rinat@taif.ru;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Tatar"),.territory=tsc(L"Russia"),.revision=tsc(L"0.4"),.date=tsc(L"2001-01-28")},.monetary={.int_curr_symbol=tsc(L"RUB "),.currency_symbol=tsc(L"₽"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"якш"),tsc(L"дүш"),tsc(L"сиш"),tsc(L"чәр"),tsc(L"пәнҗ"),tsc(L"җом"),tsc(L"шим")},.day={tsc(L"якшәмбе"),tsc(L"дүшәмбе"),tsc(L"сишәмбе"),tsc(L"чәршәмбе"),tsc(L"пәнҗешәмбе"),tsc(L"җомга"),tsc(L"шимбә")},.abmon={tsc(L"гыйн"),tsc(L"фев"),tsc(L"мар"),tsc(L"апр"),tsc(L"май"),tsc(L"июнь"),tsc(L"июль"),tsc(L"авг"),tsc(L"сент"),tsc(L"окт"),tsc(L"нояб"),tsc(L"дек")},.mon={tsc(L"гыйнвар"),tsc(L"февраль"),tsc(L"март"),tsc(L"апрель"),tsc(L"май"),tsc(L"июнь"),tsc(L"июль"),tsc(L"август"),tsc(L"сентябрь"),tsc(L"октябрь"),tsc(L"ноябрь"),tsc(L"декабрь")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1yYәӘ]"),.noexpr=tsc(L"^[-0nNюЮ]"),.yesstr=tsc(L"әйе"),.nostr=tsc(L"юк")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.int_select=tsc(L"0~10"),.int_prefix=tsc(L"7")},.name={.name_fmt=tsc(L"???")},.address={.postal_fmt=tsc(L"???"),.country_name=tsc(L"Русия"),.country_ab2=tsc(L"RU"),.country_ab3=tsc(L"RUS"),.country_num=643,.country_car=tsc(L"RUS"),.lang_name=tsc(L"татар"),.lang_ab=tsc(L"tt"),.lang_term=tsc(L"tat"),.lang_lib=tsc(L"tat")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Tatar language locale for Russia"),.source=tsc(u8"Rinat Norkin\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Pablo Saratxaga, Rinat Norkin\t\t;\t\tfast_io"),.email=tsc(u8"pablo@mandrakesoft.com, rinat@taif.ru;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Tatar"),.territory=tsc(u8"Russia"),.revision=tsc(u8"0.4"),.date=tsc(u8"2001-01-28")},.monetary={.int_curr_symbol=tsc(u8"RUB "),.currency_symbol=tsc(u8"₽"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"якш"),tsc(u8"дүш"),tsc(u8"сиш"),tsc(u8"чәр"),tsc(u8"пәнҗ"),tsc(u8"җом"),tsc(u8"шим")},.day={tsc(u8"якшәмбе"),tsc(u8"дүшәмбе"),tsc(u8"сишәмбе"),tsc(u8"чәршәмбе"),tsc(u8"пәнҗешәмбе"),tsc(u8"җомга"),tsc(u8"шимбә")},.abmon={tsc(u8"гыйн"),tsc(u8"фев"),tsc(u8"мар"),tsc(u8"апр"),tsc(u8"май"),tsc(u8"июнь"),tsc(u8"июль"),tsc(u8"авг"),tsc(u8"сент"),tsc(u8"окт"),tsc(u8"нояб"),tsc(u8"дек")},.mon={tsc(u8"гыйнвар"),tsc(u8"февраль"),tsc(u8"март"),tsc(u8"апрель"),tsc(u8"май"),tsc(u8"июнь"),tsc(u8"июль"),tsc(u8"август"),tsc(u8"сентябрь"),tsc(u8"октябрь"),tsc(u8"ноябрь"),tsc(u8"декабрь")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1yYәӘ]"),.noexpr=tsc(u8"^[-0nNюЮ]"),.yesstr=tsc(u8"әйе"),.nostr=tsc(u8"юк")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.int_select=tsc(u8"0~10"),.int_prefix=tsc(u8"7")},.name={.name_fmt=tsc(u8"???")},.address={.postal_fmt=tsc(u8"???"),.country_name=tsc(u8"Русия"),.country_ab2=tsc(u8"RU"),.country_ab3=tsc(u8"RUS"),.country_num=643,.country_car=tsc(u8"RUS"),.lang_name=tsc(u8"татар"),.lang_ab=tsc(u8"tt"),.lang_term=tsc(u8"tat"),.lang_lib=tsc(u8"tat")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Tatar language locale for Russia"),.source=tsc(u"Rinat Norkin\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Pablo Saratxaga, Rinat Norkin\t\t;\t\tfast_io"),.email=tsc(u"pablo@mandrakesoft.com, rinat@taif.ru;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Tatar"),.territory=tsc(u"Russia"),.revision=tsc(u"0.4"),.date=tsc(u"2001-01-28")},.monetary={.int_curr_symbol=tsc(u"RUB "),.currency_symbol=tsc(u"₽"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"якш"),tsc(u"дүш"),tsc(u"сиш"),tsc(u"чәр"),tsc(u"пәнҗ"),tsc(u"җом"),tsc(u"шим")},.day={tsc(u"якшәмбе"),tsc(u"дүшәмбе"),tsc(u"сишәмбе"),tsc(u"чәршәмбе"),tsc(u"пәнҗешәмбе"),tsc(u"җомга"),tsc(u"шимбә")},.abmon={tsc(u"гыйн"),tsc(u"фев"),tsc(u"мар"),tsc(u"апр"),tsc(u"май"),tsc(u"июнь"),tsc(u"июль"),tsc(u"авг"),tsc(u"сент"),tsc(u"окт"),tsc(u"нояб"),tsc(u"дек")},.mon={tsc(u"гыйнвар"),tsc(u"февраль"),tsc(u"март"),tsc(u"апрель"),tsc(u"май"),tsc(u"июнь"),tsc(u"июль"),tsc(u"август"),tsc(u"сентябрь"),tsc(u"октябрь"),tsc(u"ноябрь"),tsc(u"декабрь")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1yYәӘ]"),.noexpr=tsc(u"^[-0nNюЮ]"),.yesstr=tsc(u"әйе"),.nostr=tsc(u"юк")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.int_select=tsc(u"0~10"),.int_prefix=tsc(u"7")},.name={.name_fmt=tsc(u"???")},.address={.postal_fmt=tsc(u"???"),.country_name=tsc(u"Русия"),.country_ab2=tsc(u"RU"),.country_ab3=tsc(u"RUS"),.country_num=643,.country_car=tsc(u"RUS"),.lang_name=tsc(u"татар"),.lang_ab=tsc(u"tt"),.lang_term=tsc(u"tat"),.lang_lib=tsc(u"tat")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Tatar language locale for Russia"),.source=tsc(U"Rinat Norkin\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Pablo Saratxaga, Rinat Norkin\t\t;\t\tfast_io"),.email=tsc(U"pablo@mandrakesoft.com, rinat@taif.ru;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Tatar"),.territory=tsc(U"Russia"),.revision=tsc(U"0.4"),.date=tsc(U"2001-01-28")},.monetary={.int_curr_symbol=tsc(U"RUB "),.currency_symbol=tsc(U"₽"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U" "),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U" "),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"якш"),tsc(U"дүш"),tsc(U"сиш"),tsc(U"чәр"),tsc(U"пәнҗ"),tsc(U"җом"),tsc(U"шим")},.day={tsc(U"якшәмбе"),tsc(U"дүшәмбе"),tsc(U"сишәмбе"),tsc(U"чәршәмбе"),tsc(U"пәнҗешәмбе"),tsc(U"җомга"),tsc(U"шимбә")},.abmon={tsc(U"гыйн"),tsc(U"фев"),tsc(U"мар"),tsc(U"апр"),tsc(U"май"),tsc(U"июнь"),tsc(U"июль"),tsc(U"авг"),tsc(U"сент"),tsc(U"окт"),tsc(U"нояб"),tsc(U"дек")},.mon={tsc(U"гыйнвар"),tsc(U"февраль"),tsc(U"март"),tsc(U"апрель"),tsc(U"май"),tsc(U"июнь"),tsc(U"июль"),tsc(U"август"),tsc(U"сентябрь"),tsc(U"октябрь"),tsc(U"ноябрь"),tsc(U"декабрь")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1yYәӘ]"),.noexpr=tsc(U"^[-0nNюЮ]"),.yesstr=tsc(U"әйе"),.nostr=tsc(U"юк")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.int_select=tsc(U"0~10"),.int_prefix=tsc(U"7")},.name={.name_fmt=tsc(U"???")},.address={.postal_fmt=tsc(U"???"),.country_name=tsc(U"Русия"),.country_ab2=tsc(U"RU"),.country_ab3=tsc(U"RUS"),.country_num=643,.country_car=tsc(U"RUS"),.lang_name=tsc(U"татар"),.lang_ab=tsc(U"tt"),.lang_term=tsc(U"tat"),.lang_lib=tsc(U"tat")},.measurement={.measurement=1}};


}
}

#include"../main.h"