#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t numeric_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Walaita language locale for Ethiopia."),.source=tsc("Ge'ez Frontier Foundation\t\t;\t\tfast_io"),.address=tsc("7802 Solomon Seal Dr., Springfield, VA 22152, USA\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("fast_io"),.email=tsc("locales@geez.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Wolaytta"),.territory=tsc("Ethiopia"),.revision=tsc("0.10"),.date=tsc("2004-04-25")},.monetary={.int_curr_symbol=tsc("ETB "),.currency_symbol=tsc("Br"),.mon_decimal_point=tsc("."),.mon_thousands_sep=tsc(","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc("."),.thousands_sep=tsc(","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc("ወጋ "),tsc("ሳይኖ"),tsc("ማቆሳ"),tsc("አሩዋ"),tsc("ሃሙሳ"),tsc("አርባ"),tsc("ቄራ ")},.day={tsc("ወጋ"),tsc("ሳይኖ"),tsc("ማቆሳኛ"),tsc("አሩዋ"),tsc("ሃሙሳ"),tsc("አርባ"),tsc("ቄራ")},.abmon={tsc("ጃንዩ"),tsc("ፌብሩ"),tsc("ማርች"),tsc("ኤፕረ"),tsc("ሜይ "),tsc("ጁን "),tsc("ጁላይ"),tsc("ኦገስ"),tsc("ሴፕቴ"),tsc("ኦክተ"),tsc("ኖቬም"),tsc("ዲሴም")},.mon={tsc("ጃንዩወሪ"),tsc("ፌብሩወሪ"),tsc("ማርች"),tsc("ኤፕረል"),tsc("ሜይ"),tsc("ጁን"),tsc("ጁላይ"),tsc("ኦገስት"),tsc("ሴፕቴምበር"),tsc("ኦክተውበር"),tsc("ኖቬምበር"),tsc("ዲሴምበር")},.d_t_fmt=tsc("%A፣ %B %e ጋላሳ %Y %r %Z"),.d_fmt=tsc("%d//%m//%Y"),.t_fmt=tsc("%l:%M:%S %p"),.t_fmt_ampm=tsc("%l:%M:%S %p"),.date_fmt=tsc("%A፣ %B %e ጋላሳ %r %Z %Y ግ//ላ"),.am_pm={tsc("ማለዶ"),tsc("ቃማ")},.week={7,19971130,1}},.messages={.yesexpr=tsc("^[+1እyY]"),.noexpr=tsc("^[-0ነnN]"),.yesstr=tsc("እወ"),.nostr=tsc("ነኖእ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("%c-%a-%l"),.tel_dom_fmt=tsc("%a-%l"),.int_select=tsc("00"),.int_prefix=tsc("251")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f"),.name_gen=tsc(""),.name_miss=tsc("ኬታዩ"),.name_mr=tsc("ሚሲያ"),.name_mrs=tsc("ኬታዋ"),.name_ms=tsc("ኬታዩ")},.address={.postal_fmt=tsc("%z%c%T%s%b%e%r"),.country_name=tsc("ኢትዮጵያ"),.country_post=tsc("ETH"),.country_ab2=tsc("ET"),.country_ab3=tsc("ETH"),.country_num=231,.country_car=tsc("ETH"),.lang_name=tsc("ወላይታቱ"),.lang_term=tsc("wal"),.lang_lib=tsc("wal")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Walaita language locale for Ethiopia."),.source=tsc(L"Ge'ez Frontier Foundation\t\t;\t\tfast_io"),.address=tsc(L"7802 Solomon Seal Dr., Springfield, VA 22152, USA\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"fast_io"),.email=tsc(L"locales@geez.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Wolaytta"),.territory=tsc(L"Ethiopia"),.revision=tsc(L"0.10"),.date=tsc(L"2004-04-25")},.monetary={.int_curr_symbol=tsc(L"ETB "),.currency_symbol=tsc(L"Br"),.mon_decimal_point=tsc(L"."),.mon_thousands_sep=tsc(L","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L"."),.thousands_sep=tsc(L","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(L"ወጋ "),tsc(L"ሳይኖ"),tsc(L"ማቆሳ"),tsc(L"አሩዋ"),tsc(L"ሃሙሳ"),tsc(L"አርባ"),tsc(L"ቄራ ")},.day={tsc(L"ወጋ"),tsc(L"ሳይኖ"),tsc(L"ማቆሳኛ"),tsc(L"አሩዋ"),tsc(L"ሃሙሳ"),tsc(L"አርባ"),tsc(L"ቄራ")},.abmon={tsc(L"ጃንዩ"),tsc(L"ፌብሩ"),tsc(L"ማርች"),tsc(L"ኤፕረ"),tsc(L"ሜይ "),tsc(L"ጁን "),tsc(L"ጁላይ"),tsc(L"ኦገስ"),tsc(L"ሴፕቴ"),tsc(L"ኦክተ"),tsc(L"ኖቬም"),tsc(L"ዲሴም")},.mon={tsc(L"ጃንዩወሪ"),tsc(L"ፌብሩወሪ"),tsc(L"ማርች"),tsc(L"ኤፕረል"),tsc(L"ሜይ"),tsc(L"ጁን"),tsc(L"ጁላይ"),tsc(L"ኦገስት"),tsc(L"ሴፕቴምበር"),tsc(L"ኦክተውበር"),tsc(L"ኖቬምበር"),tsc(L"ዲሴምበር")},.d_t_fmt=tsc(L"%A፣ %B %e ጋላሳ %Y %r %Z"),.d_fmt=tsc(L"%d//%m//%Y"),.t_fmt=tsc(L"%l:%M:%S %p"),.t_fmt_ampm=tsc(L"%l:%M:%S %p"),.date_fmt=tsc(L"%A፣ %B %e ጋላሳ %r %Z %Y ግ//ላ"),.am_pm={tsc(L"ማለዶ"),tsc(L"ቃማ")},.week={7,19971130,1}},.messages={.yesexpr=tsc(L"^[+1እyY]"),.noexpr=tsc(L"^[-0ነnN]"),.yesstr=tsc(L"እወ"),.nostr=tsc(L"ነኖእ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"%c-%a-%l"),.tel_dom_fmt=tsc(L"%a-%l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"251")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f"),.name_gen=tsc(L""),.name_miss=tsc(L"ኬታዩ"),.name_mr=tsc(L"ሚሲያ"),.name_mrs=tsc(L"ኬታዋ"),.name_ms=tsc(L"ኬታዩ")},.address={.postal_fmt=tsc(L"%z%c%T%s%b%e%r"),.country_name=tsc(L"ኢትዮጵያ"),.country_post=tsc(L"ETH"),.country_ab2=tsc(L"ET"),.country_ab3=tsc(L"ETH"),.country_num=231,.country_car=tsc(L"ETH"),.lang_name=tsc(L"ወላይታቱ"),.lang_term=tsc(L"wal"),.lang_lib=tsc(L"wal")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Walaita language locale for Ethiopia."),.source=tsc(u8"Ge'ez Frontier Foundation\t\t;\t\tfast_io"),.address=tsc(u8"7802 Solomon Seal Dr., Springfield, VA 22152, USA\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"fast_io"),.email=tsc(u8"locales@geez.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Wolaytta"),.territory=tsc(u8"Ethiopia"),.revision=tsc(u8"0.10"),.date=tsc(u8"2004-04-25")},.monetary={.int_curr_symbol=tsc(u8"ETB "),.currency_symbol=tsc(u8"Br"),.mon_decimal_point=tsc(u8"."),.mon_thousands_sep=tsc(u8","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8"."),.thousands_sep=tsc(u8","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u8"ወጋ "),tsc(u8"ሳይኖ"),tsc(u8"ማቆሳ"),tsc(u8"አሩዋ"),tsc(u8"ሃሙሳ"),tsc(u8"አርባ"),tsc(u8"ቄራ ")},.day={tsc(u8"ወጋ"),tsc(u8"ሳይኖ"),tsc(u8"ማቆሳኛ"),tsc(u8"አሩዋ"),tsc(u8"ሃሙሳ"),tsc(u8"አርባ"),tsc(u8"ቄራ")},.abmon={tsc(u8"ጃንዩ"),tsc(u8"ፌብሩ"),tsc(u8"ማርች"),tsc(u8"ኤፕረ"),tsc(u8"ሜይ "),tsc(u8"ጁን "),tsc(u8"ጁላይ"),tsc(u8"ኦገስ"),tsc(u8"ሴፕቴ"),tsc(u8"ኦክተ"),tsc(u8"ኖቬም"),tsc(u8"ዲሴም")},.mon={tsc(u8"ጃንዩወሪ"),tsc(u8"ፌብሩወሪ"),tsc(u8"ማርች"),tsc(u8"ኤፕረል"),tsc(u8"ሜይ"),tsc(u8"ጁን"),tsc(u8"ጁላይ"),tsc(u8"ኦገስት"),tsc(u8"ሴፕቴምበር"),tsc(u8"ኦክተውበር"),tsc(u8"ኖቬምበር"),tsc(u8"ዲሴምበር")},.d_t_fmt=tsc(u8"%A፣ %B %e ጋላሳ %Y %r %Z"),.d_fmt=tsc(u8"%d//%m//%Y"),.t_fmt=tsc(u8"%l:%M:%S %p"),.t_fmt_ampm=tsc(u8"%l:%M:%S %p"),.date_fmt=tsc(u8"%A፣ %B %e ጋላሳ %r %Z %Y ግ//ላ"),.am_pm={tsc(u8"ማለዶ"),tsc(u8"ቃማ")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u8"^[+1እyY]"),.noexpr=tsc(u8"^[-0ነnN]"),.yesstr=tsc(u8"እወ"),.nostr=tsc(u8"ነኖእ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"%c-%a-%l"),.tel_dom_fmt=tsc(u8"%a-%l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"251")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f"),.name_gen=tsc(u8""),.name_miss=tsc(u8"ኬታዩ"),.name_mr=tsc(u8"ሚሲያ"),.name_mrs=tsc(u8"ኬታዋ"),.name_ms=tsc(u8"ኬታዩ")},.address={.postal_fmt=tsc(u8"%z%c%T%s%b%e%r"),.country_name=tsc(u8"ኢትዮጵያ"),.country_post=tsc(u8"ETH"),.country_ab2=tsc(u8"ET"),.country_ab3=tsc(u8"ETH"),.country_num=231,.country_car=tsc(u8"ETH"),.lang_name=tsc(u8"ወላይታቱ"),.lang_term=tsc(u8"wal"),.lang_lib=tsc(u8"wal")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Walaita language locale for Ethiopia."),.source=tsc(u"Ge'ez Frontier Foundation\t\t;\t\tfast_io"),.address=tsc(u"7802 Solomon Seal Dr., Springfield, VA 22152, USA\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"fast_io"),.email=tsc(u"locales@geez.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Wolaytta"),.territory=tsc(u"Ethiopia"),.revision=tsc(u"0.10"),.date=tsc(u"2004-04-25")},.monetary={.int_curr_symbol=tsc(u"ETB "),.currency_symbol=tsc(u"Br"),.mon_decimal_point=tsc(u"."),.mon_thousands_sep=tsc(u","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u"."),.thousands_sep=tsc(u","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(u"ወጋ "),tsc(u"ሳይኖ"),tsc(u"ማቆሳ"),tsc(u"አሩዋ"),tsc(u"ሃሙሳ"),tsc(u"አርባ"),tsc(u"ቄራ ")},.day={tsc(u"ወጋ"),tsc(u"ሳይኖ"),tsc(u"ማቆሳኛ"),tsc(u"አሩዋ"),tsc(u"ሃሙሳ"),tsc(u"አርባ"),tsc(u"ቄራ")},.abmon={tsc(u"ጃንዩ"),tsc(u"ፌብሩ"),tsc(u"ማርች"),tsc(u"ኤፕረ"),tsc(u"ሜይ "),tsc(u"ጁን "),tsc(u"ጁላይ"),tsc(u"ኦገስ"),tsc(u"ሴፕቴ"),tsc(u"ኦክተ"),tsc(u"ኖቬም"),tsc(u"ዲሴም")},.mon={tsc(u"ጃንዩወሪ"),tsc(u"ፌብሩወሪ"),tsc(u"ማርች"),tsc(u"ኤፕረል"),tsc(u"ሜይ"),tsc(u"ጁን"),tsc(u"ጁላይ"),tsc(u"ኦገስት"),tsc(u"ሴፕቴምበር"),tsc(u"ኦክተውበር"),tsc(u"ኖቬምበር"),tsc(u"ዲሴምበር")},.d_t_fmt=tsc(u"%A፣ %B %e ጋላሳ %Y %r %Z"),.d_fmt=tsc(u"%d//%m//%Y"),.t_fmt=tsc(u"%l:%M:%S %p"),.t_fmt_ampm=tsc(u"%l:%M:%S %p"),.date_fmt=tsc(u"%A፣ %B %e ጋላሳ %r %Z %Y ግ//ላ"),.am_pm={tsc(u"ማለዶ"),tsc(u"ቃማ")},.week={7,19971130,1}},.messages={.yesexpr=tsc(u"^[+1እyY]"),.noexpr=tsc(u"^[-0ነnN]"),.yesstr=tsc(u"እወ"),.nostr=tsc(u"ነኖእ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"%c-%a-%l"),.tel_dom_fmt=tsc(u"%a-%l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"251")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f"),.name_gen=tsc(u""),.name_miss=tsc(u"ኬታዩ"),.name_mr=tsc(u"ሚሲያ"),.name_mrs=tsc(u"ኬታዋ"),.name_ms=tsc(u"ኬታዩ")},.address={.postal_fmt=tsc(u"%z%c%T%s%b%e%r"),.country_name=tsc(u"ኢትዮጵያ"),.country_post=tsc(u"ETH"),.country_ab2=tsc(u"ET"),.country_ab3=tsc(u"ETH"),.country_num=231,.country_car=tsc(u"ETH"),.lang_name=tsc(u"ወላይታቱ"),.lang_term=tsc(u"wal"),.lang_lib=tsc(u"wal")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Walaita language locale for Ethiopia."),.source=tsc(U"Ge'ez Frontier Foundation\t\t;\t\tfast_io"),.address=tsc(U"7802 Solomon Seal Dr., Springfield, VA 22152, USA\t\t;\t\thttps://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"fast_io"),.email=tsc(U"locales@geez.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Wolaytta"),.territory=tsc(U"Ethiopia"),.revision=tsc(U"0.10"),.date=tsc(U"2004-04-25")},.monetary={.int_curr_symbol=tsc(U"ETB "),.currency_symbol=tsc(U"Br"),.mon_decimal_point=tsc(U"."),.mon_thousands_sep=tsc(U","),.mon_grouping={numeric_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=1,.p_sep_by_space=0,.n_cs_precedes=1,.n_sep_by_space=0,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U"."),.thousands_sep=tsc(U","),.grouping={numeric_grouping_storage,1}},.time={.abday={tsc(U"ወጋ "),tsc(U"ሳይኖ"),tsc(U"ማቆሳ"),tsc(U"አሩዋ"),tsc(U"ሃሙሳ"),tsc(U"አርባ"),tsc(U"ቄራ ")},.day={tsc(U"ወጋ"),tsc(U"ሳይኖ"),tsc(U"ማቆሳኛ"),tsc(U"አሩዋ"),tsc(U"ሃሙሳ"),tsc(U"አርባ"),tsc(U"ቄራ")},.abmon={tsc(U"ጃንዩ"),tsc(U"ፌብሩ"),tsc(U"ማርች"),tsc(U"ኤፕረ"),tsc(U"ሜይ "),tsc(U"ጁን "),tsc(U"ጁላይ"),tsc(U"ኦገስ"),tsc(U"ሴፕቴ"),tsc(U"ኦክተ"),tsc(U"ኖቬም"),tsc(U"ዲሴም")},.mon={tsc(U"ጃንዩወሪ"),tsc(U"ፌብሩወሪ"),tsc(U"ማርች"),tsc(U"ኤፕረል"),tsc(U"ሜይ"),tsc(U"ጁን"),tsc(U"ጁላይ"),tsc(U"ኦገስት"),tsc(U"ሴፕቴምበር"),tsc(U"ኦክተውበር"),tsc(U"ኖቬምበር"),tsc(U"ዲሴምበር")},.d_t_fmt=tsc(U"%A፣ %B %e ጋላሳ %Y %r %Z"),.d_fmt=tsc(U"%d//%m//%Y"),.t_fmt=tsc(U"%l:%M:%S %p"),.t_fmt_ampm=tsc(U"%l:%M:%S %p"),.date_fmt=tsc(U"%A፣ %B %e ጋላሳ %r %Z %Y ግ//ላ"),.am_pm={tsc(U"ማለዶ"),tsc(U"ቃማ")},.week={7,19971130,1}},.messages={.yesexpr=tsc(U"^[+1እyY]"),.noexpr=tsc(U"^[-0ነnN]"),.yesstr=tsc(U"እወ"),.nostr=tsc(U"ነኖእ")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"%c-%a-%l"),.tel_dom_fmt=tsc(U"%a-%l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"251")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f"),.name_gen=tsc(U""),.name_miss=tsc(U"ኬታዩ"),.name_mr=tsc(U"ሚሲያ"),.name_mrs=tsc(U"ኬታዋ"),.name_ms=tsc(U"ኬታዩ")},.address={.postal_fmt=tsc(U"%z%c%T%s%b%e%r"),.country_name=tsc(U"ኢትዮጵያ"),.country_post=tsc(U"ETH"),.country_ab2=tsc(U"ET"),.country_ab3=tsc(U"ETH"),.country_num=231,.country_car=tsc(U"ETH"),.lang_name=tsc(U"ወላይታቱ"),.lang_term=tsc(U"wal"),.lang_lib=tsc(U"wal")},.measurement={.measurement=1}};


}
}

#include"../main.h"