#include"../localedef.h"

namespace fast_io_i18n
{
namespace
{

inline constexpr std::size_t monetary_mon_grouping_storage[]{3};

inline constexpr lc_all lc_all_global{.identification={.title=tsc("Wolof locale for Senegal"),.source=tsc("The Debian Project\t\t;\t\tfast_io"),.address=tsc("https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc("Christian Perrier\t\t;\t\tfast_io"),.email=tsc("bubulle@debian.org;euloanty@live.com"),.tel=tsc(""),.fax=tsc(""),.language=tsc("Wolof"),.territory=tsc("Senegal"),.revision=tsc("1.0"),.date=tsc("2004-09-08")},.monetary={.int_curr_symbol=tsc("XOF "),.currency_symbol=tsc("CFA"),.mon_decimal_point=tsc(","),.mon_thousands_sep=tsc(" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(""),.negative_sign=tsc("-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(","),.thousands_sep=tsc("")},.time={.abday={tsc("dib"),tsc("alt"),tsc("tal"),tsc("all"),tsc("alx"),tsc("ajj"),tsc("gaa")},.day={tsc("dib'eer"),tsc("altine"),tsc("talaata"),tsc("allarba"),tsc("alxames"),tsc("ajjuma"),tsc("gaawu")},.abmon={tsc("san"),tsc("fee"),tsc("mar"),tsc("awr"),tsc("me "),tsc("suw"),tsc("sul"),tsc("uut"),tsc("sep"),tsc("okt"),tsc("now"),tsc("des")},.mon={tsc("sanwiy'e"),tsc("feebriy'e"),tsc("mars"),tsc("awril"),tsc("me"),tsc("suwen"),tsc("sulet"),tsc("uut"),tsc("septaambar"),tsc("oktoobar"),tsc("nowaambar"),tsc("desaambar")},.d_t_fmt=tsc("%a %d %b %Y %T"),.d_fmt=tsc("%d.%m.%Y"),.t_fmt=tsc("%T"),.t_fmt_ampm=tsc(""),.date_fmt=tsc("%a %d %b %Y %T %Z"),.am_pm={tsc(""),tsc("")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc("^[+1wWyY]"),.noexpr=tsc("^[-0dDnN]"),.yesstr=tsc("waaw"),.nostr=tsc("déedet")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc("+%c %a %l"),.tel_dom_fmt=tsc("%a %l"),.int_select=tsc("00"),.int_prefix=tsc("221")},.name={.name_fmt=tsc("%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc("%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc("Senegaal"),.country_ab2=tsc("SN"),.country_ab3=tsc("SEN"),.country_num=686,.country_car=tsc("SN"),.lang_name=tsc("Wolof"),.lang_ab=tsc("wo"),.lang_term=tsc("wol"),.lang_lib=tsc("wol")},.measurement={.measurement=1}};

inline constexpr wlc_all wlc_all_global{.identification={.title=tsc(L"Wolof locale for Senegal"),.source=tsc(L"The Debian Project\t\t;\t\tfast_io"),.address=tsc(L"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(L"Christian Perrier\t\t;\t\tfast_io"),.email=tsc(L"bubulle@debian.org;euloanty@live.com"),.tel=tsc(L""),.fax=tsc(L""),.language=tsc(L"Wolof"),.territory=tsc(L"Senegal"),.revision=tsc(L"1.0"),.date=tsc(L"2004-09-08")},.monetary={.int_curr_symbol=tsc(L"XOF "),.currency_symbol=tsc(L"CFA"),.mon_decimal_point=tsc(L","),.mon_thousands_sep=tsc(L" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(L""),.negative_sign=tsc(L"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(L","),.thousands_sep=tsc(L"")},.time={.abday={tsc(L"dib"),tsc(L"alt"),tsc(L"tal"),tsc(L"all"),tsc(L"alx"),tsc(L"ajj"),tsc(L"gaa")},.day={tsc(L"dib'eer"),tsc(L"altine"),tsc(L"talaata"),tsc(L"allarba"),tsc(L"alxames"),tsc(L"ajjuma"),tsc(L"gaawu")},.abmon={tsc(L"san"),tsc(L"fee"),tsc(L"mar"),tsc(L"awr"),tsc(L"me "),tsc(L"suw"),tsc(L"sul"),tsc(L"uut"),tsc(L"sep"),tsc(L"okt"),tsc(L"now"),tsc(L"des")},.mon={tsc(L"sanwiy'e"),tsc(L"feebriy'e"),tsc(L"mars"),tsc(L"awril"),tsc(L"me"),tsc(L"suwen"),tsc(L"sulet"),tsc(L"uut"),tsc(L"septaambar"),tsc(L"oktoobar"),tsc(L"nowaambar"),tsc(L"desaambar")},.d_t_fmt=tsc(L"%a %d %b %Y %T"),.d_fmt=tsc(L"%d.%m.%Y"),.t_fmt=tsc(L"%T"),.t_fmt_ampm=tsc(L""),.date_fmt=tsc(L"%a %d %b %Y %T %Z"),.am_pm={tsc(L""),tsc(L"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(L"^[+1wWyY]"),.noexpr=tsc(L"^[-0dDnN]"),.yesstr=tsc(L"waaw"),.nostr=tsc(L"déedet")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(L"+%c %a %l"),.tel_dom_fmt=tsc(L"%a %l"),.int_select=tsc(L"00"),.int_prefix=tsc(L"221")},.name={.name_fmt=tsc(L"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(L"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(L"Senegaal"),.country_ab2=tsc(L"SN"),.country_ab3=tsc(L"SEN"),.country_num=686,.country_car=tsc(L"SN"),.lang_name=tsc(L"Wolof"),.lang_ab=tsc(L"wo"),.lang_term=tsc(L"wol"),.lang_lib=tsc(L"wol")},.measurement={.measurement=1}};

inline constexpr u8lc_all u8lc_all_global{.identification={.title=tsc(u8"Wolof locale for Senegal"),.source=tsc(u8"The Debian Project\t\t;\t\tfast_io"),.address=tsc(u8"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u8"Christian Perrier\t\t;\t\tfast_io"),.email=tsc(u8"bubulle@debian.org;euloanty@live.com"),.tel=tsc(u8""),.fax=tsc(u8""),.language=tsc(u8"Wolof"),.territory=tsc(u8"Senegal"),.revision=tsc(u8"1.0"),.date=tsc(u8"2004-09-08")},.monetary={.int_curr_symbol=tsc(u8"XOF "),.currency_symbol=tsc(u8"CFA"),.mon_decimal_point=tsc(u8","),.mon_thousands_sep=tsc(u8" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u8""),.negative_sign=tsc(u8"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u8","),.thousands_sep=tsc(u8"")},.time={.abday={tsc(u8"dib"),tsc(u8"alt"),tsc(u8"tal"),tsc(u8"all"),tsc(u8"alx"),tsc(u8"ajj"),tsc(u8"gaa")},.day={tsc(u8"dib'eer"),tsc(u8"altine"),tsc(u8"talaata"),tsc(u8"allarba"),tsc(u8"alxames"),tsc(u8"ajjuma"),tsc(u8"gaawu")},.abmon={tsc(u8"san"),tsc(u8"fee"),tsc(u8"mar"),tsc(u8"awr"),tsc(u8"me "),tsc(u8"suw"),tsc(u8"sul"),tsc(u8"uut"),tsc(u8"sep"),tsc(u8"okt"),tsc(u8"now"),tsc(u8"des")},.mon={tsc(u8"sanwiy'e"),tsc(u8"feebriy'e"),tsc(u8"mars"),tsc(u8"awril"),tsc(u8"me"),tsc(u8"suwen"),tsc(u8"sulet"),tsc(u8"uut"),tsc(u8"septaambar"),tsc(u8"oktoobar"),tsc(u8"nowaambar"),tsc(u8"desaambar")},.d_t_fmt=tsc(u8"%a %d %b %Y %T"),.d_fmt=tsc(u8"%d.%m.%Y"),.t_fmt=tsc(u8"%T"),.t_fmt_ampm=tsc(u8""),.date_fmt=tsc(u8"%a %d %b %Y %T %Z"),.am_pm={tsc(u8""),tsc(u8"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u8"^[+1wWyY]"),.noexpr=tsc(u8"^[-0dDnN]"),.yesstr=tsc(u8"waaw"),.nostr=tsc(u8"déedet")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u8"+%c %a %l"),.tel_dom_fmt=tsc(u8"%a %l"),.int_select=tsc(u8"00"),.int_prefix=tsc(u8"221")},.name={.name_fmt=tsc(u8"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u8"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u8"Senegaal"),.country_ab2=tsc(u8"SN"),.country_ab3=tsc(u8"SEN"),.country_num=686,.country_car=tsc(u8"SN"),.lang_name=tsc(u8"Wolof"),.lang_ab=tsc(u8"wo"),.lang_term=tsc(u8"wol"),.lang_lib=tsc(u8"wol")},.measurement={.measurement=1}};

inline constexpr u16lc_all u16lc_all_global{.identification={.title=tsc(u"Wolof locale for Senegal"),.source=tsc(u"The Debian Project\t\t;\t\tfast_io"),.address=tsc(u"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(u"Christian Perrier\t\t;\t\tfast_io"),.email=tsc(u"bubulle@debian.org;euloanty@live.com"),.tel=tsc(u""),.fax=tsc(u""),.language=tsc(u"Wolof"),.territory=tsc(u"Senegal"),.revision=tsc(u"1.0"),.date=tsc(u"2004-09-08")},.monetary={.int_curr_symbol=tsc(u"XOF "),.currency_symbol=tsc(u"CFA"),.mon_decimal_point=tsc(u","),.mon_thousands_sep=tsc(u" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(u""),.negative_sign=tsc(u"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(u","),.thousands_sep=tsc(u"")},.time={.abday={tsc(u"dib"),tsc(u"alt"),tsc(u"tal"),tsc(u"all"),tsc(u"alx"),tsc(u"ajj"),tsc(u"gaa")},.day={tsc(u"dib'eer"),tsc(u"altine"),tsc(u"talaata"),tsc(u"allarba"),tsc(u"alxames"),tsc(u"ajjuma"),tsc(u"gaawu")},.abmon={tsc(u"san"),tsc(u"fee"),tsc(u"mar"),tsc(u"awr"),tsc(u"me "),tsc(u"suw"),tsc(u"sul"),tsc(u"uut"),tsc(u"sep"),tsc(u"okt"),tsc(u"now"),tsc(u"des")},.mon={tsc(u"sanwiy'e"),tsc(u"feebriy'e"),tsc(u"mars"),tsc(u"awril"),tsc(u"me"),tsc(u"suwen"),tsc(u"sulet"),tsc(u"uut"),tsc(u"septaambar"),tsc(u"oktoobar"),tsc(u"nowaambar"),tsc(u"desaambar")},.d_t_fmt=tsc(u"%a %d %b %Y %T"),.d_fmt=tsc(u"%d.%m.%Y"),.t_fmt=tsc(u"%T"),.t_fmt_ampm=tsc(u""),.date_fmt=tsc(u"%a %d %b %Y %T %Z"),.am_pm={tsc(u""),tsc(u"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(u"^[+1wWyY]"),.noexpr=tsc(u"^[-0dDnN]"),.yesstr=tsc(u"waaw"),.nostr=tsc(u"déedet")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(u"+%c %a %l"),.tel_dom_fmt=tsc(u"%a %l"),.int_select=tsc(u"00"),.int_prefix=tsc(u"221")},.name={.name_fmt=tsc(u"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(u"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(u"Senegaal"),.country_ab2=tsc(u"SN"),.country_ab3=tsc(u"SEN"),.country_num=686,.country_car=tsc(u"SN"),.lang_name=tsc(u"Wolof"),.lang_ab=tsc(u"wo"),.lang_term=tsc(u"wol"),.lang_lib=tsc(u"wol")},.measurement={.measurement=1}};

inline constexpr u32lc_all u32lc_all_global{.identification={.title=tsc(U"Wolof locale for Senegal"),.source=tsc(U"The Debian Project\t\t;\t\tfast_io"),.address=tsc(U"https://gitee.com/qabeowjbtkwb/fast_io"),.contact=tsc(U"Christian Perrier\t\t;\t\tfast_io"),.email=tsc(U"bubulle@debian.org;euloanty@live.com"),.tel=tsc(U""),.fax=tsc(U""),.language=tsc(U"Wolof"),.territory=tsc(U"Senegal"),.revision=tsc(U"1.0"),.date=tsc(U"2004-09-08")},.monetary={.int_curr_symbol=tsc(U"XOF "),.currency_symbol=tsc(U"CFA"),.mon_decimal_point=tsc(U","),.mon_thousands_sep=tsc(U" "),.mon_grouping={monetary_mon_grouping_storage,1},.positive_sign=tsc(U""),.negative_sign=tsc(U"-"),.int_frac_digits=2,.frac_digits=2,.p_cs_precedes=0,.p_sep_by_space=1,.n_cs_precedes=0,.n_sep_by_space=1,.p_sign_posn=1,.n_sign_posn=1},.numeric={.decimal_point=tsc(U","),.thousands_sep=tsc(U"")},.time={.abday={tsc(U"dib"),tsc(U"alt"),tsc(U"tal"),tsc(U"all"),tsc(U"alx"),tsc(U"ajj"),tsc(U"gaa")},.day={tsc(U"dib'eer"),tsc(U"altine"),tsc(U"talaata"),tsc(U"allarba"),tsc(U"alxames"),tsc(U"ajjuma"),tsc(U"gaawu")},.abmon={tsc(U"san"),tsc(U"fee"),tsc(U"mar"),tsc(U"awr"),tsc(U"me "),tsc(U"suw"),tsc(U"sul"),tsc(U"uut"),tsc(U"sep"),tsc(U"okt"),tsc(U"now"),tsc(U"des")},.mon={tsc(U"sanwiy'e"),tsc(U"feebriy'e"),tsc(U"mars"),tsc(U"awril"),tsc(U"me"),tsc(U"suwen"),tsc(U"sulet"),tsc(U"uut"),tsc(U"septaambar"),tsc(U"oktoobar"),tsc(U"nowaambar"),tsc(U"desaambar")},.d_t_fmt=tsc(U"%a %d %b %Y %T"),.d_fmt=tsc(U"%d.%m.%Y"),.t_fmt=tsc(U"%T"),.t_fmt_ampm=tsc(U""),.date_fmt=tsc(U"%a %d %b %Y %T %Z"),.am_pm={tsc(U""),tsc(U"")},.week={7,19971130,1},.first_weekday=2},.messages={.yesexpr=tsc(U"^[+1wWyY]"),.noexpr=tsc(U"^[-0dDnN]"),.yesstr=tsc(U"waaw"),.nostr=tsc(U"déedet")},.paper={.width=210,.height=297},.telephone={.tel_int_fmt=tsc(U"+%c %a %l"),.tel_dom_fmt=tsc(U"%a %l"),.int_select=tsc(U"00"),.int_prefix=tsc(U"221")},.name={.name_fmt=tsc(U"%d%t%g%t%m%t%f")},.address={.postal_fmt=tsc(U"%f%N%a%N%d%N%b%N%s %h %e %r%N%z %T%N%c%N"),.country_name=tsc(U"Senegaal"),.country_ab2=tsc(U"SN"),.country_ab3=tsc(U"SEN"),.country_num=686,.country_car=tsc(U"SN"),.lang_name=tsc(U"Wolof"),.lang_ab=tsc(U"wo"),.lang_term=tsc(U"wol"),.lang_lib=tsc(U"wol")},.measurement={.measurement=1}};


}
}

#include"../main.h"